SELECT
	[Ethnic_Code], [Description]
INTO #temp
FROM (VALUES
('aam', 'African American/African American'),
('afc', 'African Continental'),
('afg', 'Afghan'),
('aka', 'Akan/Ashanti'),
('alb', 'Albanian'),
('ale', 'Aleut'),
('alr', 'Algerian'),
('anl', 'Angolan'),
('ara', 'Arab'),
('arm', 'Armenian'),
('asn', 'Other Asian/Other Oriental'),
('aus', 'Australian'),
('aut', 'Austrian'),
('aze', 'Azerbaijani'),
('bah', 'Bahraini'),
('baq', 'Basque'),
('beg', 'Belgian'),
('bei', 'Beninese'),
('bel', 'Byelorussian/Belorussian'),
('ben', 'Bangladeshi/Bengali'),
('bhu', 'Bhutanese'),
('bos', 'Bosnian/Bosniak/Bosnian Muslim'),
('brk', 'Burkinabe (Burkina Faso)'),
('brz', 'Brazilian'),
('bso', 'Basotho'),
('bts', 'Batswana (Botswana)'),
('bul', 'Bulgarian'),
('bun', 'Burundi'),
('bur', 'Burmese (Myanmar)'),
('caa', 'Caribbean African American'),
('caf', 'Central African (Central African Republic)'),
('cam', 'Cameroonian'),
('chd', 'Chadian'),
('che', 'Chechen'),
('chi', 'Chinese'),
('com', 'Comoran/Comoros'),
('con', 'Congolese'),
('cze', 'Czech'),
('dan', 'Danish'),
('div', 'Maldivian and Tongan'),
('dji', 'Djiboutian'),
('drc', 'Congolese (DRC)'),
('dut', 'Dutch'),
('egy', 'Egyptian'),
('eng', 'English'),
('eqg', 'Equatorial Guinean'),
('est', 'Estonian'),
('eth', 'Ethiopian'),
('fij', 'Fijian'),
('fil', 'Filipino/Philippine'),
('fin', 'Finnish'),
('fre', 'French'),
('gaa', 'Ghanaian'),
('gab', 'Gabonese'),
('gam', 'Gambian'),
('geo', 'Georgian'),
('ger', 'German'),
('glv', 'Manx'),
('gre', 'Greek'),
('gui', 'Guinean (Guinea-Bissau)'),
('guy', 'Guyanese'),
('hat', 'Haitian'),
('hau', 'Hausa'),
('haw', 'Hawaiian'),
('heb', 'Hebrew'),
('hmn', 'Hmong'),
('hrv', 'Croatian'),
('hun', 'Hungarian'),
('ibo', 'Igbo'),
('ice', 'Icelandic'),
('iku', 'Inuit'),
('ind', 'Indonesian'),
('inn', 'Indian/Asian Indian'),
('irq', 'Iraqi'),
('irs', 'Irish'),
('ita', 'Italian'),
('ivo', 'Ivorian (Ivory Coast)'),
('jam', 'Jamaican'),
('jew', 'Jewish'),
('jpn', 'Japanese'),
('kaz', 'Kazakh'),
('ken', 'Kenyan'),
('khm', 'Khmer'),
('kir', 'Kirghiz'),
('kor', 'Korean'),
('kur', 'Kurdish'),
('kuw', 'Kuwaiti'),
('lao', 'Laotian'),
('lav', 'Latvian'),
('lby', 'Libyan'),
('lib', 'Liberian'),
('lie', 'Liechtenstein'),
('lit', 'Lithuanian'),
('ltz', 'Luxembourgian'),
('mac', 'Macedonian'),
('mau', 'Mauritanian'),
('maw', 'Malawian'),
('may', 'Malay'),
('mlg', 'Malagasy (Madagascar)'),
('mli', 'Malian'),
('mlt', 'Maltese'),
('mol', 'Moldavian/Moldovan'),
('mon', 'Mongolian'),
('mor', 'Moroccan'),
('moz', 'Mozambican (Mozambique)'),
('mul', 'Multi Ethnic'),
('nam', 'Namibian'),
('nat', 'Native American'),
('nau', 'Nauruan'),
('nep', 'Nepalese'),
('nga', 'Nigerian (Nigeria)'),
('ngr', 'Nigerien (Niger)'),
('nor', 'Norwegian'),
('nze', 'New Zealand'),
('pak', 'Pakistani'),
('per', 'Persian'),
('pil', 'Pili'),
('png', 'Papua New Guinean'),
('pol', 'Polish'),
('por', 'Portuguese'),
('qat', 'Qatari'),
('rum', 'Romanian'),
('rus', 'Russian'),
('rwa', 'Rwandan/Ruandan'),
('saf', 'South African'),
('sar', 'Southern African'),
('sau', 'Saudi'),
('sco', 'Scottish'),
('sen', 'Senegalese'),
('sey', 'Seychelles'),
('sin', 'Sri Lankan/Sinhalese'),
('sle', 'Sierra Leonean'),
('slo', 'Slovak'),
('slv', 'Slovenian'),
('smo', 'Samoan'),
('som', 'Somali'),
('sot', 'Sotho (Lesotho)'),
('spa', 'Hispanic/Spanish'),
('srp', 'Serbian'),
('ssw', 'Swazi'),
('sud', 'Sudanese/South Sudanese'),
('sur', 'Surinamese'),
('swa', 'Swahili'),
('swe', 'Swedish'),
('sws', 'Swiss'),
('syr', 'Syrian'),
('tan', 'Tanzanian'),
('tel', 'Telugu'),
('tgk', 'Tajik'),
('tha', 'Thai'),
('tib', 'Tibetan'),
('tiw', 'Taiwanese'),
('tol', 'Togolese'),
('ton', 'Tongan'),
('tri', 'Trinidadian'),
('tuk', 'Turkmen'),
('tun', 'Tunisian'),
('tur', 'Turkish'),
('ugd', 'Ugandan'),
('ukr', 'Ukrainian'),
('und', 'Default/Undetermined/Unknown'),
('uzb', 'Uzbek'),
('van', 'Vanuatuan'),
('vie', 'Vietnamese'),
('wel', 'Welsh'),
('xho', 'Xhosa'),
('yem', 'Yemeni'),
('yor', 'Yoruba'),
('zai', 'Zairean'),
('zam', 'Zambian'),
('zim', 'Zimbabwean'),
('zul', 'Zulu'))
vdata ([Ethnic_Code], [Description])


SELECT [Ethnic_Code], [Description] INTO EthnicCode FROM #temp
CREATE UNIQUE CLUSTERED INDEX [Ethnic_Code] ON EthnicCode ([Ethnic_Code] )
CREATE UNIQUE NONCLUSTERED INDEX [Description] ON EthnicCode ([Description] )
