SELECT
	[Language_Preference], [Description]
	INTO #temp
FROM (VALUES
('afr', 'Afrikaans'),
('aka', 'Akan/Ashanti'),
('alb', 'Albanian'),
('amh', 'Amharic'),
('ara', 'Arabic'),
('arm', 'Armenian'),
('aze', 'Azeri'),
('baq', 'Basque'),
('ben', 'Bengali'),
('bnt', 'Bantu'),
('bul', 'Bulgarian'),
('bur', 'Burmese'),
('can', 'Cantonese'),
('che', 'Chechen'),
('chi', 'Chinese'),
('com', 'Comorian'),
('cze', 'Czech'),
('dan', 'Danish'),
('dut', 'Dutch/Flemish'),
('dzo', 'Dzongkha'),
('eng', 'English (Default)'),
('est', 'Estonian'),
('fin', 'Finnish'),
('fre', 'French'),
('gaa', 'Ga'),
('geo', 'Georgian'),
('ger', 'German'),
('gre', 'Greek'),
('hau', 'Hausa'),
('heb', 'Hebrew'),
('hin', 'Asian Indian (Hindi or Other)'),
('hmn', 'Hmong'),
('hun', 'Hungarian'),
('ibo', 'Ibo/Igbo'),
('ice', 'Icelandic'),
('iku', 'Inuktitut'),
('ind', 'Indonesian'),
('ita', 'Italian'),
('jpn', 'Japanese'),
('kaz', 'Kazakh'),
('khm', 'Khmer'),
('kir', 'Kirghiz'),
('kor', 'Korean'),
('kur', 'Kurdish'),
('lao', 'Laotian'),
('lav', 'Latvian'),
('lit', 'Lithuanian'),
('mac', 'Macedonian'),
('may', 'Malay'),
('mlg', 'Malagasy'),
('mol', 'Moldavian/Moldovan'),
('mon', 'Mongolian'),
('nep', 'Nepali'),
('nor', 'Norwegian'),
('orm', 'Oromo'),
('per', 'Farsi/Persian'),
('pol', 'Polish'),
('por', 'Portuguese'),
('pus', 'Pashtu/Pashto'),
('rum', 'Romanian'),
('rus', 'Russian'),
('sin', 'Sinhalese'),
('slo', 'Slovakian'),
('slv', 'Slovenian'),
('smo', 'Samoan'),
('som', 'Somali'),
('sot', 'Sotho'),
('spa', 'Spanish'),
('spr', 'Serbo-Croatian'),
('ssw', 'Swazi'),
('swa', 'Swahili'),
('swe', 'Swedish'),
('tgk', 'Tajik'),
('tgl', 'Tagalog'),
('tha', 'Thai'),
('tib', 'Tibetan'),
('ton', 'Tongan'),
('tpi', 'Tok Pisin'),
('tsn', 'Tswana'),
('tuk', 'Turkmeni/Turkmen'),
('tur', 'Turkish'),
('und', 'Undetermined/Unknown'),
('urd', 'Urdu'),
('uzb', 'Uzbeki/Uzbek'),
('vie', 'Vietnamese'),
('xho', 'Xhosa'),
('yor', 'Yoruba'),
('zul', 'Zulu'))
vdata ([Language_Preference], [Description])


SELECT	[Language_Preference], [Description] INTO LanguagePreference FROM #temp

CREATE UNIQUE CLUSTERED INDEX [Language_Preference] ON LanguagePreference ([Language_Preference])
CREATE UNIQUE NONCLUSTERED INDEX [Description] ON LanguagePreference ([Description])