SELECT 
* 
INTO #cols
FROM util.dbo.parsedelimited('Quantarium_Internal_PID	FIPS_Code	Assessors_Parcel_Number	Duplicate_APN	Tax_Account_Number	Current_Owner_Name	CO_Mail_Care_of_Name	CO_Mail_Street_Address	CO_Mailing_City	CO_Mailing_State	CO_Mailing_Zip_Code	CO_Mailing_Zip_Plus4Code	CO_Unit_Number	CO_Unit_Type	Mail_Care_Of_Name_Indicator	Owner_Occupied	Owner1FirstName	Owner1MiddleName	Owner1LastName	Owner2Firstname	Owner2MiddleName	Owner2LastName	ParsedOwnerSourceCode	Buyer_ID_Code_1	Buyer_Vesting_Code	Length_of_Residence_Months	Length_of_Residence_Code	Ownership_Start_Date	LSale_Book_Number	LSale_Page_Number	LSale_Document_Number	LSale_Document_Type_Code	LSale_Price	LSale_Price_Code	LSale_Recording_Date	LSale_reo_flag	LSale_distressed_sale_flag	Last_Transfer_Date	LValid_Book_Number	LValid_Page_Number	LValid_Document_Number	LValid_Document_Type_Code	LValid_Price	LValid_Price_Code	LValid_Recording_Date	LValid_reo_flag	LValid_distressed_sale_flag	Last_Sale_date	PSale_Book_Number	PSale_Page_Number	PSale_Document_Number	PSale_Document_Type_Code	PSale_Price	PSale_Price_Code	PSale_Recording_Date	PSale_reo_flag	PSale_distressed_sale_flag	Prior_Transfer_date	PValid_Book_Number	PValid_Page_Number	PValid_Document_Number	PValid_Document_Type_Code	PValid_Price	PValid_Price_Code	PValid_Recording_Date	PValid_reo_flag	PValid_distressed_sale_flag	Prior_Sale_Date	Recorders_Document_Number_from_Assessment	Recorders_Book_Number_from_Assessment	Recorders_Page_Number_from_Assessment	Recording_Date_from_Assessment	Document_Type_from_Assessment	Sales_Price_from_Assessment	Sales_Price_Code_from_Assessment	Property_Full_Street_Address	Property_City_Name	Property_State	Property_Zip_Code	Property_Zip_Plus4Code	Property_House_Number	Property_Street_Direction_Left	Property_Street_Name	Property_Street_Suffix	Property_Street_Direction_Right	Property_Unit_Number	Property_Unit_Type	PA_Carrier_Route	PA_Census_Tract	PA_Latitude	PA_Longitude	Match_Code	Location_Code	Legal_Assessors_Map_Ref	Legal_Brief_Description	Legal_Brief_Description_FULL	Legal_Section_Township__Range_Meridian	Legal_Block	Legal_Lot_Number	Legal_City_Township_Municipality	Legal_District	Legal_Section	Legal_Land_Lot	Legal_Lot_Code	Legal_Phase_Number	Legal_Subdivision_Name	Legal_Tract_Number	Legal_Unit	Assessed_Improvement_Value	Assessed_Land_Value	Total_Assessed_Value	Assessment_Year	California_HomeOwners_Exemption	Tax_Exemption_Codes	Market_Value_Improvement	Market_Value_Land	Total_Market_Value	Market_Value_Year	School_Tax_District_1	School_Tax_District_1_Indicator	School_Tax_District_2	School_Tax_District_2_Indicator	School_Tax_District_3	School_Tax_District_3_Indicator	Tax_Amount	Tax_Year	Tax_Delinquent_Year	Tax_Rate_Code_Area	Neighborhood_Code	Condo_Project_Bldg_Name	Old_APN	Alt_Old_APN_Indicator	Certification_Date	Edition	LotSize_Acres	LotSize_Depth_Feet	LotSize_Frontage_Feet	LotSize_Square_Feet	Lot_Size_or_Area	Lot_Size_Area_Unit	Original_Lot_Size_or_Area	Topography	Site_Influence	Air_Conditioning	Air_Conditioning_Type	Amenities	Amenities_2	Basement	Building_Area	Building_Area_1	Building_Area_1_Indicator	Building_Area_2	Building_Area_2_Indicator	Building_Area_3	Building_Area_3_Indicator	Building_Area_4	Building_Area_4_Indicator	Building_Area_5	Building_Area_5_Indicator	Building_Area_6	Building_Area_6_Indicator	Building_Area_7	Building_Area_7_Indicator	Building_Class	Building_Condition	Building_Quality	Comments_Summary_of_Building_Cards	Effective_Year_Built	Elevator	Exterior_Walls	Extra_Features_1_Area	Extra_Features_1_Indicator	Extra_Features_2_Area	Extra_Features_2_Indicator	Extra_Features_3_Area	Extra_Features_3_Indicator	Extra_Features_4_Area	Extra_Features_4_Indicator	Fireplace	FLOOR_COVER	Foundation	Garage_Cars	Garage_Type	Heating	Heating_Fuel_Type	Interior_Walls	Main_Building_Area_Indicator	No_of_Buildings	No_of_Stories	Number_of_Baths	Number_of_Bedrooms	Number_of_Partial_Baths	Number_of_Units	Other_Impr_Building_Area_1	Other_Impr_Building_Area_2	Other_Impr_Building_Area_3	Other_Impr_Building_Area_4	Other_Impr_Building_Area_5	Other_Impr_Building_Indicator_1	Other_Impr_Building_Indicator_2	Other_Impr_Building_Indicator_3	Other_Impr_Building_Indicator_4	Other_Impr_Building_Indicator_5	Other_Rooms	N_of_Plumbing_Fixtures	Pool	Roof_Cover	Roof_Type	Sewer	Standardized_Land_Use_Code	Style	Total_Number_of_Rooms	Type_Construction	Water	Year_Built	Zoning	Mtg01_lender_name_beneficiary	Mtg01_lender_type	Mtg01_original_date_of_contract	Mtg01_recording_date	Mtg01_Loan_Amount	Mtg01_loan_type	Mtg01_type_financing	Mtg01_interest_rate	Mtg01_due_date	Mtg01_Adjustable_Rate_Rider	Mtg01_Adjustable_Rate_Index	Mtg01_Change_Index	Mtg01_Rate_Change_Frequency	Mtg01_Interest_Rate_Not_Greater_Than	Mtg01_Interest_Rate_Not_Less_Than	Mtg01_Maximum_Interest_Rate	Mtg01_Interest_Only_Period	Mtg01_fixed_step_conversion_rate_rider	Mtg01_First_Change_Date_Year_Conversion_Rider	Mtg01_First_Change_Date_Month_Day_Conversion_Rider	Mtg01_Prepayment_Rider	Mtg01_Prepayment_Term_Penalty_Rider	Mtg01_Title_Company_Name	Mtg01_Lender_Name	Mtg01_Lender_Mail_Full_Street_Address	Mtg01_Lender_Mail_Unit	Mtg01_Lender_Mail_City	Mtg01_Lender_Mail_State	Mtg01_Lender_Mail_Zip_Code	Mtg01_Lender_Mail_Zip_Plus4Code	Mtg01_Loan_Term_Months	Mtg01_Loan_Term_Years	Mtg01_loan_number	Mtg01_Construction_Loan	Mtg01_Cash_Purchase	Mtg01_StandAlone_Refi	Mtg01_Equity_Credit_Line	Mtg01_Curr_Est_Bal	Mtg01_Purpose_Of_Loan	Mtg01_Purchase_Mtg_Ind	Mtg01_Est_Monthly_P&I	Mtg01_Est_Monthly_Principal	Mtg01_Est_Monthly_Interest	Mtg01_Curr_Est_Int_Rate	Mtg01_Assigned_Lender_Name	Mtg01_Assignment_Date	Mtg01_Number_of_Assignments	Mtg01_PreForeclosure_Status	Mtg01_PreFcl_Recording_Date	Mtg01_PreFcl_Filing_Date	Mtg01_PreFcl_Case_Trustee_Sale_Nbr	Mtg01_PreFcl_Auction_Date	Mtg02_lender_name_beneficiary	Mtg02_lender_type	Mtg02_original_date_of_contract	Mtg02_recording_date	Mtg02_Loan_Amount	Mtg02_loan_type	Mtg02_type_financing	Mtg02_interest_rate	Mtg02_due_date	Mtg02_Adjustable_Rate_Rider	Mtg02_Adjustable_Rate_Index	Mtg02_Change_Index	Mtg02_Rate_Change_Frequency	Mtg02_Interest_Rate_Not_Greater_Than	Mtg02_Interest_Rate_Not_Less_Than	Mtg02_Maximum_Interest_Rate	Mtg02_Interest_Only_Period	Mtg02_fixed_step_conversion_rate_rider	Mtg02_First_Change_Date_Year_Conversion_Rider	Mtg02_First_Change_Date_Month_Day_Conversion_Rider	Mtg02_Prepayment_Rider	Mtg02_Prepayment_Term_Penalty_Rider	Mtg02_Title_Company_Name	Mtg02_Lender_Name	Mtg02_Lender_Mail_Full_Street_Address	Mtg02_Lender_Mail_Unit	Mtg02_Lender_Mail_City	Mtg02_Lender_Mail_State	Mtg02_Lender_Mail_Zip_Code	Mtg02_Lender_Mail_Zip_Plus4Code	Mtg02_Loan_Term_Months	Mtg02_Loan_Term_Years	Mtg02_loan_number	Mtg02_Construction_Loan	Mtg02_Cash_Purchase	Mtg02_StandAlone_Refi	Mtg02_Equity_Credit_Line	Mtg02_Curr_Est_Bal	Mtg02_Purpose_Of_Loan	Mtg02_Purchase_Mtg_Ind	Mtg02_Est_Monthly_P&I	Mtg02_Est_Monthly_Principal	Mtg02_Est_Monthly_Interest	Mtg02_Curr_Est_Int_Rate	Mtg02_Assigned_Lender_Name	Mtg02_Assignment_Date	Mtg02_Number_of_Assignments	Mtg02_PreForeclosure_Status	Mtg02_PreFcl_Recording_Date	Mtg02_PreFcl_Filing_Date	Mtg02_PreFcl_Case_Trustee_Sale_Nbr	Mtg02_PreFcl_Auction_Date	Mtg03_lender_name_beneficiary	Mtg03_lender_type	Mtg03_original_date_of_contract	Mtg03_recording_date	Mtg03_Loan_Amount	Mtg03_loan_type	Mtg03_type_financing	Mtg03_interest_rate	Mtg03_due_date	Mtg03_Adjustable_Rate_Rider	Mtg03_Adjustable_Rate_Index	Mtg03_Change_Index	Mtg03_Rate_Change_Frequency	Mtg03_Interest_Rate_Not_Greater_Than	Mtg03_Interest_Rate_Not_Less_Than	Mtg03_Maximum_Interest_Rate	Mtg03_Interest_Only_Period	Mtg03_fixed_step_conversion_rate_rider	Mtg03_First_Change_Date_Year_Conversion_Rider	Mtg03_First_Change_Date_Month_Day_Conversion_Rider	Mtg03_Prepayment_Rider	Mtg03_Prepayment_Term_Penalty_Rider	Mtg03_Title_Company_Name	Mtg03_Lender_Name	Mtg03_Lender_Mail_Full_Street_Address	Mtg03_Lender_Mail_Unit	Mtg03_Lender_Mail_City	Mtg03_Lender_Mail_State	Mtg03_Lender_Mail_Zip_Code	Mtg03_Lender_Mail_Zip_Plus4Code	Mtg03_Loan_Term_Months	Mtg03_Loan_Term_Years	Mtg03_loan_number	Mtg03_Construction_Loan	Mtg03_Cash_Purchase	Mtg03_StandAlone_Refi	Mtg03_Equity_Credit_Line	Mtg03_Curr_Est_Bal	Mtg03_Purpose_Of_Loan	Mtg03_Purchase_Mtg_Ind	Mtg03_Est_Monthly_P&I	Mtg03_Est_Monthly_Principal	Mtg03_Est_Monthly_Interest	Mtg03_Curr_Est_Int_Rate	Mtg03_Assigned_Lender_Name	Mtg03_Assignment_Date	Mtg03_Number_of_Assignments	Mtg03_PreForeclosure_Status	Mtg03_PreFcl_Recording_Date	Mtg03_PreFcl_Filing_Date	Mtg03_PreFcl_Case_Trustee_Sale_Nbr	Mtg03_PreFcl_Auction_Date	Mtg04_lender_name_beneficiary	Mtg04_lender_type	Mtg04_original_date_of_contract	Mtg04_recording_date	Mtg04_Loan_Amount	Mtg04_loan_type	Mtg04_type_financing	Mtg04_interest_rate	Mtg04_due_date	Mtg04_Adjustable_Rate_Rider	Mtg04_Adjustable_Rate_Index	Mtg04_Change_Index	Mtg04_Rate_Change_Frequency	Mtg04_Interest_Rate_Not_Greater_Than	Mtg04_Interest_Rate_Not_Less_Than	Mtg04_Maximum_Interest_Rate	Mtg04_Interest_Only_Period	Mtg04_fixed_step_conversion_rate_rider	Mtg04_First_Change_Date_Year_Conversion_Rider	Mtg04_First_Change_Date_Month_Day_Conversion_Rider	Mtg04_Prepayment_Rider	Mtg04_Prepayment_Term_Penalty_Rider	Mtg04_Title_Company_Name	Mtg04_Lender_Name	Mtg04_Lender_Mail_Full_Street_Address	Mtg04_Lender_Mail_Unit	Mtg04_Lender_Mail_City	Mtg04_Lender_Mail_State	Mtg04_Lender_Mail_Zip_Code	Mtg04_Lender_Mail_Zip_Plus4Code	Mtg04_Loan_Term_Months	Mtg04_Loan_Term_Years	Mtg04_loan_number	Mtg04_Construction_Loan	Mtg04_Cash_Purchase	Mtg04_StandAlone_Refi	Mtg04_Equity_Credit_Line	Mtg04_Curr_Est_Bal	Mtg04_Purpose_Of_Loan	Mtg04_Purchase_Mtg_Ind	Mtg04_Est_Monthly_P&I	Mtg04_Est_Monthly_Principal	Mtg04_Est_Monthly_Interest	Mtg04_Curr_Est_Int_Rate	Mtg04_Assigned_Lender_Name	Mtg04_Assignment_Date	Mtg04_Number_of_Assignments	Mtg04_PreForeclosure_Status	Mtg04_PreFcl_Recording_Date	Mtg04_PreFcl_Filing_Date	Mtg04_PreFcl_Case_Trustee_Sale_Nbr	Mtg04_PreFcl_Auction_Date	Additional_Open_Lien_Count	Additional_Open_Lien_Balance	Total_Open_Lien_Count	Total_Open_Lien_Balance	Total_Financing_History_Count	Current_Est_LTV_Combined	Current_Est_LTV_Range_Code	Current_Est_Equity_Dollars	Current_Est_Equity_Range_Code	Purchase_LTV	Current_Foreclosure_Status	Foreclosure_Recording_Date	Foreclosure_filing_date	Foreclosure_Case_Number	Foreclosure_Auction_Date	ESTIMATED_VALUE	PRICE_RANGE_MIN	PRICE_RANGE_MAX	FSD_SCORE	CONFIDENCE_SCORE	QVM_Value_Range_Code	QVM_asof_Date	Trans_asof_Date	Record_Creation_Date	Quantarium_Version','	')


SELECT CONCAT('CREATE TABLE [dbo].[Houseamp_WA_OL_Chg_20210913](
	',STRING_AGG(CONCAT(CAST(QUOTENAME(Field) AS VARCHAR(MAX)), ' VARCHAR(8000)'),',
	') WITHIN GROUP(ORDER BY fieldNum),'
)')
FROM #cols
GO

-- bcp "[Evan].[dbo].[Houseamp_WA_OL_Chg_20210913]" in "C:\Temp\Houseamp_WA_OL_Chg_20210913\Houseamp_WA_OL_Chg_20210913.txt" -F 2 -c -t \t -S DESKTOP-GU73BTH -a 65535 -T

SELECT CONCAT('SELECT
	',STRING_AGG(CONCAT(CAST(NULL AS VARCHAR(MAX)), 'CASE WHEN TRIM([',Field,']) IN ('''',''NULL'') THEN NULL ELSE TRIM([',Field,']) END AS [',Field,']'),',
	') WITHIN GROUP(ORDER BY fieldNum),'
INTO [dbo].[Houseamp_WA_OL_Chg_20210913_New]
FROM [dbo].[Houseamp_WA_OL_Chg_20210913]
') AS SQL
FROM #cols
GO



DROP TABLE IF EXISTS [dbo].[Houseamp_WA_OL_Chg_20210913]
CREATE TABLE [dbo].[Houseamp_WA_OL_Chg_20210913](
	[Quantarium_Internal_PID] VARCHAR(8000),
	[FIPS_Code] VARCHAR(8000),
	[Assessors_Parcel_Number] VARCHAR(8000),
	[Duplicate_APN] VARCHAR(8000),
	[Tax_Account_Number] VARCHAR(8000),
	[Current_Owner_Name] VARCHAR(8000),
	[CO_Mail_Care_of_Name] VARCHAR(8000),
	[CO_Mail_Street_Address] VARCHAR(8000),
	[CO_Mailing_City] VARCHAR(8000),
	[CO_Mailing_State] VARCHAR(8000),
	[CO_Mailing_Zip_Code] VARCHAR(8000),
	[CO_Mailing_Zip_Plus4Code] VARCHAR(8000),
	[CO_Unit_Number] VARCHAR(8000),
	[CO_Unit_Type] VARCHAR(8000),
	[Mail_Care_Of_Name_Indicator] VARCHAR(8000),
	[Owner_Occupied] VARCHAR(8000),
	[Owner1FirstName] VARCHAR(8000),
	[Owner1MiddleName] VARCHAR(8000),
	[Owner1LastName] VARCHAR(8000),
	[Owner2Firstname] VARCHAR(8000),
	[Owner2MiddleName] VARCHAR(8000),
	[Owner2LastName] VARCHAR(8000),
	[ParsedOwnerSourceCode] VARCHAR(8000),
	[Buyer_ID_Code_1] VARCHAR(8000),
	[Buyer_Vesting_Code] VARCHAR(8000),
	[Length_of_Residence_Months] VARCHAR(8000),
	[Length_of_Residence_Code] VARCHAR(8000),
	[Ownership_Start_Date] VARCHAR(8000),
	[LSale_Book_Number] VARCHAR(8000),
	[LSale_Page_Number] VARCHAR(8000),
	[LSale_Document_Number] VARCHAR(8000),
	[LSale_Document_Type_Code] VARCHAR(8000),
	[LSale_Price] VARCHAR(8000),
	[LSale_Price_Code] VARCHAR(8000),
	[LSale_Recording_Date] VARCHAR(8000),
	[LSale_reo_flag] VARCHAR(8000),
	[LSale_distressed_sale_flag] VARCHAR(8000),
	[Last_Transfer_Date] VARCHAR(8000),
	[LValid_Book_Number] VARCHAR(8000),
	[LValid_Page_Number] VARCHAR(8000),
	[LValid_Document_Number] VARCHAR(8000),
	[LValid_Document_Type_Code] VARCHAR(8000),
	[LValid_Price] VARCHAR(8000),
	[LValid_Price_Code] VARCHAR(8000),
	[LValid_Recording_Date] VARCHAR(8000),
	[LValid_reo_flag] VARCHAR(8000),
	[LValid_distressed_sale_flag] VARCHAR(8000),
	[Last_Sale_date] VARCHAR(8000),
	[PSale_Book_Number] VARCHAR(8000),
	[PSale_Page_Number] VARCHAR(8000),
	[PSale_Document_Number] VARCHAR(8000),
	[PSale_Document_Type_Code] VARCHAR(8000),
	[PSale_Price] VARCHAR(8000),
	[PSale_Price_Code] VARCHAR(8000),
	[PSale_Recording_Date] VARCHAR(8000),
	[PSale_reo_flag] VARCHAR(8000),
	[PSale_distressed_sale_flag] VARCHAR(8000),
	[Prior_Transfer_date] VARCHAR(8000),
	[PValid_Book_Number] VARCHAR(8000),
	[PValid_Page_Number] VARCHAR(8000),
	[PValid_Document_Number] VARCHAR(8000),
	[PValid_Document_Type_Code] VARCHAR(8000),
	[PValid_Price] VARCHAR(8000),
	[PValid_Price_Code] VARCHAR(8000),
	[PValid_Recording_Date] VARCHAR(8000),
	[PValid_reo_flag] VARCHAR(8000),
	[PValid_distressed_sale_flag] VARCHAR(8000),
	[Prior_Sale_Date] VARCHAR(8000),
	[Recorders_Document_Number_from_Assessment] VARCHAR(8000),
	[Recorders_Book_Number_from_Assessment] VARCHAR(8000),
	[Recorders_Page_Number_from_Assessment] VARCHAR(8000),
	[Recording_Date_from_Assessment] VARCHAR(8000),
	[Document_Type_from_Assessment] VARCHAR(8000),
	[Sales_Price_from_Assessment] VARCHAR(8000),
	[Sales_Price_Code_from_Assessment] VARCHAR(8000),
	[Property_Full_Street_Address] VARCHAR(8000),
	[Property_City_Name] VARCHAR(8000),
	[Property_State] VARCHAR(8000),
	[Property_Zip_Code] VARCHAR(8000),
	[Property_Zip_Plus4Code] VARCHAR(8000),
	[Property_House_Number] VARCHAR(8000),
	[Property_Street_Direction_Left] VARCHAR(8000),
	[Property_Street_Name] VARCHAR(8000),
	[Property_Street_Suffix] VARCHAR(8000),
	[Property_Street_Direction_Right] VARCHAR(8000),
	[Property_Unit_Number] VARCHAR(8000),
	[Property_Unit_Type] VARCHAR(8000),
	[PA_Carrier_Route] VARCHAR(8000),
	[PA_Census_Tract] VARCHAR(8000),
	[PA_Latitude] VARCHAR(8000),
	[PA_Longitude] VARCHAR(8000),
	[Match_Code] VARCHAR(8000),
	[Location_Code] VARCHAR(8000),
	[Legal_Assessors_Map_Ref] VARCHAR(8000),
	[Legal_Brief_Description] VARCHAR(8000),
	[Legal_Brief_Description_FULL] VARCHAR(8000),
	[Legal_Section_Township__Range_Meridian] VARCHAR(8000),
	[Legal_Block] VARCHAR(8000),
	[Legal_Lot_Number] VARCHAR(8000),
	[Legal_City_Township_Municipality] VARCHAR(8000),
	[Legal_District] VARCHAR(8000),
	[Legal_Section] VARCHAR(8000),
	[Legal_Land_Lot] VARCHAR(8000),
	[Legal_Lot_Code] VARCHAR(8000),
	[Legal_Phase_Number] VARCHAR(8000),
	[Legal_Subdivision_Name] VARCHAR(8000),
	[Legal_Tract_Number] VARCHAR(8000),
	[Legal_Unit] VARCHAR(8000),
	[Assessed_Improvement_Value] VARCHAR(8000),
	[Assessed_Land_Value] VARCHAR(8000),
	[Total_Assessed_Value] VARCHAR(8000),
	[Assessment_Year] VARCHAR(8000),
	[California_HomeOwners_Exemption] VARCHAR(8000),
	[Tax_Exemption_Codes] VARCHAR(8000),
	[Market_Value_Improvement] VARCHAR(8000),
	[Market_Value_Land] VARCHAR(8000),
	[Total_Market_Value] VARCHAR(8000),
	[Market_Value_Year] VARCHAR(8000),
	[School_Tax_District_1] VARCHAR(8000),
	[School_Tax_District_1_Indicator] VARCHAR(8000),
	[School_Tax_District_2] VARCHAR(8000),
	[School_Tax_District_2_Indicator] VARCHAR(8000),
	[School_Tax_District_3] VARCHAR(8000),
	[School_Tax_District_3_Indicator] VARCHAR(8000),
	[Tax_Amount] VARCHAR(8000),
	[Tax_Year] VARCHAR(8000),
	[Tax_Delinquent_Year] VARCHAR(8000),
	[Tax_Rate_Code_Area] VARCHAR(8000),
	[Neighborhood_Code] VARCHAR(8000),
	[Condo_Project_Bldg_Name] VARCHAR(8000),
	[Old_APN] VARCHAR(8000),
	[Alt_Old_APN_Indicator] VARCHAR(8000),
	[Certification_Date] VARCHAR(8000),
	[Edition] VARCHAR(8000),
	[LotSize_Acres] VARCHAR(8000),
	[LotSize_Depth_Feet] VARCHAR(8000),
	[LotSize_Frontage_Feet] VARCHAR(8000),
	[LotSize_Square_Feet] VARCHAR(8000),
	[Lot_Size_or_Area] VARCHAR(8000),
	[Lot_Size_Area_Unit] VARCHAR(8000),
	[Original_Lot_Size_or_Area] VARCHAR(8000),
	[Topography] VARCHAR(8000),
	[Site_Influence] VARCHAR(8000),
	[Air_Conditioning] VARCHAR(8000),
	[Air_Conditioning_Type] VARCHAR(8000),
	[Amenities] VARCHAR(8000),
	[Amenities_2] VARCHAR(8000),
	[Basement] VARCHAR(8000),
	[Building_Area] VARCHAR(8000),
	[Building_Area_1] VARCHAR(8000),
	[Building_Area_1_Indicator] VARCHAR(8000),
	[Building_Area_2] VARCHAR(8000),
	[Building_Area_2_Indicator] VARCHAR(8000),
	[Building_Area_3] VARCHAR(8000),
	[Building_Area_3_Indicator] VARCHAR(8000),
	[Building_Area_4] VARCHAR(8000),
	[Building_Area_4_Indicator] VARCHAR(8000),
	[Building_Area_5] VARCHAR(8000),
	[Building_Area_5_Indicator] VARCHAR(8000),
	[Building_Area_6] VARCHAR(8000),
	[Building_Area_6_Indicator] VARCHAR(8000),
	[Building_Area_7] VARCHAR(8000),
	[Building_Area_7_Indicator] VARCHAR(8000),
	[Building_Class] VARCHAR(8000),
	[Building_Condition] VARCHAR(8000),
	[Building_Quality] VARCHAR(8000),
	[Comments_Summary_of_Building_Cards] VARCHAR(8000),
	[Effective_Year_Built] VARCHAR(8000),
	[Elevator] VARCHAR(8000),
	[Exterior_Walls] VARCHAR(8000),
	[Extra_Features_1_Area] VARCHAR(8000),
	[Extra_Features_1_Indicator] VARCHAR(8000),
	[Extra_Features_2_Area] VARCHAR(8000),
	[Extra_Features_2_Indicator] VARCHAR(8000),
	[Extra_Features_3_Area] VARCHAR(8000),
	[Extra_Features_3_Indicator] VARCHAR(8000),
	[Extra_Features_4_Area] VARCHAR(8000),
	[Extra_Features_4_Indicator] VARCHAR(8000),
	[Fireplace] VARCHAR(8000),
	[FLOOR_COVER] VARCHAR(8000),
	[Foundation] VARCHAR(8000),
	[Garage_Cars] VARCHAR(8000),
	[Garage_Type] VARCHAR(8000),
	[Heating] VARCHAR(8000),
	[Heating_Fuel_Type] VARCHAR(8000),
	[Interior_Walls] VARCHAR(8000),
	[Main_Building_Area_Indicator] VARCHAR(8000),
	[No_of_Buildings] VARCHAR(8000),
	[No_of_Stories] VARCHAR(8000),
	[Number_of_Baths] VARCHAR(8000),
	[Number_of_Bedrooms] VARCHAR(8000),
	[Number_of_Partial_Baths] VARCHAR(8000),
	[Number_of_Units] VARCHAR(8000),
	[Other_Impr_Building_Area_1] VARCHAR(8000),
	[Other_Impr_Building_Area_2] VARCHAR(8000),
	[Other_Impr_Building_Area_3] VARCHAR(8000),
	[Other_Impr_Building_Area_4] VARCHAR(8000),
	[Other_Impr_Building_Area_5] VARCHAR(8000),
	[Other_Impr_Building_Indicator_1] VARCHAR(8000),
	[Other_Impr_Building_Indicator_2] VARCHAR(8000),
	[Other_Impr_Building_Indicator_3] VARCHAR(8000),
	[Other_Impr_Building_Indicator_4] VARCHAR(8000),
	[Other_Impr_Building_Indicator_5] VARCHAR(8000),
	[Other_Rooms] VARCHAR(8000),
	[N_of_Plumbing_Fixtures] VARCHAR(8000),
	[Pool] VARCHAR(8000),
	[Roof_Cover] VARCHAR(8000),
	[Roof_Type] VARCHAR(8000),
	[Sewer] VARCHAR(8000),
	[Standardized_Land_Use_Code] VARCHAR(8000),
	[Style] VARCHAR(8000),
	[Total_Number_of_Rooms] VARCHAR(8000),
	[Type_Construction] VARCHAR(8000),
	[Water] VARCHAR(8000),
	[Year_Built] VARCHAR(8000),
	[Zoning] VARCHAR(8000),
	[Mtg01_lender_name_beneficiary] VARCHAR(8000),
	[Mtg01_lender_type] VARCHAR(8000),
	[Mtg01_original_date_of_contract] VARCHAR(8000),
	[Mtg01_recording_date] VARCHAR(8000),
	[Mtg01_Loan_Amount] VARCHAR(8000),
	[Mtg01_loan_type] VARCHAR(8000),
	[Mtg01_type_financing] VARCHAR(8000),
	[Mtg01_interest_rate] VARCHAR(8000),
	[Mtg01_due_date] VARCHAR(8000),
	[Mtg01_Adjustable_Rate_Rider] VARCHAR(8000),
	[Mtg01_Adjustable_Rate_Index] VARCHAR(8000),
	[Mtg01_Change_Index] VARCHAR(8000),
	[Mtg01_Rate_Change_Frequency] VARCHAR(8000),
	[Mtg01_Interest_Rate_Not_Greater_Than] VARCHAR(8000),
	[Mtg01_Interest_Rate_Not_Less_Than] VARCHAR(8000),
	[Mtg01_Maximum_Interest_Rate] VARCHAR(8000),
	[Mtg01_Interest_Only_Period] VARCHAR(8000),
	[Mtg01_fixed_step_conversion_rate_rider] VARCHAR(8000),
	[Mtg01_First_Change_Date_Year_Conversion_Rider] VARCHAR(8000),
	[Mtg01_First_Change_Date_Month_Day_Conversion_Rider] VARCHAR(8000),
	[Mtg01_Prepayment_Rider] VARCHAR(8000),
	[Mtg01_Prepayment_Term_Penalty_Rider] VARCHAR(8000),
	[Mtg01_Title_Company_Name] VARCHAR(8000),
	[Mtg01_Lender_Name] VARCHAR(8000),
	[Mtg01_Lender_Mail_Full_Street_Address] VARCHAR(8000),
	[Mtg01_Lender_Mail_Unit] VARCHAR(8000),
	[Mtg01_Lender_Mail_City] VARCHAR(8000),
	[Mtg01_Lender_Mail_State] VARCHAR(8000),
	[Mtg01_Lender_Mail_Zip_Code] VARCHAR(8000),
	[Mtg01_Lender_Mail_Zip_Plus4Code] VARCHAR(8000),
	[Mtg01_Loan_Term_Months] VARCHAR(8000),
	[Mtg01_Loan_Term_Years] VARCHAR(8000),
	[Mtg01_loan_number] VARCHAR(8000),
	[Mtg01_Construction_Loan] VARCHAR(8000),
	[Mtg01_Cash_Purchase] VARCHAR(8000),
	[Mtg01_StandAlone_Refi] VARCHAR(8000),
	[Mtg01_Equity_Credit_Line] VARCHAR(8000),
	[Mtg01_Curr_Est_Bal] VARCHAR(8000),
	[Mtg01_Purpose_Of_Loan] VARCHAR(8000),
	[Mtg01_Purchase_Mtg_Ind] VARCHAR(8000),
	[Mtg01_Est_Monthly_P&I] VARCHAR(8000),
	[Mtg01_Est_Monthly_Principal] VARCHAR(8000),
	[Mtg01_Est_Monthly_Interest] VARCHAR(8000),
	[Mtg01_Curr_Est_Int_Rate] VARCHAR(8000),
	[Mtg01_Assigned_Lender_Name] VARCHAR(8000),
	[Mtg01_Assignment_Date] VARCHAR(8000),
	[Mtg01_Number_of_Assignments] VARCHAR(8000),
	[Mtg01_PreForeclosure_Status] VARCHAR(8000),
	[Mtg01_PreFcl_Recording_Date] VARCHAR(8000),
	[Mtg01_PreFcl_Filing_Date] VARCHAR(8000),
	[Mtg01_PreFcl_Case_Trustee_Sale_Nbr] VARCHAR(8000),
	[Mtg01_PreFcl_Auction_Date] VARCHAR(8000),
	[Mtg02_lender_name_beneficiary] VARCHAR(8000),
	[Mtg02_lender_type] VARCHAR(8000),
	[Mtg02_original_date_of_contract] VARCHAR(8000),
	[Mtg02_recording_date] VARCHAR(8000),
	[Mtg02_Loan_Amount] VARCHAR(8000),
	[Mtg02_loan_type] VARCHAR(8000),
	[Mtg02_type_financing] VARCHAR(8000),
	[Mtg02_interest_rate] VARCHAR(8000),
	[Mtg02_due_date] VARCHAR(8000),
	[Mtg02_Adjustable_Rate_Rider] VARCHAR(8000),
	[Mtg02_Adjustable_Rate_Index] VARCHAR(8000),
	[Mtg02_Change_Index] VARCHAR(8000),
	[Mtg02_Rate_Change_Frequency] VARCHAR(8000),
	[Mtg02_Interest_Rate_Not_Greater_Than] VARCHAR(8000),
	[Mtg02_Interest_Rate_Not_Less_Than] VARCHAR(8000),
	[Mtg02_Maximum_Interest_Rate] VARCHAR(8000),
	[Mtg02_Interest_Only_Period] VARCHAR(8000),
	[Mtg02_fixed_step_conversion_rate_rider] VARCHAR(8000),
	[Mtg02_First_Change_Date_Year_Conversion_Rider] VARCHAR(8000),
	[Mtg02_First_Change_Date_Month_Day_Conversion_Rider] VARCHAR(8000),
	[Mtg02_Prepayment_Rider] VARCHAR(8000),
	[Mtg02_Prepayment_Term_Penalty_Rider] VARCHAR(8000),
	[Mtg02_Title_Company_Name] VARCHAR(8000),
	[Mtg02_Lender_Name] VARCHAR(8000),
	[Mtg02_Lender_Mail_Full_Street_Address] VARCHAR(8000),
	[Mtg02_Lender_Mail_Unit] VARCHAR(8000),
	[Mtg02_Lender_Mail_City] VARCHAR(8000),
	[Mtg02_Lender_Mail_State] VARCHAR(8000),
	[Mtg02_Lender_Mail_Zip_Code] VARCHAR(8000),
	[Mtg02_Lender_Mail_Zip_Plus4Code] VARCHAR(8000),
	[Mtg02_Loan_Term_Months] VARCHAR(8000),
	[Mtg02_Loan_Term_Years] VARCHAR(8000),
	[Mtg02_loan_number] VARCHAR(8000),
	[Mtg02_Construction_Loan] VARCHAR(8000),
	[Mtg02_Cash_Purchase] VARCHAR(8000),
	[Mtg02_StandAlone_Refi] VARCHAR(8000),
	[Mtg02_Equity_Credit_Line] VARCHAR(8000),
	[Mtg02_Curr_Est_Bal] VARCHAR(8000),
	[Mtg02_Purpose_Of_Loan] VARCHAR(8000),
	[Mtg02_Purchase_Mtg_Ind] VARCHAR(8000),
	[Mtg02_Est_Monthly_P&I] VARCHAR(8000),
	[Mtg02_Est_Monthly_Principal] VARCHAR(8000),
	[Mtg02_Est_Monthly_Interest] VARCHAR(8000),
	[Mtg02_Curr_Est_Int_Rate] VARCHAR(8000),
	[Mtg02_Assigned_Lender_Name] VARCHAR(8000),
	[Mtg02_Assignment_Date] VARCHAR(8000),
	[Mtg02_Number_of_Assignments] VARCHAR(8000),
	[Mtg02_PreForeclosure_Status] VARCHAR(8000),
	[Mtg02_PreFcl_Recording_Date] VARCHAR(8000),
	[Mtg02_PreFcl_Filing_Date] VARCHAR(8000),
	[Mtg02_PreFcl_Case_Trustee_Sale_Nbr] VARCHAR(8000),
	[Mtg02_PreFcl_Auction_Date] VARCHAR(8000),
	[Mtg03_lender_name_beneficiary] VARCHAR(8000),
	[Mtg03_lender_type] VARCHAR(8000),
	[Mtg03_original_date_of_contract] VARCHAR(8000),
	[Mtg03_recording_date] VARCHAR(8000),
	[Mtg03_Loan_Amount] VARCHAR(8000),
	[Mtg03_loan_type] VARCHAR(8000),
	[Mtg03_type_financing] VARCHAR(8000),
	[Mtg03_interest_rate] VARCHAR(8000),
	[Mtg03_due_date] VARCHAR(8000),
	[Mtg03_Adjustable_Rate_Rider] VARCHAR(8000),
	[Mtg03_Adjustable_Rate_Index] VARCHAR(8000),
	[Mtg03_Change_Index] VARCHAR(8000),
	[Mtg03_Rate_Change_Frequency] VARCHAR(8000),
	[Mtg03_Interest_Rate_Not_Greater_Than] VARCHAR(8000),
	[Mtg03_Interest_Rate_Not_Less_Than] VARCHAR(8000),
	[Mtg03_Maximum_Interest_Rate] VARCHAR(8000),
	[Mtg03_Interest_Only_Period] VARCHAR(8000),
	[Mtg03_fixed_step_conversion_rate_rider] VARCHAR(8000),
	[Mtg03_First_Change_Date_Year_Conversion_Rider] VARCHAR(8000),
	[Mtg03_First_Change_Date_Month_Day_Conversion_Rider] VARCHAR(8000),
	[Mtg03_Prepayment_Rider] VARCHAR(8000),
	[Mtg03_Prepayment_Term_Penalty_Rider] VARCHAR(8000),
	[Mtg03_Title_Company_Name] VARCHAR(8000),
	[Mtg03_Lender_Name] VARCHAR(8000),
	[Mtg03_Lender_Mail_Full_Street_Address] VARCHAR(8000),
	[Mtg03_Lender_Mail_Unit] VARCHAR(8000),
	[Mtg03_Lender_Mail_City] VARCHAR(8000),
	[Mtg03_Lender_Mail_State] VARCHAR(8000),
	[Mtg03_Lender_Mail_Zip_Code] VARCHAR(8000),
	[Mtg03_Lender_Mail_Zip_Plus4Code] VARCHAR(8000),
	[Mtg03_Loan_Term_Months] VARCHAR(8000),
	[Mtg03_Loan_Term_Years] VARCHAR(8000),
	[Mtg03_loan_number] VARCHAR(8000),
	[Mtg03_Construction_Loan] VARCHAR(8000),
	[Mtg03_Cash_Purchase] VARCHAR(8000),
	[Mtg03_StandAlone_Refi] VARCHAR(8000),
	[Mtg03_Equity_Credit_Line] VARCHAR(8000),
	[Mtg03_Curr_Est_Bal] VARCHAR(8000),
	[Mtg03_Purpose_Of_Loan] VARCHAR(8000),
	[Mtg03_Purchase_Mtg_Ind] VARCHAR(8000),
	[Mtg03_Est_Monthly_P&I] VARCHAR(8000),
	[Mtg03_Est_Monthly_Principal] VARCHAR(8000),
	[Mtg03_Est_Monthly_Interest] VARCHAR(8000),
	[Mtg03_Curr_Est_Int_Rate] VARCHAR(8000),
	[Mtg03_Assigned_Lender_Name] VARCHAR(8000),
	[Mtg03_Assignment_Date] VARCHAR(8000),
	[Mtg03_Number_of_Assignments] VARCHAR(8000),
	[Mtg03_PreForeclosure_Status] VARCHAR(8000),
	[Mtg03_PreFcl_Recording_Date] VARCHAR(8000),
	[Mtg03_PreFcl_Filing_Date] VARCHAR(8000),
	[Mtg03_PreFcl_Case_Trustee_Sale_Nbr] VARCHAR(8000),
	[Mtg03_PreFcl_Auction_Date] VARCHAR(8000),
	[Mtg04_lender_name_beneficiary] VARCHAR(8000),
	[Mtg04_lender_type] VARCHAR(8000),
	[Mtg04_original_date_of_contract] VARCHAR(8000),
	[Mtg04_recording_date] VARCHAR(8000),
	[Mtg04_Loan_Amount] VARCHAR(8000),
	[Mtg04_loan_type] VARCHAR(8000),
	[Mtg04_type_financing] VARCHAR(8000),
	[Mtg04_interest_rate] VARCHAR(8000),
	[Mtg04_due_date] VARCHAR(8000),
	[Mtg04_Adjustable_Rate_Rider] VARCHAR(8000),
	[Mtg04_Adjustable_Rate_Index] VARCHAR(8000),
	[Mtg04_Change_Index] VARCHAR(8000),
	[Mtg04_Rate_Change_Frequency] VARCHAR(8000),
	[Mtg04_Interest_Rate_Not_Greater_Than] VARCHAR(8000),
	[Mtg04_Interest_Rate_Not_Less_Than] VARCHAR(8000),
	[Mtg04_Maximum_Interest_Rate] VARCHAR(8000),
	[Mtg04_Interest_Only_Period] VARCHAR(8000),
	[Mtg04_fixed_step_conversion_rate_rider] VARCHAR(8000),
	[Mtg04_First_Change_Date_Year_Conversion_Rider] VARCHAR(8000),
	[Mtg04_First_Change_Date_Month_Day_Conversion_Rider] VARCHAR(8000),
	[Mtg04_Prepayment_Rider] VARCHAR(8000),
	[Mtg04_Prepayment_Term_Penalty_Rider] VARCHAR(8000),
	[Mtg04_Title_Company_Name] VARCHAR(8000),
	[Mtg04_Lender_Name] VARCHAR(8000),
	[Mtg04_Lender_Mail_Full_Street_Address] VARCHAR(8000),
	[Mtg04_Lender_Mail_Unit] VARCHAR(8000),
	[Mtg04_Lender_Mail_City] VARCHAR(8000),
	[Mtg04_Lender_Mail_State] VARCHAR(8000),
	[Mtg04_Lender_Mail_Zip_Code] VARCHAR(8000),
	[Mtg04_Lender_Mail_Zip_Plus4Code] VARCHAR(8000),
	[Mtg04_Loan_Term_Months] VARCHAR(8000),
	[Mtg04_Loan_Term_Years] VARCHAR(8000),
	[Mtg04_loan_number] VARCHAR(8000),
	[Mtg04_Construction_Loan] VARCHAR(8000),
	[Mtg04_Cash_Purchase] VARCHAR(8000),
	[Mtg04_StandAlone_Refi] VARCHAR(8000),
	[Mtg04_Equity_Credit_Line] VARCHAR(8000),
	[Mtg04_Curr_Est_Bal] VARCHAR(8000),
	[Mtg04_Purpose_Of_Loan] VARCHAR(8000),
	[Mtg04_Purchase_Mtg_Ind] VARCHAR(8000),
	[Mtg04_Est_Monthly_P&I] VARCHAR(8000),
	[Mtg04_Est_Monthly_Principal] VARCHAR(8000),
	[Mtg04_Est_Monthly_Interest] VARCHAR(8000),
	[Mtg04_Curr_Est_Int_Rate] VARCHAR(8000),
	[Mtg04_Assigned_Lender_Name] VARCHAR(8000),
	[Mtg04_Assignment_Date] VARCHAR(8000),
	[Mtg04_Number_of_Assignments] VARCHAR(8000),
	[Mtg04_PreForeclosure_Status] VARCHAR(8000),
	[Mtg04_PreFcl_Recording_Date] VARCHAR(8000),
	[Mtg04_PreFcl_Filing_Date] VARCHAR(8000),
	[Mtg04_PreFcl_Case_Trustee_Sale_Nbr] VARCHAR(8000),
	[Mtg04_PreFcl_Auction_Date] VARCHAR(8000),
	[Additional_Open_Lien_Count] VARCHAR(8000),
	[Additional_Open_Lien_Balance] VARCHAR(8000),
	[Total_Open_Lien_Count] VARCHAR(8000),
	[Total_Open_Lien_Balance] VARCHAR(8000),
	[Total_Financing_History_Count] VARCHAR(8000),
	[Current_Est_LTV_Combined] VARCHAR(8000),
	[Current_Est_LTV_Range_Code] VARCHAR(8000),
	[Current_Est_Equity_Dollars] VARCHAR(8000),
	[Current_Est_Equity_Range_Code] VARCHAR(8000),
	[Purchase_LTV] VARCHAR(8000),
	[Current_Foreclosure_Status] VARCHAR(8000),
	[Foreclosure_Recording_Date] VARCHAR(8000),
	[Foreclosure_filing_date] VARCHAR(8000),
	[Foreclosure_Case_Number] VARCHAR(8000),
	[Foreclosure_Auction_Date] VARCHAR(8000),
	[ESTIMATED_VALUE] VARCHAR(8000),
	[PRICE_RANGE_MIN] VARCHAR(8000),
	[PRICE_RANGE_MAX] VARCHAR(8000),
	[FSD_SCORE] VARCHAR(8000),
	[CONFIDENCE_SCORE] VARCHAR(8000),
	[QVM_Value_Range_Code] VARCHAR(8000),
	[QVM_asof_Date] VARCHAR(8000),
	[Trans_asof_Date] VARCHAR(8000),
	[Record_Creation_Date] VARCHAR(8000),
	[Quantarium_Version] VARCHAR(8000)
)



SELECT
	CASE WHEN TRIM([Quantarium_Internal_PID]) IN ('','NULL') THEN NULL ELSE TRIM([Quantarium_Internal_PID]) END AS [Quantarium_Internal_PID],
	CASE WHEN TRIM([FIPS_Code]) IN ('','NULL') THEN NULL ELSE TRIM([FIPS_Code]) END AS [FIPS_Code],
	CASE WHEN TRIM([Assessors_Parcel_Number]) IN ('','NULL') THEN NULL ELSE TRIM([Assessors_Parcel_Number]) END AS [Assessors_Parcel_Number],
	CASE WHEN TRIM([Duplicate_APN]) IN ('','NULL') THEN NULL ELSE TRIM([Duplicate_APN]) END AS [Duplicate_APN],
	CASE WHEN TRIM([Tax_Account_Number]) IN ('','NULL') THEN NULL ELSE TRIM([Tax_Account_Number]) END AS [Tax_Account_Number],
	CASE WHEN TRIM([Current_Owner_Name]) IN ('','NULL') THEN NULL ELSE TRIM([Current_Owner_Name]) END AS [Current_Owner_Name],
	CASE WHEN TRIM([CO_Mail_Care_of_Name]) IN ('','NULL') THEN NULL ELSE TRIM([CO_Mail_Care_of_Name]) END AS [CO_Mail_Care_of_Name],
	CASE WHEN TRIM([CO_Mail_Street_Address]) IN ('','NULL') THEN NULL ELSE TRIM([CO_Mail_Street_Address]) END AS [CO_Mail_Street_Address],
	CASE WHEN TRIM([CO_Mailing_City]) IN ('','NULL') THEN NULL ELSE TRIM([CO_Mailing_City]) END AS [CO_Mailing_City],
	CASE WHEN TRIM([CO_Mailing_State]) IN ('','NULL') THEN NULL ELSE TRIM([CO_Mailing_State]) END AS [CO_Mailing_State],
	CASE WHEN TRIM([CO_Mailing_Zip_Code]) IN ('','NULL') THEN NULL ELSE TRIM([CO_Mailing_Zip_Code]) END AS [CO_Mailing_Zip_Code],
	CASE WHEN TRIM([CO_Mailing_Zip_Plus4Code]) IN ('','NULL') THEN NULL ELSE TRIM([CO_Mailing_Zip_Plus4Code]) END AS [CO_Mailing_Zip_Plus4Code],
	CASE WHEN TRIM([CO_Unit_Number]) IN ('','NULL') THEN NULL ELSE TRIM([CO_Unit_Number]) END AS [CO_Unit_Number],
	CASE WHEN TRIM([CO_Unit_Type]) IN ('','NULL') THEN NULL ELSE TRIM([CO_Unit_Type]) END AS [CO_Unit_Type],
	CASE WHEN TRIM([Mail_Care_Of_Name_Indicator]) IN ('','NULL') THEN NULL ELSE TRIM([Mail_Care_Of_Name_Indicator]) END AS [Mail_Care_Of_Name_Indicator],
	CASE WHEN TRIM([Owner_Occupied]) IN ('','NULL') THEN NULL ELSE TRIM([Owner_Occupied]) END AS [Owner_Occupied],
	CASE WHEN TRIM([Owner1FirstName]) IN ('','NULL') THEN NULL ELSE TRIM([Owner1FirstName]) END AS [Owner1FirstName],
	CASE WHEN TRIM([Owner1MiddleName]) IN ('','NULL') THEN NULL ELSE TRIM([Owner1MiddleName]) END AS [Owner1MiddleName],
	CASE WHEN TRIM([Owner1LastName]) IN ('','NULL') THEN NULL ELSE TRIM([Owner1LastName]) END AS [Owner1LastName],
	CASE WHEN TRIM([Owner2Firstname]) IN ('','NULL') THEN NULL ELSE TRIM([Owner2Firstname]) END AS [Owner2Firstname],
	CASE WHEN TRIM([Owner2MiddleName]) IN ('','NULL') THEN NULL ELSE TRIM([Owner2MiddleName]) END AS [Owner2MiddleName],
	CASE WHEN TRIM([Owner2LastName]) IN ('','NULL') THEN NULL ELSE TRIM([Owner2LastName]) END AS [Owner2LastName],
	CASE WHEN TRIM([ParsedOwnerSourceCode]) IN ('','NULL') THEN NULL ELSE TRIM([ParsedOwnerSourceCode]) END AS [ParsedOwnerSourceCode],
	CASE WHEN TRIM([Buyer_ID_Code_1]) IN ('','NULL') THEN NULL ELSE TRIM([Buyer_ID_Code_1]) END AS [Buyer_ID_Code_1],
	CASE WHEN TRIM([Buyer_Vesting_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Buyer_Vesting_Code]) END AS [Buyer_Vesting_Code],
	CASE WHEN TRIM([Length_of_Residence_Months]) IN ('','NULL') THEN NULL ELSE TRIM([Length_of_Residence_Months]) END AS [Length_of_Residence_Months],
	CASE WHEN TRIM([Length_of_Residence_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Length_of_Residence_Code]) END AS [Length_of_Residence_Code],
	CASE WHEN TRIM([Ownership_Start_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Ownership_Start_Date]) END AS [Ownership_Start_Date],
	CASE WHEN TRIM([LSale_Book_Number]) IN ('','NULL') THEN NULL ELSE TRIM([LSale_Book_Number]) END AS [LSale_Book_Number],
	CASE WHEN TRIM([LSale_Page_Number]) IN ('','NULL') THEN NULL ELSE TRIM([LSale_Page_Number]) END AS [LSale_Page_Number],
	CASE WHEN TRIM([LSale_Document_Number]) IN ('','NULL') THEN NULL ELSE TRIM([LSale_Document_Number]) END AS [LSale_Document_Number],
	CASE WHEN TRIM([LSale_Document_Type_Code]) IN ('','NULL') THEN NULL ELSE TRIM([LSale_Document_Type_Code]) END AS [LSale_Document_Type_Code],
	CASE WHEN TRIM([LSale_Price]) IN ('','NULL') THEN NULL ELSE TRIM([LSale_Price]) END AS [LSale_Price],
	CASE WHEN TRIM([LSale_Price_Code]) IN ('','NULL') THEN NULL ELSE TRIM([LSale_Price_Code]) END AS [LSale_Price_Code],
	CASE WHEN TRIM([LSale_Recording_Date]) IN ('','NULL') THEN NULL ELSE TRIM([LSale_Recording_Date]) END AS [LSale_Recording_Date],
	CASE WHEN TRIM([LSale_reo_flag]) IN ('','NULL') THEN NULL ELSE TRIM([LSale_reo_flag]) END AS [LSale_reo_flag],
	CASE WHEN TRIM([LSale_distressed_sale_flag]) IN ('','NULL') THEN NULL ELSE TRIM([LSale_distressed_sale_flag]) END AS [LSale_distressed_sale_flag],
	CASE WHEN TRIM([Last_Transfer_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Last_Transfer_Date]) END AS [Last_Transfer_Date],
	CASE WHEN TRIM([LValid_Book_Number]) IN ('','NULL') THEN NULL ELSE TRIM([LValid_Book_Number]) END AS [LValid_Book_Number],
	CASE WHEN TRIM([LValid_Page_Number]) IN ('','NULL') THEN NULL ELSE TRIM([LValid_Page_Number]) END AS [LValid_Page_Number],
	CASE WHEN TRIM([LValid_Document_Number]) IN ('','NULL') THEN NULL ELSE TRIM([LValid_Document_Number]) END AS [LValid_Document_Number],
	CASE WHEN TRIM([LValid_Document_Type_Code]) IN ('','NULL') THEN NULL ELSE TRIM([LValid_Document_Type_Code]) END AS [LValid_Document_Type_Code],
	CASE WHEN TRIM([LValid_Price]) IN ('','NULL') THEN NULL ELSE TRIM([LValid_Price]) END AS [LValid_Price],
	CASE WHEN TRIM([LValid_Price_Code]) IN ('','NULL') THEN NULL ELSE TRIM([LValid_Price_Code]) END AS [LValid_Price_Code],
	CASE WHEN TRIM([LValid_Recording_Date]) IN ('','NULL') THEN NULL ELSE TRIM([LValid_Recording_Date]) END AS [LValid_Recording_Date],
	CASE WHEN TRIM([LValid_reo_flag]) IN ('','NULL') THEN NULL ELSE TRIM([LValid_reo_flag]) END AS [LValid_reo_flag],
	CASE WHEN TRIM([LValid_distressed_sale_flag]) IN ('','NULL') THEN NULL ELSE TRIM([LValid_distressed_sale_flag]) END AS [LValid_distressed_sale_flag],
	CASE WHEN TRIM([Last_Sale_date]) IN ('','NULL') THEN NULL ELSE TRIM([Last_Sale_date]) END AS [Last_Sale_date],
	CASE WHEN TRIM([PSale_Book_Number]) IN ('','NULL') THEN NULL ELSE TRIM([PSale_Book_Number]) END AS [PSale_Book_Number],
	CASE WHEN TRIM([PSale_Page_Number]) IN ('','NULL') THEN NULL ELSE TRIM([PSale_Page_Number]) END AS [PSale_Page_Number],
	CASE WHEN TRIM([PSale_Document_Number]) IN ('','NULL') THEN NULL ELSE TRIM([PSale_Document_Number]) END AS [PSale_Document_Number],
	CASE WHEN TRIM([PSale_Document_Type_Code]) IN ('','NULL') THEN NULL ELSE TRIM([PSale_Document_Type_Code]) END AS [PSale_Document_Type_Code],
	CASE WHEN TRIM([PSale_Price]) IN ('','NULL') THEN NULL ELSE TRIM([PSale_Price]) END AS [PSale_Price],
	CASE WHEN TRIM([PSale_Price_Code]) IN ('','NULL') THEN NULL ELSE TRIM([PSale_Price_Code]) END AS [PSale_Price_Code],
	CASE WHEN TRIM([PSale_Recording_Date]) IN ('','NULL') THEN NULL ELSE TRIM([PSale_Recording_Date]) END AS [PSale_Recording_Date],
	CASE WHEN TRIM([PSale_reo_flag]) IN ('','NULL') THEN NULL ELSE TRIM([PSale_reo_flag]) END AS [PSale_reo_flag],
	CASE WHEN TRIM([PSale_distressed_sale_flag]) IN ('','NULL') THEN NULL ELSE TRIM([PSale_distressed_sale_flag]) END AS [PSale_distressed_sale_flag],
	CASE WHEN TRIM([Prior_Transfer_date]) IN ('','NULL') THEN NULL ELSE TRIM([Prior_Transfer_date]) END AS [Prior_Transfer_date],
	CASE WHEN TRIM([PValid_Book_Number]) IN ('','NULL') THEN NULL ELSE TRIM([PValid_Book_Number]) END AS [PValid_Book_Number],
	CASE WHEN TRIM([PValid_Page_Number]) IN ('','NULL') THEN NULL ELSE TRIM([PValid_Page_Number]) END AS [PValid_Page_Number],
	CASE WHEN TRIM([PValid_Document_Number]) IN ('','NULL') THEN NULL ELSE TRIM([PValid_Document_Number]) END AS [PValid_Document_Number],
	CASE WHEN TRIM([PValid_Document_Type_Code]) IN ('','NULL') THEN NULL ELSE TRIM([PValid_Document_Type_Code]) END AS [PValid_Document_Type_Code],
	CASE WHEN TRIM([PValid_Price]) IN ('','NULL') THEN NULL ELSE TRIM([PValid_Price]) END AS [PValid_Price],
	CASE WHEN TRIM([PValid_Price_Code]) IN ('','NULL') THEN NULL ELSE TRIM([PValid_Price_Code]) END AS [PValid_Price_Code],
	CASE WHEN TRIM([PValid_Recording_Date]) IN ('','NULL') THEN NULL ELSE TRIM([PValid_Recording_Date]) END AS [PValid_Recording_Date],
	CASE WHEN TRIM([PValid_reo_flag]) IN ('','NULL') THEN NULL ELSE TRIM([PValid_reo_flag]) END AS [PValid_reo_flag],
	CASE WHEN TRIM([PValid_distressed_sale_flag]) IN ('','NULL') THEN NULL ELSE TRIM([PValid_distressed_sale_flag]) END AS [PValid_distressed_sale_flag],
	CASE WHEN TRIM([Prior_Sale_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Prior_Sale_Date]) END AS [Prior_Sale_Date],
	CASE WHEN TRIM([Recorders_Document_Number_from_Assessment]) IN ('','NULL') THEN NULL ELSE TRIM([Recorders_Document_Number_from_Assessment]) END AS [Recorders_Document_Number_from_Assessment],
	CASE WHEN TRIM([Recorders_Book_Number_from_Assessment]) IN ('','NULL') THEN NULL ELSE TRIM([Recorders_Book_Number_from_Assessment]) END AS [Recorders_Book_Number_from_Assessment],
	CASE WHEN TRIM([Recorders_Page_Number_from_Assessment]) IN ('','NULL') THEN NULL ELSE TRIM([Recorders_Page_Number_from_Assessment]) END AS [Recorders_Page_Number_from_Assessment],
	CASE WHEN TRIM([Recording_Date_from_Assessment]) IN ('','NULL') THEN NULL ELSE TRIM([Recording_Date_from_Assessment]) END AS [Recording_Date_from_Assessment],
	CASE WHEN TRIM([Document_Type_from_Assessment]) IN ('','NULL') THEN NULL ELSE TRIM([Document_Type_from_Assessment]) END AS [Document_Type_from_Assessment],
	CASE WHEN TRIM([Sales_Price_from_Assessment]) IN ('','NULL') THEN NULL ELSE TRIM([Sales_Price_from_Assessment]) END AS [Sales_Price_from_Assessment],
	CASE WHEN TRIM([Sales_Price_Code_from_Assessment]) IN ('','NULL') THEN NULL ELSE TRIM([Sales_Price_Code_from_Assessment]) END AS [Sales_Price_Code_from_Assessment],
	CASE WHEN TRIM([Property_Full_Street_Address]) IN ('','NULL') THEN NULL ELSE TRIM([Property_Full_Street_Address]) END AS [Property_Full_Street_Address],
	CASE WHEN TRIM([Property_City_Name]) IN ('','NULL') THEN NULL ELSE TRIM([Property_City_Name]) END AS [Property_City_Name],
	CASE WHEN TRIM([Property_State]) IN ('','NULL') THEN NULL ELSE TRIM([Property_State]) END AS [Property_State],
	CASE WHEN TRIM([Property_Zip_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Property_Zip_Code]) END AS [Property_Zip_Code],
	CASE WHEN TRIM([Property_Zip_Plus4Code]) IN ('','NULL') THEN NULL ELSE TRIM([Property_Zip_Plus4Code]) END AS [Property_Zip_Plus4Code],
	CASE WHEN TRIM([Property_House_Number]) IN ('','NULL') THEN NULL ELSE TRIM([Property_House_Number]) END AS [Property_House_Number],
	CASE WHEN TRIM([Property_Street_Direction_Left]) IN ('','NULL') THEN NULL ELSE TRIM([Property_Street_Direction_Left]) END AS [Property_Street_Direction_Left],
	CASE WHEN TRIM([Property_Street_Name]) IN ('','NULL') THEN NULL ELSE TRIM([Property_Street_Name]) END AS [Property_Street_Name],
	CASE WHEN TRIM([Property_Street_Suffix]) IN ('','NULL') THEN NULL ELSE TRIM([Property_Street_Suffix]) END AS [Property_Street_Suffix],
	CASE WHEN TRIM([Property_Street_Direction_Right]) IN ('','NULL') THEN NULL ELSE TRIM([Property_Street_Direction_Right]) END AS [Property_Street_Direction_Right],
	CASE WHEN TRIM([Property_Unit_Number]) IN ('','NULL') THEN NULL ELSE TRIM([Property_Unit_Number]) END AS [Property_Unit_Number],
	CASE WHEN TRIM([Property_Unit_Type]) IN ('','NULL') THEN NULL ELSE TRIM([Property_Unit_Type]) END AS [Property_Unit_Type],
	CASE WHEN TRIM([PA_Carrier_Route]) IN ('','NULL') THEN NULL ELSE TRIM([PA_Carrier_Route]) END AS [PA_Carrier_Route],
	CASE WHEN TRIM([PA_Census_Tract]) IN ('','NULL') THEN NULL ELSE TRIM([PA_Census_Tract]) END AS [PA_Census_Tract],
	CASE WHEN TRIM([PA_Latitude]) IN ('','NULL') THEN NULL ELSE TRIM([PA_Latitude]) END AS [PA_Latitude],
	CASE WHEN TRIM([PA_Longitude]) IN ('','NULL') THEN NULL ELSE TRIM([PA_Longitude]) END AS [PA_Longitude],
	CASE WHEN TRIM([Match_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Match_Code]) END AS [Match_Code],
	CASE WHEN TRIM([Location_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Location_Code]) END AS [Location_Code],
	CASE WHEN TRIM([Legal_Assessors_Map_Ref]) IN ('','NULL') THEN NULL ELSE TRIM([Legal_Assessors_Map_Ref]) END AS [Legal_Assessors_Map_Ref],
	CASE WHEN TRIM([Legal_Brief_Description]) IN ('','NULL') THEN NULL ELSE TRIM([Legal_Brief_Description]) END AS [Legal_Brief_Description],
	CASE WHEN TRIM([Legal_Brief_Description_FULL]) IN ('','NULL') THEN NULL ELSE TRIM([Legal_Brief_Description_FULL]) END AS [Legal_Brief_Description_FULL],
	CASE WHEN TRIM([Legal_Section_Township__Range_Meridian]) IN ('','NULL') THEN NULL ELSE TRIM([Legal_Section_Township__Range_Meridian]) END AS [Legal_Section_Township__Range_Meridian],
	CASE WHEN TRIM([Legal_Block]) IN ('','NULL') THEN NULL ELSE TRIM([Legal_Block]) END AS [Legal_Block],
	CASE WHEN TRIM([Legal_Lot_Number]) IN ('','NULL') THEN NULL ELSE TRIM([Legal_Lot_Number]) END AS [Legal_Lot_Number],
	CASE WHEN TRIM([Legal_City_Township_Municipality]) IN ('','NULL') THEN NULL ELSE TRIM([Legal_City_Township_Municipality]) END AS [Legal_City_Township_Municipality],
	CASE WHEN TRIM([Legal_District]) IN ('','NULL') THEN NULL ELSE TRIM([Legal_District]) END AS [Legal_District],
	CASE WHEN TRIM([Legal_Section]) IN ('','NULL') THEN NULL ELSE TRIM([Legal_Section]) END AS [Legal_Section],
	CASE WHEN TRIM([Legal_Land_Lot]) IN ('','NULL') THEN NULL ELSE TRIM([Legal_Land_Lot]) END AS [Legal_Land_Lot],
	CASE WHEN TRIM([Legal_Lot_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Legal_Lot_Code]) END AS [Legal_Lot_Code],
	CASE WHEN TRIM([Legal_Phase_Number]) IN ('','NULL') THEN NULL ELSE TRIM([Legal_Phase_Number]) END AS [Legal_Phase_Number],
	CASE WHEN TRIM([Legal_Subdivision_Name]) IN ('','NULL') THEN NULL ELSE TRIM([Legal_Subdivision_Name]) END AS [Legal_Subdivision_Name],
	CASE WHEN TRIM([Legal_Tract_Number]) IN ('','NULL') THEN NULL ELSE TRIM([Legal_Tract_Number]) END AS [Legal_Tract_Number],
	CASE WHEN TRIM([Legal_Unit]) IN ('','NULL') THEN NULL ELSE TRIM([Legal_Unit]) END AS [Legal_Unit],
	CASE WHEN TRIM([Assessed_Improvement_Value]) IN ('','NULL') THEN NULL ELSE TRIM([Assessed_Improvement_Value]) END AS [Assessed_Improvement_Value],
	CASE WHEN TRIM([Assessed_Land_Value]) IN ('','NULL') THEN NULL ELSE TRIM([Assessed_Land_Value]) END AS [Assessed_Land_Value],
	CASE WHEN TRIM([Total_Assessed_Value]) IN ('','NULL') THEN NULL ELSE TRIM([Total_Assessed_Value]) END AS [Total_Assessed_Value],
	CASE WHEN TRIM([Assessment_Year]) IN ('','NULL') THEN NULL ELSE TRIM([Assessment_Year]) END AS [Assessment_Year],
	CASE WHEN TRIM([California_HomeOwners_Exemption]) IN ('','NULL') THEN NULL ELSE TRIM([California_HomeOwners_Exemption]) END AS [California_HomeOwners_Exemption],
	CASE WHEN TRIM([Tax_Exemption_Codes]) IN ('','NULL') THEN NULL ELSE TRIM([Tax_Exemption_Codes]) END AS [Tax_Exemption_Codes],
	CASE WHEN TRIM([Market_Value_Improvement]) IN ('','NULL') THEN NULL ELSE TRIM([Market_Value_Improvement]) END AS [Market_Value_Improvement],
	CASE WHEN TRIM([Market_Value_Land]) IN ('','NULL') THEN NULL ELSE TRIM([Market_Value_Land]) END AS [Market_Value_Land],
	CASE WHEN TRIM([Total_Market_Value]) IN ('','NULL') THEN NULL ELSE TRIM([Total_Market_Value]) END AS [Total_Market_Value],
	CASE WHEN TRIM([Market_Value_Year]) IN ('','NULL') THEN NULL ELSE TRIM([Market_Value_Year]) END AS [Market_Value_Year],
	CASE WHEN TRIM([School_Tax_District_1]) IN ('','NULL') THEN NULL ELSE TRIM([School_Tax_District_1]) END AS [School_Tax_District_1],
	CASE WHEN TRIM([School_Tax_District_1_Indicator]) IN ('','NULL') THEN NULL ELSE TRIM([School_Tax_District_1_Indicator]) END AS [School_Tax_District_1_Indicator],
	CASE WHEN TRIM([School_Tax_District_2]) IN ('','NULL') THEN NULL ELSE TRIM([School_Tax_District_2]) END AS [School_Tax_District_2],
	CASE WHEN TRIM([School_Tax_District_2_Indicator]) IN ('','NULL') THEN NULL ELSE TRIM([School_Tax_District_2_Indicator]) END AS [School_Tax_District_2_Indicator],
	CASE WHEN TRIM([School_Tax_District_3]) IN ('','NULL') THEN NULL ELSE TRIM([School_Tax_District_3]) END AS [School_Tax_District_3],
	CASE WHEN TRIM([School_Tax_District_3_Indicator]) IN ('','NULL') THEN NULL ELSE TRIM([School_Tax_District_3_Indicator]) END AS [School_Tax_District_3_Indicator],
	CASE WHEN TRIM([Tax_Amount]) IN ('','NULL') THEN NULL ELSE TRIM([Tax_Amount]) END AS [Tax_Amount],
	CASE WHEN TRIM([Tax_Year]) IN ('','NULL') THEN NULL ELSE TRIM([Tax_Year]) END AS [Tax_Year],
	CASE WHEN TRIM([Tax_Delinquent_Year]) IN ('','NULL') THEN NULL ELSE TRIM([Tax_Delinquent_Year]) END AS [Tax_Delinquent_Year],
	CASE WHEN TRIM([Tax_Rate_Code_Area]) IN ('','NULL') THEN NULL ELSE TRIM([Tax_Rate_Code_Area]) END AS [Tax_Rate_Code_Area],
	CASE WHEN TRIM([Neighborhood_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Neighborhood_Code]) END AS [Neighborhood_Code],
	CASE WHEN TRIM([Condo_Project_Bldg_Name]) IN ('','NULL') THEN NULL ELSE TRIM([Condo_Project_Bldg_Name]) END AS [Condo_Project_Bldg_Name],
	CASE WHEN TRIM([Old_APN]) IN ('','NULL') THEN NULL ELSE TRIM([Old_APN]) END AS [Old_APN],
	CASE WHEN TRIM([Alt_Old_APN_Indicator]) IN ('','NULL') THEN NULL ELSE TRIM([Alt_Old_APN_Indicator]) END AS [Alt_Old_APN_Indicator],
	CASE WHEN TRIM([Certification_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Certification_Date]) END AS [Certification_Date],
	CASE WHEN TRIM([Edition]) IN ('','NULL') THEN NULL ELSE TRIM([Edition]) END AS [Edition],
	CASE WHEN TRIM([LotSize_Acres]) IN ('','NULL') THEN NULL ELSE TRIM([LotSize_Acres]) END AS [LotSize_Acres],
	CASE WHEN TRIM([LotSize_Depth_Feet]) IN ('','NULL') THEN NULL ELSE TRIM([LotSize_Depth_Feet]) END AS [LotSize_Depth_Feet],
	CASE WHEN TRIM([LotSize_Frontage_Feet]) IN ('','NULL') THEN NULL ELSE TRIM([LotSize_Frontage_Feet]) END AS [LotSize_Frontage_Feet],
	CASE WHEN TRIM([LotSize_Square_Feet]) IN ('','NULL') THEN NULL ELSE TRIM([LotSize_Square_Feet]) END AS [LotSize_Square_Feet],
	CASE WHEN TRIM([Lot_Size_or_Area]) IN ('','NULL') THEN NULL ELSE TRIM([Lot_Size_or_Area]) END AS [Lot_Size_or_Area],
	CASE WHEN TRIM([Lot_Size_Area_Unit]) IN ('','NULL') THEN NULL ELSE TRIM([Lot_Size_Area_Unit]) END AS [Lot_Size_Area_Unit],
	CASE WHEN TRIM([Original_Lot_Size_or_Area]) IN ('','NULL') THEN NULL ELSE TRIM([Original_Lot_Size_or_Area]) END AS [Original_Lot_Size_or_Area],
	CASE WHEN TRIM([Topography]) IN ('','NULL') THEN NULL ELSE TRIM([Topography]) END AS [Topography],
	CASE WHEN TRIM([Site_Influence]) IN ('','NULL') THEN NULL ELSE TRIM([Site_Influence]) END AS [Site_Influence],
	CASE WHEN TRIM([Air_Conditioning]) IN ('','NULL') THEN NULL ELSE TRIM([Air_Conditioning]) END AS [Air_Conditioning],
	CASE WHEN TRIM([Air_Conditioning_Type]) IN ('','NULL') THEN NULL ELSE TRIM([Air_Conditioning_Type]) END AS [Air_Conditioning_Type],
	CASE WHEN TRIM([Amenities]) IN ('','NULL') THEN NULL ELSE TRIM([Amenities]) END AS [Amenities],
	CASE WHEN TRIM([Amenities_2]) IN ('','NULL') THEN NULL ELSE TRIM([Amenities_2]) END AS [Amenities_2],
	CASE WHEN TRIM([Basement]) IN ('','NULL') THEN NULL ELSE TRIM([Basement]) END AS [Basement],
	CASE WHEN TRIM([Building_Area]) IN ('','NULL') THEN NULL ELSE TRIM([Building_Area]) END AS [Building_Area],
	CASE WHEN TRIM([Building_Area_1]) IN ('','NULL') THEN NULL ELSE TRIM([Building_Area_1]) END AS [Building_Area_1],
	CASE WHEN TRIM([Building_Area_1_Indicator]) IN ('','NULL') THEN NULL ELSE TRIM([Building_Area_1_Indicator]) END AS [Building_Area_1_Indicator],
	CASE WHEN TRIM([Building_Area_2]) IN ('','NULL') THEN NULL ELSE TRIM([Building_Area_2]) END AS [Building_Area_2],
	CASE WHEN TRIM([Building_Area_2_Indicator]) IN ('','NULL') THEN NULL ELSE TRIM([Building_Area_2_Indicator]) END AS [Building_Area_2_Indicator],
	CASE WHEN TRIM([Building_Area_3]) IN ('','NULL') THEN NULL ELSE TRIM([Building_Area_3]) END AS [Building_Area_3],
	CASE WHEN TRIM([Building_Area_3_Indicator]) IN ('','NULL') THEN NULL ELSE TRIM([Building_Area_3_Indicator]) END AS [Building_Area_3_Indicator],
	CASE WHEN TRIM([Building_Area_4]) IN ('','NULL') THEN NULL ELSE TRIM([Building_Area_4]) END AS [Building_Area_4],
	CASE WHEN TRIM([Building_Area_4_Indicator]) IN ('','NULL') THEN NULL ELSE TRIM([Building_Area_4_Indicator]) END AS [Building_Area_4_Indicator],
	CASE WHEN TRIM([Building_Area_5]) IN ('','NULL') THEN NULL ELSE TRIM([Building_Area_5]) END AS [Building_Area_5],
	CASE WHEN TRIM([Building_Area_5_Indicator]) IN ('','NULL') THEN NULL ELSE TRIM([Building_Area_5_Indicator]) END AS [Building_Area_5_Indicator],
	CASE WHEN TRIM([Building_Area_6]) IN ('','NULL') THEN NULL ELSE TRIM([Building_Area_6]) END AS [Building_Area_6],
	CASE WHEN TRIM([Building_Area_6_Indicator]) IN ('','NULL') THEN NULL ELSE TRIM([Building_Area_6_Indicator]) END AS [Building_Area_6_Indicator],
	CASE WHEN TRIM([Building_Area_7]) IN ('','NULL') THEN NULL ELSE TRIM([Building_Area_7]) END AS [Building_Area_7],
	CASE WHEN TRIM([Building_Area_7_Indicator]) IN ('','NULL') THEN NULL ELSE TRIM([Building_Area_7_Indicator]) END AS [Building_Area_7_Indicator],
	CASE WHEN TRIM([Building_Class]) IN ('','NULL') THEN NULL ELSE TRIM([Building_Class]) END AS [Building_Class],
	CASE WHEN TRIM([Building_Condition]) IN ('','NULL') THEN NULL ELSE TRIM([Building_Condition]) END AS [Building_Condition],
	CASE WHEN TRIM([Building_Quality]) IN ('','NULL') THEN NULL ELSE TRIM([Building_Quality]) END AS [Building_Quality],
	CASE WHEN TRIM([Comments_Summary_of_Building_Cards]) IN ('','NULL') THEN NULL ELSE TRIM([Comments_Summary_of_Building_Cards]) END AS [Comments_Summary_of_Building_Cards],
	CASE WHEN TRIM([Effective_Year_Built]) IN ('','NULL') THEN NULL ELSE TRIM([Effective_Year_Built]) END AS [Effective_Year_Built],
	CASE WHEN TRIM([Elevator]) IN ('','NULL') THEN NULL ELSE TRIM([Elevator]) END AS [Elevator],
	CASE WHEN TRIM([Exterior_Walls]) IN ('','NULL') THEN NULL ELSE TRIM([Exterior_Walls]) END AS [Exterior_Walls],
	CASE WHEN TRIM([Extra_Features_1_Area]) IN ('','NULL') THEN NULL ELSE TRIM([Extra_Features_1_Area]) END AS [Extra_Features_1_Area],
	CASE WHEN TRIM([Extra_Features_1_Indicator]) IN ('','NULL') THEN NULL ELSE TRIM([Extra_Features_1_Indicator]) END AS [Extra_Features_1_Indicator],
	CASE WHEN TRIM([Extra_Features_2_Area]) IN ('','NULL') THEN NULL ELSE TRIM([Extra_Features_2_Area]) END AS [Extra_Features_2_Area],
	CASE WHEN TRIM([Extra_Features_2_Indicator]) IN ('','NULL') THEN NULL ELSE TRIM([Extra_Features_2_Indicator]) END AS [Extra_Features_2_Indicator],
	CASE WHEN TRIM([Extra_Features_3_Area]) IN ('','NULL') THEN NULL ELSE TRIM([Extra_Features_3_Area]) END AS [Extra_Features_3_Area],
	CASE WHEN TRIM([Extra_Features_3_Indicator]) IN ('','NULL') THEN NULL ELSE TRIM([Extra_Features_3_Indicator]) END AS [Extra_Features_3_Indicator],
	CASE WHEN TRIM([Extra_Features_4_Area]) IN ('','NULL') THEN NULL ELSE TRIM([Extra_Features_4_Area]) END AS [Extra_Features_4_Area],
	CASE WHEN TRIM([Extra_Features_4_Indicator]) IN ('','NULL') THEN NULL ELSE TRIM([Extra_Features_4_Indicator]) END AS [Extra_Features_4_Indicator],
	CASE WHEN TRIM([Fireplace]) IN ('','NULL') THEN NULL ELSE TRIM([Fireplace]) END AS [Fireplace],
	CASE WHEN TRIM([FLOOR_COVER]) IN ('','NULL') THEN NULL ELSE TRIM([FLOOR_COVER]) END AS [FLOOR_COVER],
	CASE WHEN TRIM([Foundation]) IN ('','NULL') THEN NULL ELSE TRIM([Foundation]) END AS [Foundation],
	CASE WHEN TRIM([Garage_Cars]) IN ('','NULL') THEN NULL ELSE TRIM([Garage_Cars]) END AS [Garage_Cars],
	CASE WHEN TRIM([Garage_Type]) IN ('','NULL') THEN NULL ELSE TRIM([Garage_Type]) END AS [Garage_Type],
	CASE WHEN TRIM([Heating]) IN ('','NULL') THEN NULL ELSE TRIM([Heating]) END AS [Heating],
	CASE WHEN TRIM([Heating_Fuel_Type]) IN ('','NULL') THEN NULL ELSE TRIM([Heating_Fuel_Type]) END AS [Heating_Fuel_Type],
	CASE WHEN TRIM([Interior_Walls]) IN ('','NULL') THEN NULL ELSE TRIM([Interior_Walls]) END AS [Interior_Walls],
	CASE WHEN TRIM([Main_Building_Area_Indicator]) IN ('','NULL') THEN NULL ELSE TRIM([Main_Building_Area_Indicator]) END AS [Main_Building_Area_Indicator],
	CASE WHEN TRIM([No_of_Buildings]) IN ('','NULL') THEN NULL ELSE TRIM([No_of_Buildings]) END AS [No_of_Buildings],
	CASE WHEN TRIM([No_of_Stories]) IN ('','NULL') THEN NULL ELSE TRIM([No_of_Stories]) END AS [No_of_Stories],
	CASE WHEN TRIM([Number_of_Baths]) IN ('','NULL') THEN NULL ELSE TRIM([Number_of_Baths]) END AS [Number_of_Baths],
	CASE WHEN TRIM([Number_of_Bedrooms]) IN ('','NULL') THEN NULL ELSE TRIM([Number_of_Bedrooms]) END AS [Number_of_Bedrooms],
	CASE WHEN TRIM([Number_of_Partial_Baths]) IN ('','NULL') THEN NULL ELSE TRIM([Number_of_Partial_Baths]) END AS [Number_of_Partial_Baths],
	CASE WHEN TRIM([Number_of_Units]) IN ('','NULL') THEN NULL ELSE TRIM([Number_of_Units]) END AS [Number_of_Units],
	CASE WHEN TRIM([Other_Impr_Building_Area_1]) IN ('','NULL') THEN NULL ELSE TRIM([Other_Impr_Building_Area_1]) END AS [Other_Impr_Building_Area_1],
	CASE WHEN TRIM([Other_Impr_Building_Area_2]) IN ('','NULL') THEN NULL ELSE TRIM([Other_Impr_Building_Area_2]) END AS [Other_Impr_Building_Area_2],
	CASE WHEN TRIM([Other_Impr_Building_Area_3]) IN ('','NULL') THEN NULL ELSE TRIM([Other_Impr_Building_Area_3]) END AS [Other_Impr_Building_Area_3],
	CASE WHEN TRIM([Other_Impr_Building_Area_4]) IN ('','NULL') THEN NULL ELSE TRIM([Other_Impr_Building_Area_4]) END AS [Other_Impr_Building_Area_4],
	CASE WHEN TRIM([Other_Impr_Building_Area_5]) IN ('','NULL') THEN NULL ELSE TRIM([Other_Impr_Building_Area_5]) END AS [Other_Impr_Building_Area_5],
	CASE WHEN TRIM([Other_Impr_Building_Indicator_1]) IN ('','NULL') THEN NULL ELSE TRIM([Other_Impr_Building_Indicator_1]) END AS [Other_Impr_Building_Indicator_1],
	CASE WHEN TRIM([Other_Impr_Building_Indicator_2]) IN ('','NULL') THEN NULL ELSE TRIM([Other_Impr_Building_Indicator_2]) END AS [Other_Impr_Building_Indicator_2],
	CASE WHEN TRIM([Other_Impr_Building_Indicator_3]) IN ('','NULL') THEN NULL ELSE TRIM([Other_Impr_Building_Indicator_3]) END AS [Other_Impr_Building_Indicator_3],
	CASE WHEN TRIM([Other_Impr_Building_Indicator_4]) IN ('','NULL') THEN NULL ELSE TRIM([Other_Impr_Building_Indicator_4]) END AS [Other_Impr_Building_Indicator_4],
	CASE WHEN TRIM([Other_Impr_Building_Indicator_5]) IN ('','NULL') THEN NULL ELSE TRIM([Other_Impr_Building_Indicator_5]) END AS [Other_Impr_Building_Indicator_5],
	CASE WHEN TRIM([Other_Rooms]) IN ('','NULL') THEN NULL ELSE TRIM([Other_Rooms]) END AS [Other_Rooms],
	CASE WHEN TRIM([N_of_Plumbing_Fixtures]) IN ('','NULL') THEN NULL ELSE TRIM([N_of_Plumbing_Fixtures]) END AS [N_of_Plumbing_Fixtures],
	CASE WHEN TRIM([Pool]) IN ('','NULL') THEN NULL ELSE TRIM([Pool]) END AS [Pool],
	CASE WHEN TRIM([Roof_Cover]) IN ('','NULL') THEN NULL ELSE TRIM([Roof_Cover]) END AS [Roof_Cover],
	CASE WHEN TRIM([Roof_Type]) IN ('','NULL') THEN NULL ELSE TRIM([Roof_Type]) END AS [Roof_Type],
	CASE WHEN TRIM([Sewer]) IN ('','NULL') THEN NULL ELSE TRIM([Sewer]) END AS [Sewer],
	CASE WHEN TRIM([Standardized_Land_Use_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Standardized_Land_Use_Code]) END AS [Standardized_Land_Use_Code],
	CASE WHEN TRIM([Style]) IN ('','NULL') THEN NULL ELSE TRIM([Style]) END AS [Style],
	CASE WHEN TRIM([Total_Number_of_Rooms]) IN ('','NULL') THEN NULL ELSE TRIM([Total_Number_of_Rooms]) END AS [Total_Number_of_Rooms],
	CASE WHEN TRIM([Type_Construction]) IN ('','NULL') THEN NULL ELSE TRIM([Type_Construction]) END AS [Type_Construction],
	CASE WHEN TRIM([Water]) IN ('','NULL') THEN NULL ELSE TRIM([Water]) END AS [Water],
	CASE WHEN TRIM([Year_Built]) IN ('','NULL') THEN NULL ELSE TRIM([Year_Built]) END AS [Year_Built],
	CASE WHEN TRIM([Zoning]) IN ('','NULL') THEN NULL ELSE TRIM([Zoning]) END AS [Zoning],
	CASE WHEN TRIM([Mtg01_lender_name_beneficiary]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_lender_name_beneficiary]) END AS [Mtg01_lender_name_beneficiary],
	CASE WHEN TRIM([Mtg01_lender_type]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_lender_type]) END AS [Mtg01_lender_type],
	CASE WHEN TRIM([Mtg01_original_date_of_contract]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_original_date_of_contract]) END AS [Mtg01_original_date_of_contract],
	CASE WHEN TRIM([Mtg01_recording_date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_recording_date]) END AS [Mtg01_recording_date],
	CASE WHEN TRIM([Mtg01_Loan_Amount]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Loan_Amount]) END AS [Mtg01_Loan_Amount],
	CASE WHEN TRIM([Mtg01_loan_type]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_loan_type]) END AS [Mtg01_loan_type],
	CASE WHEN TRIM([Mtg01_type_financing]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_type_financing]) END AS [Mtg01_type_financing],
	CASE WHEN TRIM([Mtg01_interest_rate]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_interest_rate]) END AS [Mtg01_interest_rate],
	CASE WHEN TRIM([Mtg01_due_date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_due_date]) END AS [Mtg01_due_date],
	CASE WHEN TRIM([Mtg01_Adjustable_Rate_Rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Adjustable_Rate_Rider]) END AS [Mtg01_Adjustable_Rate_Rider],
	CASE WHEN TRIM([Mtg01_Adjustable_Rate_Index]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Adjustable_Rate_Index]) END AS [Mtg01_Adjustable_Rate_Index],
	CASE WHEN TRIM([Mtg01_Change_Index]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Change_Index]) END AS [Mtg01_Change_Index],
	CASE WHEN TRIM([Mtg01_Rate_Change_Frequency]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Rate_Change_Frequency]) END AS [Mtg01_Rate_Change_Frequency],
	CASE WHEN TRIM([Mtg01_Interest_Rate_Not_Greater_Than]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Interest_Rate_Not_Greater_Than]) END AS [Mtg01_Interest_Rate_Not_Greater_Than],
	CASE WHEN TRIM([Mtg01_Interest_Rate_Not_Less_Than]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Interest_Rate_Not_Less_Than]) END AS [Mtg01_Interest_Rate_Not_Less_Than],
	CASE WHEN TRIM([Mtg01_Maximum_Interest_Rate]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Maximum_Interest_Rate]) END AS [Mtg01_Maximum_Interest_Rate],
	CASE WHEN TRIM([Mtg01_Interest_Only_Period]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Interest_Only_Period]) END AS [Mtg01_Interest_Only_Period],
	CASE WHEN TRIM([Mtg01_fixed_step_conversion_rate_rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_fixed_step_conversion_rate_rider]) END AS [Mtg01_fixed_step_conversion_rate_rider],
	CASE WHEN TRIM([Mtg01_First_Change_Date_Year_Conversion_Rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_First_Change_Date_Year_Conversion_Rider]) END AS [Mtg01_First_Change_Date_Year_Conversion_Rider],
	CASE WHEN TRIM([Mtg01_First_Change_Date_Month_Day_Conversion_Rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_First_Change_Date_Month_Day_Conversion_Rider]) END AS [Mtg01_First_Change_Date_Month_Day_Conversion_Rider],
	CASE WHEN TRIM([Mtg01_Prepayment_Rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Prepayment_Rider]) END AS [Mtg01_Prepayment_Rider],
	CASE WHEN TRIM([Mtg01_Prepayment_Term_Penalty_Rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Prepayment_Term_Penalty_Rider]) END AS [Mtg01_Prepayment_Term_Penalty_Rider],
	CASE WHEN TRIM([Mtg01_Title_Company_Name]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Title_Company_Name]) END AS [Mtg01_Title_Company_Name],
	CASE WHEN TRIM([Mtg01_Lender_Name]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Lender_Name]) END AS [Mtg01_Lender_Name],
	CASE WHEN TRIM([Mtg01_Lender_Mail_Full_Street_Address]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Lender_Mail_Full_Street_Address]) END AS [Mtg01_Lender_Mail_Full_Street_Address],
	CASE WHEN TRIM([Mtg01_Lender_Mail_Unit]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Lender_Mail_Unit]) END AS [Mtg01_Lender_Mail_Unit],
	CASE WHEN TRIM([Mtg01_Lender_Mail_City]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Lender_Mail_City]) END AS [Mtg01_Lender_Mail_City],
	CASE WHEN TRIM([Mtg01_Lender_Mail_State]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Lender_Mail_State]) END AS [Mtg01_Lender_Mail_State],
	CASE WHEN TRIM([Mtg01_Lender_Mail_Zip_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Lender_Mail_Zip_Code]) END AS [Mtg01_Lender_Mail_Zip_Code],
	CASE WHEN TRIM([Mtg01_Lender_Mail_Zip_Plus4Code]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Lender_Mail_Zip_Plus4Code]) END AS [Mtg01_Lender_Mail_Zip_Plus4Code],
	CASE WHEN TRIM([Mtg01_Loan_Term_Months]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Loan_Term_Months]) END AS [Mtg01_Loan_Term_Months],
	CASE WHEN TRIM([Mtg01_Loan_Term_Years]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Loan_Term_Years]) END AS [Mtg01_Loan_Term_Years],
	CASE WHEN TRIM([Mtg01_loan_number]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_loan_number]) END AS [Mtg01_loan_number],
	CASE WHEN TRIM([Mtg01_Construction_Loan]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Construction_Loan]) END AS [Mtg01_Construction_Loan],
	CASE WHEN TRIM([Mtg01_Cash_Purchase]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Cash_Purchase]) END AS [Mtg01_Cash_Purchase],
	CASE WHEN TRIM([Mtg01_StandAlone_Refi]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_StandAlone_Refi]) END AS [Mtg01_StandAlone_Refi],
	CASE WHEN TRIM([Mtg01_Equity_Credit_Line]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Equity_Credit_Line]) END AS [Mtg01_Equity_Credit_Line],
	CASE WHEN TRIM([Mtg01_Curr_Est_Bal]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Curr_Est_Bal]) END AS [Mtg01_Curr_Est_Bal],
	CASE WHEN TRIM([Mtg01_Purpose_Of_Loan]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Purpose_Of_Loan]) END AS [Mtg01_Purpose_Of_Loan],
	CASE WHEN TRIM([Mtg01_Purchase_Mtg_Ind]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Purchase_Mtg_Ind]) END AS [Mtg01_Purchase_Mtg_Ind],
	CASE WHEN TRIM([Mtg01_Est_Monthly_P&I]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Est_Monthly_P&I]) END AS [Mtg01_Est_Monthly_P&I],
	CASE WHEN TRIM([Mtg01_Est_Monthly_Principal]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Est_Monthly_Principal]) END AS [Mtg01_Est_Monthly_Principal],
	CASE WHEN TRIM([Mtg01_Est_Monthly_Interest]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Est_Monthly_Interest]) END AS [Mtg01_Est_Monthly_Interest],
	CASE WHEN TRIM([Mtg01_Curr_Est_Int_Rate]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Curr_Est_Int_Rate]) END AS [Mtg01_Curr_Est_Int_Rate],
	CASE WHEN TRIM([Mtg01_Assigned_Lender_Name]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Assigned_Lender_Name]) END AS [Mtg01_Assigned_Lender_Name],
	CASE WHEN TRIM([Mtg01_Assignment_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Assignment_Date]) END AS [Mtg01_Assignment_Date],
	CASE WHEN TRIM([Mtg01_Number_of_Assignments]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_Number_of_Assignments]) END AS [Mtg01_Number_of_Assignments],
	CASE WHEN TRIM([Mtg01_PreForeclosure_Status]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_PreForeclosure_Status]) END AS [Mtg01_PreForeclosure_Status],
	CASE WHEN TRIM([Mtg01_PreFcl_Recording_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_PreFcl_Recording_Date]) END AS [Mtg01_PreFcl_Recording_Date],
	CASE WHEN TRIM([Mtg01_PreFcl_Filing_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_PreFcl_Filing_Date]) END AS [Mtg01_PreFcl_Filing_Date],
	CASE WHEN TRIM([Mtg01_PreFcl_Case_Trustee_Sale_Nbr]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_PreFcl_Case_Trustee_Sale_Nbr]) END AS [Mtg01_PreFcl_Case_Trustee_Sale_Nbr],
	CASE WHEN TRIM([Mtg01_PreFcl_Auction_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg01_PreFcl_Auction_Date]) END AS [Mtg01_PreFcl_Auction_Date],
	CASE WHEN TRIM([Mtg02_lender_name_beneficiary]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_lender_name_beneficiary]) END AS [Mtg02_lender_name_beneficiary],
	CASE WHEN TRIM([Mtg02_lender_type]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_lender_type]) END AS [Mtg02_lender_type],
	CASE WHEN TRIM([Mtg02_original_date_of_contract]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_original_date_of_contract]) END AS [Mtg02_original_date_of_contract],
	CASE WHEN TRIM([Mtg02_recording_date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_recording_date]) END AS [Mtg02_recording_date],
	CASE WHEN TRIM([Mtg02_Loan_Amount]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Loan_Amount]) END AS [Mtg02_Loan_Amount],
	CASE WHEN TRIM([Mtg02_loan_type]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_loan_type]) END AS [Mtg02_loan_type],
	CASE WHEN TRIM([Mtg02_type_financing]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_type_financing]) END AS [Mtg02_type_financing],
	CASE WHEN TRIM([Mtg02_interest_rate]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_interest_rate]) END AS [Mtg02_interest_rate],
	CASE WHEN TRIM([Mtg02_due_date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_due_date]) END AS [Mtg02_due_date],
	CASE WHEN TRIM([Mtg02_Adjustable_Rate_Rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Adjustable_Rate_Rider]) END AS [Mtg02_Adjustable_Rate_Rider],
	CASE WHEN TRIM([Mtg02_Adjustable_Rate_Index]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Adjustable_Rate_Index]) END AS [Mtg02_Adjustable_Rate_Index],
	CASE WHEN TRIM([Mtg02_Change_Index]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Change_Index]) END AS [Mtg02_Change_Index],
	CASE WHEN TRIM([Mtg02_Rate_Change_Frequency]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Rate_Change_Frequency]) END AS [Mtg02_Rate_Change_Frequency],
	CASE WHEN TRIM([Mtg02_Interest_Rate_Not_Greater_Than]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Interest_Rate_Not_Greater_Than]) END AS [Mtg02_Interest_Rate_Not_Greater_Than],
	CASE WHEN TRIM([Mtg02_Interest_Rate_Not_Less_Than]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Interest_Rate_Not_Less_Than]) END AS [Mtg02_Interest_Rate_Not_Less_Than],
	CASE WHEN TRIM([Mtg02_Maximum_Interest_Rate]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Maximum_Interest_Rate]) END AS [Mtg02_Maximum_Interest_Rate],
	CASE WHEN TRIM([Mtg02_Interest_Only_Period]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Interest_Only_Period]) END AS [Mtg02_Interest_Only_Period],
	CASE WHEN TRIM([Mtg02_fixed_step_conversion_rate_rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_fixed_step_conversion_rate_rider]) END AS [Mtg02_fixed_step_conversion_rate_rider],
	CASE WHEN TRIM([Mtg02_First_Change_Date_Year_Conversion_Rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_First_Change_Date_Year_Conversion_Rider]) END AS [Mtg02_First_Change_Date_Year_Conversion_Rider],
	CASE WHEN TRIM([Mtg02_First_Change_Date_Month_Day_Conversion_Rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_First_Change_Date_Month_Day_Conversion_Rider]) END AS [Mtg02_First_Change_Date_Month_Day_Conversion_Rider],
	CASE WHEN TRIM([Mtg02_Prepayment_Rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Prepayment_Rider]) END AS [Mtg02_Prepayment_Rider],
	CASE WHEN TRIM([Mtg02_Prepayment_Term_Penalty_Rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Prepayment_Term_Penalty_Rider]) END AS [Mtg02_Prepayment_Term_Penalty_Rider],
	CASE WHEN TRIM([Mtg02_Title_Company_Name]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Title_Company_Name]) END AS [Mtg02_Title_Company_Name],
	CASE WHEN TRIM([Mtg02_Lender_Name]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Lender_Name]) END AS [Mtg02_Lender_Name],
	CASE WHEN TRIM([Mtg02_Lender_Mail_Full_Street_Address]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Lender_Mail_Full_Street_Address]) END AS [Mtg02_Lender_Mail_Full_Street_Address],
	CASE WHEN TRIM([Mtg02_Lender_Mail_Unit]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Lender_Mail_Unit]) END AS [Mtg02_Lender_Mail_Unit],
	CASE WHEN TRIM([Mtg02_Lender_Mail_City]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Lender_Mail_City]) END AS [Mtg02_Lender_Mail_City],
	CASE WHEN TRIM([Mtg02_Lender_Mail_State]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Lender_Mail_State]) END AS [Mtg02_Lender_Mail_State],
	CASE WHEN TRIM([Mtg02_Lender_Mail_Zip_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Lender_Mail_Zip_Code]) END AS [Mtg02_Lender_Mail_Zip_Code],
	CASE WHEN TRIM([Mtg02_Lender_Mail_Zip_Plus4Code]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Lender_Mail_Zip_Plus4Code]) END AS [Mtg02_Lender_Mail_Zip_Plus4Code],
	CASE WHEN TRIM([Mtg02_Loan_Term_Months]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Loan_Term_Months]) END AS [Mtg02_Loan_Term_Months],
	CASE WHEN TRIM([Mtg02_Loan_Term_Years]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Loan_Term_Years]) END AS [Mtg02_Loan_Term_Years],
	CASE WHEN TRIM([Mtg02_loan_number]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_loan_number]) END AS [Mtg02_loan_number],
	CASE WHEN TRIM([Mtg02_Construction_Loan]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Construction_Loan]) END AS [Mtg02_Construction_Loan],
	CASE WHEN TRIM([Mtg02_Cash_Purchase]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Cash_Purchase]) END AS [Mtg02_Cash_Purchase],
	CASE WHEN TRIM([Mtg02_StandAlone_Refi]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_StandAlone_Refi]) END AS [Mtg02_StandAlone_Refi],
	CASE WHEN TRIM([Mtg02_Equity_Credit_Line]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Equity_Credit_Line]) END AS [Mtg02_Equity_Credit_Line],
	CASE WHEN TRIM([Mtg02_Curr_Est_Bal]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Curr_Est_Bal]) END AS [Mtg02_Curr_Est_Bal],
	CASE WHEN TRIM([Mtg02_Purpose_Of_Loan]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Purpose_Of_Loan]) END AS [Mtg02_Purpose_Of_Loan],
	CASE WHEN TRIM([Mtg02_Purchase_Mtg_Ind]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Purchase_Mtg_Ind]) END AS [Mtg02_Purchase_Mtg_Ind],
	CASE WHEN TRIM([Mtg02_Est_Monthly_P&I]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Est_Monthly_P&I]) END AS [Mtg02_Est_Monthly_P&I],
	CASE WHEN TRIM([Mtg02_Est_Monthly_Principal]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Est_Monthly_Principal]) END AS [Mtg02_Est_Monthly_Principal],
	CASE WHEN TRIM([Mtg02_Est_Monthly_Interest]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Est_Monthly_Interest]) END AS [Mtg02_Est_Monthly_Interest],
	CASE WHEN TRIM([Mtg02_Curr_Est_Int_Rate]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Curr_Est_Int_Rate]) END AS [Mtg02_Curr_Est_Int_Rate],
	CASE WHEN TRIM([Mtg02_Assigned_Lender_Name]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Assigned_Lender_Name]) END AS [Mtg02_Assigned_Lender_Name],
	CASE WHEN TRIM([Mtg02_Assignment_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Assignment_Date]) END AS [Mtg02_Assignment_Date],
	CASE WHEN TRIM([Mtg02_Number_of_Assignments]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_Number_of_Assignments]) END AS [Mtg02_Number_of_Assignments],
	CASE WHEN TRIM([Mtg02_PreForeclosure_Status]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_PreForeclosure_Status]) END AS [Mtg02_PreForeclosure_Status],
	CASE WHEN TRIM([Mtg02_PreFcl_Recording_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_PreFcl_Recording_Date]) END AS [Mtg02_PreFcl_Recording_Date],
	CASE WHEN TRIM([Mtg02_PreFcl_Filing_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_PreFcl_Filing_Date]) END AS [Mtg02_PreFcl_Filing_Date],
	CASE WHEN TRIM([Mtg02_PreFcl_Case_Trustee_Sale_Nbr]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_PreFcl_Case_Trustee_Sale_Nbr]) END AS [Mtg02_PreFcl_Case_Trustee_Sale_Nbr],
	CASE WHEN TRIM([Mtg02_PreFcl_Auction_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg02_PreFcl_Auction_Date]) END AS [Mtg02_PreFcl_Auction_Date],
	CASE WHEN TRIM([Mtg03_lender_name_beneficiary]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_lender_name_beneficiary]) END AS [Mtg03_lender_name_beneficiary],
	CASE WHEN TRIM([Mtg03_lender_type]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_lender_type]) END AS [Mtg03_lender_type],
	CASE WHEN TRIM([Mtg03_original_date_of_contract]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_original_date_of_contract]) END AS [Mtg03_original_date_of_contract],
	CASE WHEN TRIM([Mtg03_recording_date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_recording_date]) END AS [Mtg03_recording_date],
	CASE WHEN TRIM([Mtg03_Loan_Amount]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Loan_Amount]) END AS [Mtg03_Loan_Amount],
	CASE WHEN TRIM([Mtg03_loan_type]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_loan_type]) END AS [Mtg03_loan_type],
	CASE WHEN TRIM([Mtg03_type_financing]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_type_financing]) END AS [Mtg03_type_financing],
	CASE WHEN TRIM([Mtg03_interest_rate]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_interest_rate]) END AS [Mtg03_interest_rate],
	CASE WHEN TRIM([Mtg03_due_date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_due_date]) END AS [Mtg03_due_date],
	CASE WHEN TRIM([Mtg03_Adjustable_Rate_Rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Adjustable_Rate_Rider]) END AS [Mtg03_Adjustable_Rate_Rider],
	CASE WHEN TRIM([Mtg03_Adjustable_Rate_Index]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Adjustable_Rate_Index]) END AS [Mtg03_Adjustable_Rate_Index],
	CASE WHEN TRIM([Mtg03_Change_Index]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Change_Index]) END AS [Mtg03_Change_Index],
	CASE WHEN TRIM([Mtg03_Rate_Change_Frequency]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Rate_Change_Frequency]) END AS [Mtg03_Rate_Change_Frequency],
	CASE WHEN TRIM([Mtg03_Interest_Rate_Not_Greater_Than]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Interest_Rate_Not_Greater_Than]) END AS [Mtg03_Interest_Rate_Not_Greater_Than],
	CASE WHEN TRIM([Mtg03_Interest_Rate_Not_Less_Than]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Interest_Rate_Not_Less_Than]) END AS [Mtg03_Interest_Rate_Not_Less_Than],
	CASE WHEN TRIM([Mtg03_Maximum_Interest_Rate]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Maximum_Interest_Rate]) END AS [Mtg03_Maximum_Interest_Rate],
	CASE WHEN TRIM([Mtg03_Interest_Only_Period]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Interest_Only_Period]) END AS [Mtg03_Interest_Only_Period],
	CASE WHEN TRIM([Mtg03_fixed_step_conversion_rate_rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_fixed_step_conversion_rate_rider]) END AS [Mtg03_fixed_step_conversion_rate_rider],
	CASE WHEN TRIM([Mtg03_First_Change_Date_Year_Conversion_Rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_First_Change_Date_Year_Conversion_Rider]) END AS [Mtg03_First_Change_Date_Year_Conversion_Rider],
	CASE WHEN TRIM([Mtg03_First_Change_Date_Month_Day_Conversion_Rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_First_Change_Date_Month_Day_Conversion_Rider]) END AS [Mtg03_First_Change_Date_Month_Day_Conversion_Rider],
	CASE WHEN TRIM([Mtg03_Prepayment_Rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Prepayment_Rider]) END AS [Mtg03_Prepayment_Rider],
	CASE WHEN TRIM([Mtg03_Prepayment_Term_Penalty_Rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Prepayment_Term_Penalty_Rider]) END AS [Mtg03_Prepayment_Term_Penalty_Rider],
	CASE WHEN TRIM([Mtg03_Title_Company_Name]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Title_Company_Name]) END AS [Mtg03_Title_Company_Name],
	CASE WHEN TRIM([Mtg03_Lender_Name]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Lender_Name]) END AS [Mtg03_Lender_Name],
	CASE WHEN TRIM([Mtg03_Lender_Mail_Full_Street_Address]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Lender_Mail_Full_Street_Address]) END AS [Mtg03_Lender_Mail_Full_Street_Address],
	CASE WHEN TRIM([Mtg03_Lender_Mail_Unit]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Lender_Mail_Unit]) END AS [Mtg03_Lender_Mail_Unit],
	CASE WHEN TRIM([Mtg03_Lender_Mail_City]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Lender_Mail_City]) END AS [Mtg03_Lender_Mail_City],
	CASE WHEN TRIM([Mtg03_Lender_Mail_State]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Lender_Mail_State]) END AS [Mtg03_Lender_Mail_State],
	CASE WHEN TRIM([Mtg03_Lender_Mail_Zip_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Lender_Mail_Zip_Code]) END AS [Mtg03_Lender_Mail_Zip_Code],
	CASE WHEN TRIM([Mtg03_Lender_Mail_Zip_Plus4Code]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Lender_Mail_Zip_Plus4Code]) END AS [Mtg03_Lender_Mail_Zip_Plus4Code],
	CASE WHEN TRIM([Mtg03_Loan_Term_Months]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Loan_Term_Months]) END AS [Mtg03_Loan_Term_Months],
	CASE WHEN TRIM([Mtg03_Loan_Term_Years]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Loan_Term_Years]) END AS [Mtg03_Loan_Term_Years],
	CASE WHEN TRIM([Mtg03_loan_number]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_loan_number]) END AS [Mtg03_loan_number],
	CASE WHEN TRIM([Mtg03_Construction_Loan]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Construction_Loan]) END AS [Mtg03_Construction_Loan],
	CASE WHEN TRIM([Mtg03_Cash_Purchase]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Cash_Purchase]) END AS [Mtg03_Cash_Purchase],
	CASE WHEN TRIM([Mtg03_StandAlone_Refi]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_StandAlone_Refi]) END AS [Mtg03_StandAlone_Refi],
	CASE WHEN TRIM([Mtg03_Equity_Credit_Line]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Equity_Credit_Line]) END AS [Mtg03_Equity_Credit_Line],
	CASE WHEN TRIM([Mtg03_Curr_Est_Bal]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Curr_Est_Bal]) END AS [Mtg03_Curr_Est_Bal],
	CASE WHEN TRIM([Mtg03_Purpose_Of_Loan]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Purpose_Of_Loan]) END AS [Mtg03_Purpose_Of_Loan],
	CASE WHEN TRIM([Mtg03_Purchase_Mtg_Ind]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Purchase_Mtg_Ind]) END AS [Mtg03_Purchase_Mtg_Ind],
	CASE WHEN TRIM([Mtg03_Est_Monthly_P&I]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Est_Monthly_P&I]) END AS [Mtg03_Est_Monthly_P&I],
	CASE WHEN TRIM([Mtg03_Est_Monthly_Principal]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Est_Monthly_Principal]) END AS [Mtg03_Est_Monthly_Principal],
	CASE WHEN TRIM([Mtg03_Est_Monthly_Interest]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Est_Monthly_Interest]) END AS [Mtg03_Est_Monthly_Interest],
	CASE WHEN TRIM([Mtg03_Curr_Est_Int_Rate]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Curr_Est_Int_Rate]) END AS [Mtg03_Curr_Est_Int_Rate],
	CASE WHEN TRIM([Mtg03_Assigned_Lender_Name]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Assigned_Lender_Name]) END AS [Mtg03_Assigned_Lender_Name],
	CASE WHEN TRIM([Mtg03_Assignment_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Assignment_Date]) END AS [Mtg03_Assignment_Date],
	CASE WHEN TRIM([Mtg03_Number_of_Assignments]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_Number_of_Assignments]) END AS [Mtg03_Number_of_Assignments],
	CASE WHEN TRIM([Mtg03_PreForeclosure_Status]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_PreForeclosure_Status]) END AS [Mtg03_PreForeclosure_Status],
	CASE WHEN TRIM([Mtg03_PreFcl_Recording_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_PreFcl_Recording_Date]) END AS [Mtg03_PreFcl_Recording_Date],
	CASE WHEN TRIM([Mtg03_PreFcl_Filing_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_PreFcl_Filing_Date]) END AS [Mtg03_PreFcl_Filing_Date],
	CASE WHEN TRIM([Mtg03_PreFcl_Case_Trustee_Sale_Nbr]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_PreFcl_Case_Trustee_Sale_Nbr]) END AS [Mtg03_PreFcl_Case_Trustee_Sale_Nbr],
	CASE WHEN TRIM([Mtg03_PreFcl_Auction_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg03_PreFcl_Auction_Date]) END AS [Mtg03_PreFcl_Auction_Date],
	CASE WHEN TRIM([Mtg04_lender_name_beneficiary]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_lender_name_beneficiary]) END AS [Mtg04_lender_name_beneficiary],
	CASE WHEN TRIM([Mtg04_lender_type]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_lender_type]) END AS [Mtg04_lender_type],
	CASE WHEN TRIM([Mtg04_original_date_of_contract]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_original_date_of_contract]) END AS [Mtg04_original_date_of_contract],
	CASE WHEN TRIM([Mtg04_recording_date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_recording_date]) END AS [Mtg04_recording_date],
	CASE WHEN TRIM([Mtg04_Loan_Amount]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Loan_Amount]) END AS [Mtg04_Loan_Amount],
	CASE WHEN TRIM([Mtg04_loan_type]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_loan_type]) END AS [Mtg04_loan_type],
	CASE WHEN TRIM([Mtg04_type_financing]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_type_financing]) END AS [Mtg04_type_financing],
	CASE WHEN TRIM([Mtg04_interest_rate]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_interest_rate]) END AS [Mtg04_interest_rate],
	CASE WHEN TRIM([Mtg04_due_date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_due_date]) END AS [Mtg04_due_date],
	CASE WHEN TRIM([Mtg04_Adjustable_Rate_Rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Adjustable_Rate_Rider]) END AS [Mtg04_Adjustable_Rate_Rider],
	CASE WHEN TRIM([Mtg04_Adjustable_Rate_Index]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Adjustable_Rate_Index]) END AS [Mtg04_Adjustable_Rate_Index],
	CASE WHEN TRIM([Mtg04_Change_Index]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Change_Index]) END AS [Mtg04_Change_Index],
	CASE WHEN TRIM([Mtg04_Rate_Change_Frequency]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Rate_Change_Frequency]) END AS [Mtg04_Rate_Change_Frequency],
	CASE WHEN TRIM([Mtg04_Interest_Rate_Not_Greater_Than]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Interest_Rate_Not_Greater_Than]) END AS [Mtg04_Interest_Rate_Not_Greater_Than],
	CASE WHEN TRIM([Mtg04_Interest_Rate_Not_Less_Than]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Interest_Rate_Not_Less_Than]) END AS [Mtg04_Interest_Rate_Not_Less_Than],
	CASE WHEN TRIM([Mtg04_Maximum_Interest_Rate]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Maximum_Interest_Rate]) END AS [Mtg04_Maximum_Interest_Rate],
	CASE WHEN TRIM([Mtg04_Interest_Only_Period]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Interest_Only_Period]) END AS [Mtg04_Interest_Only_Period],
	CASE WHEN TRIM([Mtg04_fixed_step_conversion_rate_rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_fixed_step_conversion_rate_rider]) END AS [Mtg04_fixed_step_conversion_rate_rider],
	CASE WHEN TRIM([Mtg04_First_Change_Date_Year_Conversion_Rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_First_Change_Date_Year_Conversion_Rider]) END AS [Mtg04_First_Change_Date_Year_Conversion_Rider],
	CASE WHEN TRIM([Mtg04_First_Change_Date_Month_Day_Conversion_Rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_First_Change_Date_Month_Day_Conversion_Rider]) END AS [Mtg04_First_Change_Date_Month_Day_Conversion_Rider],
	CASE WHEN TRIM([Mtg04_Prepayment_Rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Prepayment_Rider]) END AS [Mtg04_Prepayment_Rider],
	CASE WHEN TRIM([Mtg04_Prepayment_Term_Penalty_Rider]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Prepayment_Term_Penalty_Rider]) END AS [Mtg04_Prepayment_Term_Penalty_Rider],
	CASE WHEN TRIM([Mtg04_Title_Company_Name]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Title_Company_Name]) END AS [Mtg04_Title_Company_Name],
	CASE WHEN TRIM([Mtg04_Lender_Name]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Lender_Name]) END AS [Mtg04_Lender_Name],
	CASE WHEN TRIM([Mtg04_Lender_Mail_Full_Street_Address]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Lender_Mail_Full_Street_Address]) END AS [Mtg04_Lender_Mail_Full_Street_Address],
	CASE WHEN TRIM([Mtg04_Lender_Mail_Unit]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Lender_Mail_Unit]) END AS [Mtg04_Lender_Mail_Unit],
	CASE WHEN TRIM([Mtg04_Lender_Mail_City]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Lender_Mail_City]) END AS [Mtg04_Lender_Mail_City],
	CASE WHEN TRIM([Mtg04_Lender_Mail_State]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Lender_Mail_State]) END AS [Mtg04_Lender_Mail_State],
	CASE WHEN TRIM([Mtg04_Lender_Mail_Zip_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Lender_Mail_Zip_Code]) END AS [Mtg04_Lender_Mail_Zip_Code],
	CASE WHEN TRIM([Mtg04_Lender_Mail_Zip_Plus4Code]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Lender_Mail_Zip_Plus4Code]) END AS [Mtg04_Lender_Mail_Zip_Plus4Code],
	CASE WHEN TRIM([Mtg04_Loan_Term_Months]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Loan_Term_Months]) END AS [Mtg04_Loan_Term_Months],
	CASE WHEN TRIM([Mtg04_Loan_Term_Years]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Loan_Term_Years]) END AS [Mtg04_Loan_Term_Years],
	CASE WHEN TRIM([Mtg04_loan_number]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_loan_number]) END AS [Mtg04_loan_number],
	CASE WHEN TRIM([Mtg04_Construction_Loan]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Construction_Loan]) END AS [Mtg04_Construction_Loan],
	CASE WHEN TRIM([Mtg04_Cash_Purchase]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Cash_Purchase]) END AS [Mtg04_Cash_Purchase],
	CASE WHEN TRIM([Mtg04_StandAlone_Refi]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_StandAlone_Refi]) END AS [Mtg04_StandAlone_Refi],
	CASE WHEN TRIM([Mtg04_Equity_Credit_Line]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Equity_Credit_Line]) END AS [Mtg04_Equity_Credit_Line],
	CASE WHEN TRIM([Mtg04_Curr_Est_Bal]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Curr_Est_Bal]) END AS [Mtg04_Curr_Est_Bal],
	CASE WHEN TRIM([Mtg04_Purpose_Of_Loan]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Purpose_Of_Loan]) END AS [Mtg04_Purpose_Of_Loan],
	CASE WHEN TRIM([Mtg04_Purchase_Mtg_Ind]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Purchase_Mtg_Ind]) END AS [Mtg04_Purchase_Mtg_Ind],
	CASE WHEN TRIM([Mtg04_Est_Monthly_P&I]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Est_Monthly_P&I]) END AS [Mtg04_Est_Monthly_P&I],
	CASE WHEN TRIM([Mtg04_Est_Monthly_Principal]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Est_Monthly_Principal]) END AS [Mtg04_Est_Monthly_Principal],
	CASE WHEN TRIM([Mtg04_Est_Monthly_Interest]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Est_Monthly_Interest]) END AS [Mtg04_Est_Monthly_Interest],
	CASE WHEN TRIM([Mtg04_Curr_Est_Int_Rate]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Curr_Est_Int_Rate]) END AS [Mtg04_Curr_Est_Int_Rate],
	CASE WHEN TRIM([Mtg04_Assigned_Lender_Name]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Assigned_Lender_Name]) END AS [Mtg04_Assigned_Lender_Name],
	CASE WHEN TRIM([Mtg04_Assignment_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Assignment_Date]) END AS [Mtg04_Assignment_Date],
	CASE WHEN TRIM([Mtg04_Number_of_Assignments]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_Number_of_Assignments]) END AS [Mtg04_Number_of_Assignments],
	CASE WHEN TRIM([Mtg04_PreForeclosure_Status]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_PreForeclosure_Status]) END AS [Mtg04_PreForeclosure_Status],
	CASE WHEN TRIM([Mtg04_PreFcl_Recording_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_PreFcl_Recording_Date]) END AS [Mtg04_PreFcl_Recording_Date],
	CASE WHEN TRIM([Mtg04_PreFcl_Filing_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_PreFcl_Filing_Date]) END AS [Mtg04_PreFcl_Filing_Date],
	CASE WHEN TRIM([Mtg04_PreFcl_Case_Trustee_Sale_Nbr]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_PreFcl_Case_Trustee_Sale_Nbr]) END AS [Mtg04_PreFcl_Case_Trustee_Sale_Nbr],
	CASE WHEN TRIM([Mtg04_PreFcl_Auction_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Mtg04_PreFcl_Auction_Date]) END AS [Mtg04_PreFcl_Auction_Date],
	CASE WHEN TRIM([Additional_Open_Lien_Count]) IN ('','NULL') THEN NULL ELSE TRIM([Additional_Open_Lien_Count]) END AS [Additional_Open_Lien_Count],
	CASE WHEN TRIM([Additional_Open_Lien_Balance]) IN ('','NULL') THEN NULL ELSE TRIM([Additional_Open_Lien_Balance]) END AS [Additional_Open_Lien_Balance],
	CASE WHEN TRIM([Total_Open_Lien_Count]) IN ('','NULL') THEN NULL ELSE TRIM([Total_Open_Lien_Count]) END AS [Total_Open_Lien_Count],
	CASE WHEN TRIM([Total_Open_Lien_Balance]) IN ('','NULL') THEN NULL ELSE TRIM([Total_Open_Lien_Balance]) END AS [Total_Open_Lien_Balance],
	CASE WHEN TRIM([Total_Financing_History_Count]) IN ('','NULL') THEN NULL ELSE TRIM([Total_Financing_History_Count]) END AS [Total_Financing_History_Count],
	CASE WHEN TRIM([Current_Est_LTV_Combined]) IN ('','NULL') THEN NULL ELSE TRIM([Current_Est_LTV_Combined]) END AS [Current_Est_LTV_Combined],
	CASE WHEN TRIM([Current_Est_LTV_Range_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Current_Est_LTV_Range_Code]) END AS [Current_Est_LTV_Range_Code],
	CASE WHEN TRIM([Current_Est_Equity_Dollars]) IN ('','NULL') THEN NULL ELSE TRIM([Current_Est_Equity_Dollars]) END AS [Current_Est_Equity_Dollars],
	CASE WHEN TRIM([Current_Est_Equity_Range_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Current_Est_Equity_Range_Code]) END AS [Current_Est_Equity_Range_Code],
	CASE WHEN TRIM([Purchase_LTV]) IN ('','NULL') THEN NULL ELSE TRIM([Purchase_LTV]) END AS [Purchase_LTV],
	CASE WHEN TRIM([Current_Foreclosure_Status]) IN ('','NULL') THEN NULL ELSE TRIM([Current_Foreclosure_Status]) END AS [Current_Foreclosure_Status],
	CASE WHEN TRIM([Foreclosure_Recording_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Foreclosure_Recording_Date]) END AS [Foreclosure_Recording_Date],
	CASE WHEN TRIM([Foreclosure_filing_date]) IN ('','NULL') THEN NULL ELSE TRIM([Foreclosure_filing_date]) END AS [Foreclosure_filing_date],
	CASE WHEN TRIM([Foreclosure_Case_Number]) IN ('','NULL') THEN NULL ELSE TRIM([Foreclosure_Case_Number]) END AS [Foreclosure_Case_Number],
	CASE WHEN TRIM([Foreclosure_Auction_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Foreclosure_Auction_Date]) END AS [Foreclosure_Auction_Date],
	CASE WHEN TRIM([ESTIMATED_VALUE]) IN ('','NULL') THEN NULL ELSE TRIM([ESTIMATED_VALUE]) END AS [ESTIMATED_VALUE],
	CASE WHEN TRIM([PRICE_RANGE_MIN]) IN ('','NULL') THEN NULL ELSE TRIM([PRICE_RANGE_MIN]) END AS [PRICE_RANGE_MIN],
	CASE WHEN TRIM([PRICE_RANGE_MAX]) IN ('','NULL') THEN NULL ELSE TRIM([PRICE_RANGE_MAX]) END AS [PRICE_RANGE_MAX],
	CASE WHEN TRIM([FSD_SCORE]) IN ('','NULL') THEN NULL ELSE TRIM([FSD_SCORE]) END AS [FSD_SCORE],
	CASE WHEN TRIM([CONFIDENCE_SCORE]) IN ('','NULL') THEN NULL ELSE TRIM([CONFIDENCE_SCORE]) END AS [CONFIDENCE_SCORE],
	CASE WHEN TRIM([QVM_Value_Range_Code]) IN ('','NULL') THEN NULL ELSE TRIM([QVM_Value_Range_Code]) END AS [QVM_Value_Range_Code],
	CASE WHEN TRIM([QVM_asof_Date]) IN ('','NULL') THEN NULL ELSE TRIM([QVM_asof_Date]) END AS [QVM_asof_Date],
	CASE WHEN TRIM([Trans_asof_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Trans_asof_Date]) END AS [Trans_asof_Date],
	CASE WHEN TRIM([Record_Creation_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Record_Creation_Date]) END AS [Record_Creation_Date],
	CASE WHEN TRIM([Quantarium_Version]) IN ('','NULL') THEN NULL ELSE TRIM([Quantarium_Version]) END AS [Quantarium_Version]
INTO [dbo].[Houseamp_WA_OL_Chg_20210913_New]
FROM [dbo].[Houseamp_WA_OL_Chg_20210913]



GO
RETURN
SET XACT_ABORT ON 
BEGIN transaction
DROP TABLE [dbo].[Houseamp_WA_OL_Chg_20210913]
EXEC sp_rename '[dbo].[Houseamp_WA_OL_Chg_20210913_New]','Houseamp_WA_OL_Chg_20210913','object'
COMMIT

ALTER TABLE [dbo].[Houseamp_WA_OL_Chg_20210913] REBUILD WITH (DATA_COMPRESSION = ROW)