SELECT 
* 
INTO #cols
FROM util.dbo.parsedelimited('QId	DBUSA_Household_ID	DBUSA_Individual_ID	Location_ID	Full_Name	Name_Prefix	First_Name	Middle_Initial	Last_Name	Suffix	Gender	Date_Of_Birth_Year	Date_Of_Birth_Month	Age	Age_Code_Description	Ethnic_Code	Ethnic_Group	Religious_Affiliation	Language_Preference	Hispanic_Country_Of_Origin	Assimilation_Code	Education_Individual	Occupation_Individual	Occupation_Individual_Range	Political_Party_Individual	Political_Ideology	Voter_ID	Veteran_Individual	Mail_Score_Code	Standardized_Address	City	State	Zip	ZIP_Plus4	Carrier_Route	Delivery_Point	Delivery_Point_Check_Digit	Address_Street_Number	Address_Street_Pre	Address_Street_Name	Address_Street_Suffix	Address_Street_Post	Address_Suite_Name	Address_Suite_Number	Line_Of_Travel	GeoCode_Match_Level	Latitude	Longitude	Time_Zone_Code	Time_Zone_Description	Census_Tract	Census_Block	County_Code	County_Name	FIPS_Code	CBSA_Code	CBSA_Description	Walk_Sequence	District_Congressional	District_State_Senate	District_State_House	District_State_Legislative	DMA_Code	DMA_Zone	Email_Present	Email	Email_02	Email_03	Email_04	Email_05	Area_Code	Phone	DNC	Scrubbed_Phoneable	Area_Code_Cell_Phone	Cell_Phone	Dwelling_Type	Home_Owner_Renter	Length_Of_Residence	Length_of_Residence_Code	Length_Of_Residence_Description	Recently_Moved_Flag	Recently_Moved_Year	Recently_Moved_Month	Household_Size	Household_Rank	Number_Of_Adults	Young_Adult_In_Household	Senior_Adult_In_Household	Generations_In_Household	Marital_Status	Recent_Divorce	Single_Parent	Children_Present	Number_Children	Childrens_Age_00_02	Childrens_Age_00_02_Male	Childrens_Age_00_02_Female	Childrens_Age_00_02_Unknown	Childrens_Age_03_05	Childrens_Age_03_05_Male	Childrens_Age_03_05_Female	Childrens_Age_03_05_Unknown	Childrens_Age_06_10	Childrens_Age_06_10_Male	Childrens_Age_06_10_Female	Childrens_Age_06_10_Unknown	Childrens_Age_11_15	Childrens_Age_11_15_Male	Childrens_Age_11_15_Female	Childrens_Age_11_15_Unknown	Childrens_Age_16_17	Childrens_Age_16_17_Male	Childrens_Age_16_17_Female	Childrens_Age_16_17_Unknown	Child_Near_High_School_Graduation	College_Graduate	Christian_Families	Business_Owner	SOHO	Working_Woman	Veteran_Present_In_Household	Credit_Card_User	Mail_Order_Donor	Mail_Order_Buyer	Mail_Order_Responder	TV_Satellite_Dish	Pet_Owner	Cat_Owner	Dog_Owner	Other_Pet_Owner	New_Teen_Driver	New_Teen_Driver_Gender	Boat_Owner	Truck_Owner	Motorcycle_Owner	RV_Owner	Auto_Buy_New	Auto_Buy_Used	Auto_Buy_Used_5_Months_Or_Less	Auto_Buy_Used_6_Months_Or_More	Median_HseHld_Income	Median_HseHld_Income_Code	Median_HseHld_Income_Description	Income	Income_Code	Income_Description	NetWorth	NetWorth_Code	NetWorth_Description	Millionaire	Unsecured_Credit_Capacity	Unsecured_Credit_Capacity_Code	Unsecured_Credit_Capacity_Description	Discretionary_Income	Discretionary_Income_Code	Discretionary_Income_Description	Donor_Capacity	Donor_Capacity_Code	Donor_Capacity_Description	Investment_Properties_Owned	Estimated_Area_Credit_Rating	CRA_Income_Classification_Code	Credit_Range_New_Credit	Lines_Of_Credit	Home_Property_Type	Home_Property_Type_Detail	Home_Value	Home_Value_Code	Home_Value_Description	Median_Home_Value	Median_Home_Value_Code	Median_Home_Value_Description	Home_Built_Year	Home_Built_Year_Code	Home_Built_Year_Description	Home_Square_Footage	Home_Square_Footage_Range	Land_Square_Footage	Number_Of_Bedrooms	Number_Of_Bathrooms	Home_Air_Conditioning	Home_Swimming_Pool	Home_Sewer	Home_Water	Recent_Home_Buyer	Recent_Mortgage_Borrower	New_Home_Owner_Flag	Most_Recent_Home_Purchase_Date_Flag	Home_Purchase_Date	Home_Purchase_Year	Home_Purchase_Amount	Home_Assessed_Value	Home_Total_Loan	Home_Loan_Date_1_Year	Home_Loan_Date_1_Month	Home_Loan_Date_2_Year	Home_Loan_Date_2_Month	Home_Loan_Date_3_Year	Home_Loan_Date_3_Month	Home_Loan_Amount_1	Home_Loan_Amount_2	Home_Loan_Amount_3	Home_Loan_Type_1	Home_Loan_Type_2	Home_Loan_Type_3	Home_Loan_Interest_Rate_1	Home_Loan_Interest_Rate_2	Home_Loan_Interest_Rate_3	Home_Loan_Interest_Rate_Type_1	Home_Loan_Interest_Rate_Type_2	Home_Loan_Interest_Rate_Type_3	Home_Loan_Transaction_Type_1	Home_Loan_Transaction_Type_2	Home_Loan_Transaction_Type_3	Home_Loan_Lender_Name_1	Home_Loan_Lender_Name_2	Home_Loan_Lender_Name_3	Home_Loan_To_Value_Code	Home_Equity_Available_Code	Home_Equity_Available_Description	Donor_Charitable	Donor_Animal_Welfare	Donor_Arts_Cultural	Donor_Childrens	Donor_Environment_Wildlife	Donor_Health	Donor_International_Aid	Donor_Political	Donor_Political_Conservative	Donor_Political_Liberal	Donor_Religious	Donor_Veterans	CC_American_Express	CC_American_Express_Gold_Platinum	CC_Discover	CC_Visa	CC_Mastercard	CC_Bank	CC_Gas_Dept_Retail	CC_Travel_Entertainment	CC_Unknown	CC_Gold_Platinum	CC_Premium	CC_Upscale_Dept	CC_New_Issue	Home_Living	DIY_Living	Sporty_Living	Upscale_Living	Cultural_Artistic_Living	Highbrow	Common_Living	Professional_Living	Broader_Living	Arts	Theater_Performing_Arts	Food_Wines	Foods_Natural	Cooking_General	Cooking_Gourmet	Aviation	Auto_Work	Automotive_Buff	Beauty_Cosmetics	Career	Career_Improvement	Parenting	Childrens_Interests	Grandchildren	Community_Charities	Religious_Inspirational	Crafts	Photography	Sewing_Knitting_Needlework	Collector_Avid	Collectibles_Grouping	Collectibles_General	Collectibles_Stamps	Collectibles_Coins	Collectibles_Arts	Collectibles_Antiques	Collectibles_Sports_Memorabilia	Education_Online	Exercise_Aerobic	Exercise_Running_Jogging	Exercise_Walking	High_Tech_General	Games_Computer_Games	Games_Video_Games	Games_Board_Puzzles	Gaming_Casino	Consumer_Electronics	Environmental_Issues	Gardening	Home_Furnishings_Decorating	House_Plant	Home_Improvement_Grouping	Home_Improvement	Home_Improvement_DIY	Health_Medical	Dieting_Weight_Loss	Self_Improvement	Investments_Grouping	Investments_Foreign	Investments_Personal	Investments_Real_Estate	Investments_Stocks_Bonds	Money_Seekers	Sweepstakes_Contests	Music_Home_Stereo	Music_Player	Music_Collector	Music_Listener	Movie_Grouping	Movie_Music_General	Movie_Collector	Reading_General	Reading_Audio_Books	Reading_Magazines	Reading_Religious_Inspirational	Reading_Science_Fiction	Reading_Financial_Newsletter_Subscribers	Current_Affairs_Politics	History_Military	Outdoor_Grouping	Outdoor_Enthusiast_General	Outdoor_Fishing	Outdoor_Boating_Sailing	Outdoor_Camping_Hiking	Outdoor_Hunting_Shooting	Outdoor_Scuba_Diving	Spectator_Sports_Grouping	Spectator_Sports_General	Spectator_Sports_Baseball	Spectator_Sports_Basketball	Spectator_Sports_Football	Spectator_Sports_Hockey	Spectator_Sports_Racing	Spectator_Sports_Soccer	Spectator_Sports_TV_Sports	Spectator_NASCAR	Smoking_Tobacco	Sports_Grouping	Sports_Equestrian	Sports_Golf	Sports_Motorcycling	Sports_Skiing	Sports_Tennis	Travel_Grouping	Travel_Cruises	Travel_Domestic	Travel_International	Travel_RV	Science_Space	Woodworking	Buyer_Books	Buyer_Crafts_Hobbies	Buyer_Gardening_Farming	Buyer_Jewelry	Buyer_Luggage	Buyer_Online	Buyer_Membership_Club	Buyer_Merchandise_Male	Buyer_Merchandise_Female	Buyer_Health_Beauty	Buyer_Childrens_Babycare	Buyer_Childrens_Learning_Toys	Buyer_Childrens_Back_To_School	Apparel_Childrens	Apparel_Infant_Toddlers	Apparel_Womens	Apparel_Womens_Petite	Apparel_Womens_Plus_Size	Apparel_Womens_Young	Apparel_Mens	Apparel_Mens_Big_Tall	Apparel_Mens_Young	Auto_Parts_Accessories	Military_Memorabilia_Weapons	Musical_Instruments	Photography_Video_Equipment	Sports_Leisure	Value_Hunter	Last_Update_Date	Source_Data	Production_Date','	')


SELECT CONCAT('CREATE TABLE [dbo].[Quantarium_Houseamp_WA_Select_DemoInd_20210622](
	',STRING_AGG(CONCAT(CAST(QUOTENAME(Field) AS VARCHAR(MAX)), ' VARCHAR(8000)'),',
	') WITHIN GROUP(ORDER BY fieldNum),'
)')
FROM #cols
GO

-- bcp "[Evan].[dbo].[Quantarium_Houseamp_WA_Select_DemoInd_20210622]" in "D:\Temp\Evan\HouseAMP\Quantarium_Houseamp_WA_Select_DemoInd_20210622.txt" -F 2 -c -t \t -S DESKTOP-GU73BTH -a 65535 -T

SELECT CONCAT('SELECT
	',STRING_AGG(CONCAT(CAST(NULL AS VARCHAR(MAX)), 'CASE WHEN TRIM([',Field,']) IN ('''',''NULL'') THEN NULL ELSE TRIM([',Field,']) END AS [',Field,']'),',
	') WITHIN GROUP(ORDER BY fieldNum),'
INTO [dbo].[Quantarium_Houseamp_WA_Select_DemoInd_20210622_New]
FROM [dbo].[Quantarium_Houseamp_WA_Select_DemoInd_20210622]
') AS SQL
FROM #cols
GO



DROP TABLE IF EXISTS [dbo].[Quantarium_Houseamp_WA_Select_DemoInd_20210622]
CREATE TABLE [dbo].[Quantarium_Houseamp_WA_Select_DemoInd_20210622](
	[QId] VARCHAR(8000),
	[DBUSA_Household_ID] VARCHAR(8000),
	[DBUSA_Individual_ID] VARCHAR(8000),
	[Location_ID] VARCHAR(8000),
	[Full_Name] VARCHAR(8000),
	[Name_Prefix] VARCHAR(8000),
	[First_Name] VARCHAR(8000),
	[Middle_Initial] VARCHAR(8000),
	[Last_Name] VARCHAR(8000),
	[Suffix] VARCHAR(8000),
	[Gender] VARCHAR(8000),
	[Date_Of_Birth_Year] VARCHAR(8000),
	[Date_Of_Birth_Month] VARCHAR(8000),
	[Age] VARCHAR(8000),
	[Age_Code_Description] VARCHAR(8000),
	[Ethnic_Code] VARCHAR(8000),
	[Ethnic_Group] VARCHAR(8000),
	[Religious_Affiliation] VARCHAR(8000),
	[Language_Preference] VARCHAR(8000),
	[Hispanic_Country_Of_Origin] VARCHAR(8000),
	[Assimilation_Code] VARCHAR(8000),
	[Education_Individual] VARCHAR(8000),
	[Occupation_Individual] VARCHAR(8000),
	[Occupation_Individual_Range] VARCHAR(8000),
	[Political_Party_Individual] VARCHAR(8000),
	[Political_Ideology] VARCHAR(8000),
	[Voter_ID] VARCHAR(8000),
	[Veteran_Individual] VARCHAR(8000),
	[Mail_Score_Code] VARCHAR(8000),
	[Standardized_Address] VARCHAR(8000),
	[City] VARCHAR(8000),
	[State] VARCHAR(8000),
	[Zip] VARCHAR(8000),
	[ZIP_Plus4] VARCHAR(8000),
	[Carrier_Route] VARCHAR(8000),
	[Delivery_Point] VARCHAR(8000),
	[Delivery_Point_Check_Digit] VARCHAR(8000),
	[Address_Street_Number] VARCHAR(8000),
	[Address_Street_Pre] VARCHAR(8000),
	[Address_Street_Name] VARCHAR(8000),
	[Address_Street_Suffix] VARCHAR(8000),
	[Address_Street_Post] VARCHAR(8000),
	[Address_Suite_Name] VARCHAR(8000),
	[Address_Suite_Number] VARCHAR(8000),
	[Line_Of_Travel] VARCHAR(8000),
	[GeoCode_Match_Level] VARCHAR(8000),
	[Latitude] VARCHAR(8000),
	[Longitude] VARCHAR(8000),
	[Time_Zone_Code] VARCHAR(8000),
	[Time_Zone_Description] VARCHAR(8000),
	[Census_Tract] VARCHAR(8000),
	[Census_Block] VARCHAR(8000),
	[County_Code] VARCHAR(8000),
	[County_Name] VARCHAR(8000),
	[FIPS_Code] VARCHAR(8000),
	[CBSA_Code] VARCHAR(8000),
	[CBSA_Description] VARCHAR(8000),
	[Walk_Sequence] VARCHAR(8000),
	[District_Congressional] VARCHAR(8000),
	[District_State_Senate] VARCHAR(8000),
	[District_State_House] VARCHAR(8000),
	[District_State_Legislative] VARCHAR(8000),
	[DMA_Code] VARCHAR(8000),
	[DMA_Zone] VARCHAR(8000),
	[Email_Present] VARCHAR(8000),
	[Email] VARCHAR(8000),
	[Email_02] VARCHAR(8000),
	[Email_03] VARCHAR(8000),
	[Email_04] VARCHAR(8000),
	[Email_05] VARCHAR(8000),
	[Area_Code] VARCHAR(8000),
	[Phone] VARCHAR(8000),
	[DNC] VARCHAR(8000),
	[Scrubbed_Phoneable] VARCHAR(8000),
	[Area_Code_Cell_Phone] VARCHAR(8000),
	[Cell_Phone] VARCHAR(8000),
	[Dwelling_Type] VARCHAR(8000),
	[Home_Owner_Renter] VARCHAR(8000),
	[Length_Of_Residence] VARCHAR(8000),
	[Length_of_Residence_Code] VARCHAR(8000),
	[Length_Of_Residence_Description] VARCHAR(8000),
	[Recently_Moved_Flag] VARCHAR(8000),
	[Recently_Moved_Year] VARCHAR(8000),
	[Recently_Moved_Month] VARCHAR(8000),
	[Household_Size] VARCHAR(8000),
	[Household_Rank] VARCHAR(8000),
	[Number_Of_Adults] VARCHAR(8000),
	[Young_Adult_In_Household] VARCHAR(8000),
	[Senior_Adult_In_Household] VARCHAR(8000),
	[Generations_In_Household] VARCHAR(8000),
	[Marital_Status] VARCHAR(8000),
	[Recent_Divorce] VARCHAR(8000),
	[Single_Parent] VARCHAR(8000),
	[Children_Present] VARCHAR(8000),
	[Number_Children] VARCHAR(8000),
	[Childrens_Age_00_02] VARCHAR(8000),
	[Childrens_Age_00_02_Male] VARCHAR(8000),
	[Childrens_Age_00_02_Female] VARCHAR(8000),
	[Childrens_Age_00_02_Unknown] VARCHAR(8000),
	[Childrens_Age_03_05] VARCHAR(8000),
	[Childrens_Age_03_05_Male] VARCHAR(8000),
	[Childrens_Age_03_05_Female] VARCHAR(8000),
	[Childrens_Age_03_05_Unknown] VARCHAR(8000),
	[Childrens_Age_06_10] VARCHAR(8000),
	[Childrens_Age_06_10_Male] VARCHAR(8000),
	[Childrens_Age_06_10_Female] VARCHAR(8000),
	[Childrens_Age_06_10_Unknown] VARCHAR(8000),
	[Childrens_Age_11_15] VARCHAR(8000),
	[Childrens_Age_11_15_Male] VARCHAR(8000),
	[Childrens_Age_11_15_Female] VARCHAR(8000),
	[Childrens_Age_11_15_Unknown] VARCHAR(8000),
	[Childrens_Age_16_17] VARCHAR(8000),
	[Childrens_Age_16_17_Male] VARCHAR(8000),
	[Childrens_Age_16_17_Female] VARCHAR(8000),
	[Childrens_Age_16_17_Unknown] VARCHAR(8000),
	[Child_Near_High_School_Graduation] VARCHAR(8000),
	[College_Graduate] VARCHAR(8000),
	[Christian_Families] VARCHAR(8000),
	[Business_Owner] VARCHAR(8000),
	[SOHO] VARCHAR(8000),
	[Working_Woman] VARCHAR(8000),
	[Veteran_Present_In_Household] VARCHAR(8000),
	[Credit_Card_User] VARCHAR(8000),
	[Mail_Order_Donor] VARCHAR(8000),
	[Mail_Order_Buyer] VARCHAR(8000),
	[Mail_Order_Responder] VARCHAR(8000),
	[TV_Satellite_Dish] VARCHAR(8000),
	[Pet_Owner] VARCHAR(8000),
	[Cat_Owner] VARCHAR(8000),
	[Dog_Owner] VARCHAR(8000),
	[Other_Pet_Owner] VARCHAR(8000),
	[New_Teen_Driver] VARCHAR(8000),
	[New_Teen_Driver_Gender] VARCHAR(8000),
	[Boat_Owner] VARCHAR(8000),
	[Truck_Owner] VARCHAR(8000),
	[Motorcycle_Owner] VARCHAR(8000),
	[RV_Owner] VARCHAR(8000),
	[Auto_Buy_New] VARCHAR(8000),
	[Auto_Buy_Used] VARCHAR(8000),
	[Auto_Buy_Used_5_Months_Or_Less] VARCHAR(8000),
	[Auto_Buy_Used_6_Months_Or_More] VARCHAR(8000),
	[Median_HseHld_Income] VARCHAR(8000),
	[Median_HseHld_Income_Code] VARCHAR(8000),
	[Median_HseHld_Income_Description] VARCHAR(8000),
	[Income] VARCHAR(8000),
	[Income_Code] VARCHAR(8000),
	[Income_Description] VARCHAR(8000),
	[NetWorth] VARCHAR(8000),
	[NetWorth_Code] VARCHAR(8000),
	[NetWorth_Description] VARCHAR(8000),
	[Millionaire] VARCHAR(8000),
	[Unsecured_Credit_Capacity] VARCHAR(8000),
	[Unsecured_Credit_Capacity_Code] VARCHAR(8000),
	[Unsecured_Credit_Capacity_Description] VARCHAR(8000),
	[Discretionary_Income] VARCHAR(8000),
	[Discretionary_Income_Code] VARCHAR(8000),
	[Discretionary_Income_Description] VARCHAR(8000),
	[Donor_Capacity] VARCHAR(8000),
	[Donor_Capacity_Code] VARCHAR(8000),
	[Donor_Capacity_Description] VARCHAR(8000),
	[Investment_Properties_Owned] VARCHAR(8000),
	[Estimated_Area_Credit_Rating] VARCHAR(8000),
	[CRA_Income_Classification_Code] VARCHAR(8000),
	[Credit_Range_New_Credit] VARCHAR(8000),
	[Lines_Of_Credit] VARCHAR(8000),
	[Home_Property_Type] VARCHAR(8000),
	[Home_Property_Type_Detail] VARCHAR(8000),
	[Home_Value] VARCHAR(8000),
	[Home_Value_Code] VARCHAR(8000),
	[Home_Value_Description] VARCHAR(8000),
	[Median_Home_Value] VARCHAR(8000),
	[Median_Home_Value_Code] VARCHAR(8000),
	[Median_Home_Value_Description] VARCHAR(8000),
	[Home_Built_Year] VARCHAR(8000),
	[Home_Built_Year_Code] VARCHAR(8000),
	[Home_Built_Year_Description] VARCHAR(8000),
	[Home_Square_Footage] VARCHAR(8000),
	[Home_Square_Footage_Range] VARCHAR(8000),
	[Land_Square_Footage] VARCHAR(8000),
	[Number_Of_Bedrooms] VARCHAR(8000),
	[Number_Of_Bathrooms] VARCHAR(8000),
	[Home_Air_Conditioning] VARCHAR(8000),
	[Home_Swimming_Pool] VARCHAR(8000),
	[Home_Sewer] VARCHAR(8000),
	[Home_Water] VARCHAR(8000),
	[Recent_Home_Buyer] VARCHAR(8000),
	[Recent_Mortgage_Borrower] VARCHAR(8000),
	[New_Home_Owner_Flag] VARCHAR(8000),
	[Most_Recent_Home_Purchase_Date_Flag] VARCHAR(8000),
	[Home_Purchase_Date] VARCHAR(8000),
	[Home_Purchase_Year] VARCHAR(8000),
	[Home_Purchase_Amount] VARCHAR(8000),
	[Home_Assessed_Value] VARCHAR(8000),
	[Home_Total_Loan] VARCHAR(8000),
	[Home_Loan_Date_1_Year] VARCHAR(8000),
	[Home_Loan_Date_1_Month] VARCHAR(8000),
	[Home_Loan_Date_2_Year] VARCHAR(8000),
	[Home_Loan_Date_2_Month] VARCHAR(8000),
	[Home_Loan_Date_3_Year] VARCHAR(8000),
	[Home_Loan_Date_3_Month] VARCHAR(8000),
	[Home_Loan_Amount_1] VARCHAR(8000),
	[Home_Loan_Amount_2] VARCHAR(8000),
	[Home_Loan_Amount_3] VARCHAR(8000),
	[Home_Loan_Type_1] VARCHAR(8000),
	[Home_Loan_Type_2] VARCHAR(8000),
	[Home_Loan_Type_3] VARCHAR(8000),
	[Home_Loan_Interest_Rate_1] VARCHAR(8000),
	[Home_Loan_Interest_Rate_2] VARCHAR(8000),
	[Home_Loan_Interest_Rate_3] VARCHAR(8000),
	[Home_Loan_Interest_Rate_Type_1] VARCHAR(8000),
	[Home_Loan_Interest_Rate_Type_2] VARCHAR(8000),
	[Home_Loan_Interest_Rate_Type_3] VARCHAR(8000),
	[Home_Loan_Transaction_Type_1] VARCHAR(8000),
	[Home_Loan_Transaction_Type_2] VARCHAR(8000),
	[Home_Loan_Transaction_Type_3] VARCHAR(8000),
	[Home_Loan_Lender_Name_1] VARCHAR(8000),
	[Home_Loan_Lender_Name_2] VARCHAR(8000),
	[Home_Loan_Lender_Name_3] VARCHAR(8000),
	[Home_Loan_To_Value_Code] VARCHAR(8000),
	[Home_Equity_Available_Code] VARCHAR(8000),
	[Home_Equity_Available_Description] VARCHAR(8000),
	[Donor_Charitable] VARCHAR(8000),
	[Donor_Animal_Welfare] VARCHAR(8000),
	[Donor_Arts_Cultural] VARCHAR(8000),
	[Donor_Childrens] VARCHAR(8000),
	[Donor_Environment_Wildlife] VARCHAR(8000),
	[Donor_Health] VARCHAR(8000),
	[Donor_International_Aid] VARCHAR(8000),
	[Donor_Political] VARCHAR(8000),
	[Donor_Political_Conservative] VARCHAR(8000),
	[Donor_Political_Liberal] VARCHAR(8000),
	[Donor_Religious] VARCHAR(8000),
	[Donor_Veterans] VARCHAR(8000),
	[CC_American_Express] VARCHAR(8000),
	[CC_American_Express_Gold_Platinum] VARCHAR(8000),
	[CC_Discover] VARCHAR(8000),
	[CC_Visa] VARCHAR(8000),
	[CC_Mastercard] VARCHAR(8000),
	[CC_Bank] VARCHAR(8000),
	[CC_Gas_Dept_Retail] VARCHAR(8000),
	[CC_Travel_Entertainment] VARCHAR(8000),
	[CC_Unknown] VARCHAR(8000),
	[CC_Gold_Platinum] VARCHAR(8000),
	[CC_Premium] VARCHAR(8000),
	[CC_Upscale_Dept] VARCHAR(8000),
	[CC_New_Issue] VARCHAR(8000),
	[Home_Living] VARCHAR(8000),
	[DIY_Living] VARCHAR(8000),
	[Sporty_Living] VARCHAR(8000),
	[Upscale_Living] VARCHAR(8000),
	[Cultural_Artistic_Living] VARCHAR(8000),
	[Highbrow] VARCHAR(8000),
	[Common_Living] VARCHAR(8000),
	[Professional_Living] VARCHAR(8000),
	[Broader_Living] VARCHAR(8000),
	[Arts] VARCHAR(8000),
	[Theater_Performing_Arts] VARCHAR(8000),
	[Food_Wines] VARCHAR(8000),
	[Foods_Natural] VARCHAR(8000),
	[Cooking_General] VARCHAR(8000),
	[Cooking_Gourmet] VARCHAR(8000),
	[Aviation] VARCHAR(8000),
	[Auto_Work] VARCHAR(8000),
	[Automotive_Buff] VARCHAR(8000),
	[Beauty_Cosmetics] VARCHAR(8000),
	[Career] VARCHAR(8000),
	[Career_Improvement] VARCHAR(8000),
	[Parenting] VARCHAR(8000),
	[Childrens_Interests] VARCHAR(8000),
	[Grandchildren] VARCHAR(8000),
	[Community_Charities] VARCHAR(8000),
	[Religious_Inspirational] VARCHAR(8000),
	[Crafts] VARCHAR(8000),
	[Photography] VARCHAR(8000),
	[Sewing_Knitting_Needlework] VARCHAR(8000),
	[Collector_Avid] VARCHAR(8000),
	[Collectibles_Grouping] VARCHAR(8000),
	[Collectibles_General] VARCHAR(8000),
	[Collectibles_Stamps] VARCHAR(8000),
	[Collectibles_Coins] VARCHAR(8000),
	[Collectibles_Arts] VARCHAR(8000),
	[Collectibles_Antiques] VARCHAR(8000),
	[Collectibles_Sports_Memorabilia] VARCHAR(8000),
	[Education_Online] VARCHAR(8000),
	[Exercise_Aerobic] VARCHAR(8000),
	[Exercise_Running_Jogging] VARCHAR(8000),
	[Exercise_Walking] VARCHAR(8000),
	[High_Tech_General] VARCHAR(8000),
	[Games_Computer_Games] VARCHAR(8000),
	[Games_Video_Games] VARCHAR(8000),
	[Games_Board_Puzzles] VARCHAR(8000),
	[Gaming_Casino] VARCHAR(8000),
	[Consumer_Electronics] VARCHAR(8000),
	[Environmental_Issues] VARCHAR(8000),
	[Gardening] VARCHAR(8000),
	[Home_Furnishings_Decorating] VARCHAR(8000),
	[House_Plant] VARCHAR(8000),
	[Home_Improvement_Grouping] VARCHAR(8000),
	[Home_Improvement] VARCHAR(8000),
	[Home_Improvement_DIY] VARCHAR(8000),
	[Health_Medical] VARCHAR(8000),
	[Dieting_Weight_Loss] VARCHAR(8000),
	[Self_Improvement] VARCHAR(8000),
	[Investments_Grouping] VARCHAR(8000),
	[Investments_Foreign] VARCHAR(8000),
	[Investments_Personal] VARCHAR(8000),
	[Investments_Real_Estate] VARCHAR(8000),
	[Investments_Stocks_Bonds] VARCHAR(8000),
	[Money_Seekers] VARCHAR(8000),
	[Sweepstakes_Contests] VARCHAR(8000),
	[Music_Home_Stereo] VARCHAR(8000),
	[Music_Player] VARCHAR(8000),
	[Music_Collector] VARCHAR(8000),
	[Music_Listener] VARCHAR(8000),
	[Movie_Grouping] VARCHAR(8000),
	[Movie_Music_General] VARCHAR(8000),
	[Movie_Collector] VARCHAR(8000),
	[Reading_General] VARCHAR(8000),
	[Reading_Audio_Books] VARCHAR(8000),
	[Reading_Magazines] VARCHAR(8000),
	[Reading_Religious_Inspirational] VARCHAR(8000),
	[Reading_Science_Fiction] VARCHAR(8000),
	[Reading_Financial_Newsletter_Subscribers] VARCHAR(8000),
	[Current_Affairs_Politics] VARCHAR(8000),
	[History_Military] VARCHAR(8000),
	[Outdoor_Grouping] VARCHAR(8000),
	[Outdoor_Enthusiast_General] VARCHAR(8000),
	[Outdoor_Fishing] VARCHAR(8000),
	[Outdoor_Boating_Sailing] VARCHAR(8000),
	[Outdoor_Camping_Hiking] VARCHAR(8000),
	[Outdoor_Hunting_Shooting] VARCHAR(8000),
	[Outdoor_Scuba_Diving] VARCHAR(8000),
	[Spectator_Sports_Grouping] VARCHAR(8000),
	[Spectator_Sports_General] VARCHAR(8000),
	[Spectator_Sports_Baseball] VARCHAR(8000),
	[Spectator_Sports_Basketball] VARCHAR(8000),
	[Spectator_Sports_Football] VARCHAR(8000),
	[Spectator_Sports_Hockey] VARCHAR(8000),
	[Spectator_Sports_Racing] VARCHAR(8000),
	[Spectator_Sports_Soccer] VARCHAR(8000),
	[Spectator_Sports_TV_Sports] VARCHAR(8000),
	[Spectator_NASCAR] VARCHAR(8000),
	[Smoking_Tobacco] VARCHAR(8000),
	[Sports_Grouping] VARCHAR(8000),
	[Sports_Equestrian] VARCHAR(8000),
	[Sports_Golf] VARCHAR(8000),
	[Sports_Motorcycling] VARCHAR(8000),
	[Sports_Skiing] VARCHAR(8000),
	[Sports_Tennis] VARCHAR(8000),
	[Travel_Grouping] VARCHAR(8000),
	[Travel_Cruises] VARCHAR(8000),
	[Travel_Domestic] VARCHAR(8000),
	[Travel_International] VARCHAR(8000),
	[Travel_RV] VARCHAR(8000),
	[Science_Space] VARCHAR(8000),
	[Woodworking] VARCHAR(8000),
	[Buyer_Books] VARCHAR(8000),
	[Buyer_Crafts_Hobbies] VARCHAR(8000),
	[Buyer_Gardening_Farming] VARCHAR(8000),
	[Buyer_Jewelry] VARCHAR(8000),
	[Buyer_Luggage] VARCHAR(8000),
	[Buyer_Online] VARCHAR(8000),
	[Buyer_Membership_Club] VARCHAR(8000),
	[Buyer_Merchandise_Male] VARCHAR(8000),
	[Buyer_Merchandise_Female] VARCHAR(8000),
	[Buyer_Health_Beauty] VARCHAR(8000),
	[Buyer_Childrens_Babycare] VARCHAR(8000),
	[Buyer_Childrens_Learning_Toys] VARCHAR(8000),
	[Buyer_Childrens_Back_To_School] VARCHAR(8000),
	[Apparel_Childrens] VARCHAR(8000),
	[Apparel_Infant_Toddlers] VARCHAR(8000),
	[Apparel_Womens] VARCHAR(8000),
	[Apparel_Womens_Petite] VARCHAR(8000),
	[Apparel_Womens_Plus_Size] VARCHAR(8000),
	[Apparel_Womens_Young] VARCHAR(8000),
	[Apparel_Mens] VARCHAR(8000),
	[Apparel_Mens_Big_Tall] VARCHAR(8000),
	[Apparel_Mens_Young] VARCHAR(8000),
	[Auto_Parts_Accessories] VARCHAR(8000),
	[Military_Memorabilia_Weapons] VARCHAR(8000),
	[Musical_Instruments] VARCHAR(8000),
	[Photography_Video_Equipment] VARCHAR(8000),
	[Sports_Leisure] VARCHAR(8000),
	[Value_Hunter] VARCHAR(8000),
	[Last_Update_Date] VARCHAR(8000),
	[Source_Data] VARCHAR(8000),
	[Production_Date] VARCHAR(8000)
)





SELECT
	CASE WHEN TRIM([QId]) IN ('','NULL') THEN NULL ELSE TRIM([QId]) END AS [QId],
	CASE WHEN TRIM([DBUSA_Household_ID]) IN ('','NULL') THEN NULL ELSE TRIM([DBUSA_Household_ID]) END AS [DBUSA_Household_ID],
	CASE WHEN TRIM([DBUSA_Individual_ID]) IN ('','NULL') THEN NULL ELSE TRIM([DBUSA_Individual_ID]) END AS [DBUSA_Individual_ID],
	CASE WHEN TRIM([Location_ID]) IN ('','NULL') THEN NULL ELSE TRIM([Location_ID]) END AS [Location_ID],
	CASE WHEN TRIM([Full_Name]) IN ('','NULL') THEN NULL ELSE TRIM([Full_Name]) END AS [Full_Name],
	CASE WHEN TRIM([Name_Prefix]) IN ('','NULL') THEN NULL ELSE TRIM([Name_Prefix]) END AS [Name_Prefix],
	CASE WHEN TRIM([First_Name]) IN ('','NULL') THEN NULL ELSE TRIM([First_Name]) END AS [First_Name],
	CASE WHEN TRIM([Middle_Initial]) IN ('','NULL') THEN NULL ELSE TRIM([Middle_Initial]) END AS [Middle_Initial],
	CASE WHEN TRIM([Last_Name]) IN ('','NULL') THEN NULL ELSE TRIM([Last_Name]) END AS [Last_Name],
	CASE WHEN TRIM([Suffix]) IN ('','NULL') THEN NULL ELSE TRIM([Suffix]) END AS [Suffix],
	CASE WHEN TRIM([Gender]) IN ('','NULL') THEN NULL ELSE TRIM([Gender]) END AS [Gender],
	CASE WHEN TRIM([Date_Of_Birth_Year]) IN ('','NULL') THEN NULL ELSE TRIM([Date_Of_Birth_Year]) END AS [Date_Of_Birth_Year],
	CASE WHEN TRIM([Date_Of_Birth_Month]) IN ('','NULL') THEN NULL ELSE TRIM([Date_Of_Birth_Month]) END AS [Date_Of_Birth_Month],
	CASE WHEN TRIM([Age]) IN ('','NULL') THEN NULL ELSE TRIM([Age]) END AS [Age],
	CASE WHEN TRIM([Age_Code_Description]) IN ('','NULL') THEN NULL ELSE TRIM([Age_Code_Description]) END AS [Age_Code_Description],
	CASE WHEN TRIM([Ethnic_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Ethnic_Code]) END AS [Ethnic_Code],
	CASE WHEN TRIM([Ethnic_Group]) IN ('','NULL') THEN NULL ELSE TRIM([Ethnic_Group]) END AS [Ethnic_Group],
	CASE WHEN TRIM([Religious_Affiliation]) IN ('','NULL') THEN NULL ELSE TRIM([Religious_Affiliation]) END AS [Religious_Affiliation],
	CASE WHEN TRIM([Language_Preference]) IN ('','NULL') THEN NULL ELSE TRIM([Language_Preference]) END AS [Language_Preference],
	CASE WHEN TRIM([Hispanic_Country_Of_Origin]) IN ('','NULL') THEN NULL ELSE TRIM([Hispanic_Country_Of_Origin]) END AS [Hispanic_Country_Of_Origin],
	CASE WHEN TRIM([Assimilation_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Assimilation_Code]) END AS [Assimilation_Code],
	CASE WHEN TRIM([Education_Individual]) IN ('','NULL') THEN NULL ELSE TRIM([Education_Individual]) END AS [Education_Individual],
	CASE WHEN TRIM([Occupation_Individual]) IN ('','NULL') THEN NULL ELSE TRIM([Occupation_Individual]) END AS [Occupation_Individual],
	CASE WHEN TRIM([Occupation_Individual_Range]) IN ('','NULL') THEN NULL ELSE TRIM([Occupation_Individual_Range]) END AS [Occupation_Individual_Range],
	CASE WHEN TRIM([Political_Party_Individual]) IN ('','NULL') THEN NULL ELSE TRIM([Political_Party_Individual]) END AS [Political_Party_Individual],
	CASE WHEN TRIM([Political_Ideology]) IN ('','NULL') THEN NULL ELSE TRIM([Political_Ideology]) END AS [Political_Ideology],
	CASE WHEN TRIM([Voter_ID]) IN ('','NULL') THEN NULL ELSE TRIM([Voter_ID]) END AS [Voter_ID],
	CASE WHEN TRIM([Veteran_Individual]) IN ('','NULL') THEN NULL ELSE TRIM([Veteran_Individual]) END AS [Veteran_Individual],
	CASE WHEN TRIM([Mail_Score_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Mail_Score_Code]) END AS [Mail_Score_Code],
	CASE WHEN TRIM([Standardized_Address]) IN ('','NULL') THEN NULL ELSE TRIM([Standardized_Address]) END AS [Standardized_Address],
	CASE WHEN TRIM([City]) IN ('','NULL') THEN NULL ELSE TRIM([City]) END AS [City],
	CASE WHEN TRIM([State]) IN ('','NULL') THEN NULL ELSE TRIM([State]) END AS [State],
	CASE WHEN TRIM([Zip]) IN ('','NULL') THEN NULL ELSE TRIM([Zip]) END AS [Zip],
	CASE WHEN TRIM([ZIP_Plus4]) IN ('','NULL') THEN NULL ELSE TRIM([ZIP_Plus4]) END AS [ZIP_Plus4],
	CASE WHEN TRIM([Carrier_Route]) IN ('','NULL') THEN NULL ELSE TRIM([Carrier_Route]) END AS [Carrier_Route],
	CASE WHEN TRIM([Delivery_Point]) IN ('','NULL') THEN NULL ELSE TRIM([Delivery_Point]) END AS [Delivery_Point],
	CASE WHEN TRIM([Delivery_Point_Check_Digit]) IN ('','NULL') THEN NULL ELSE TRIM([Delivery_Point_Check_Digit]) END AS [Delivery_Point_Check_Digit],
	CASE WHEN TRIM([Address_Street_Number]) IN ('','NULL') THEN NULL ELSE TRIM([Address_Street_Number]) END AS [Address_Street_Number],
	CASE WHEN TRIM([Address_Street_Pre]) IN ('','NULL') THEN NULL ELSE TRIM([Address_Street_Pre]) END AS [Address_Street_Pre],
	CASE WHEN TRIM([Address_Street_Name]) IN ('','NULL') THEN NULL ELSE TRIM([Address_Street_Name]) END AS [Address_Street_Name],
	CASE WHEN TRIM([Address_Street_Suffix]) IN ('','NULL') THEN NULL ELSE TRIM([Address_Street_Suffix]) END AS [Address_Street_Suffix],
	CASE WHEN TRIM([Address_Street_Post]) IN ('','NULL') THEN NULL ELSE TRIM([Address_Street_Post]) END AS [Address_Street_Post],
	CASE WHEN TRIM([Address_Suite_Name]) IN ('','NULL') THEN NULL ELSE TRIM([Address_Suite_Name]) END AS [Address_Suite_Name],
	CASE WHEN TRIM([Address_Suite_Number]) IN ('','NULL') THEN NULL ELSE TRIM([Address_Suite_Number]) END AS [Address_Suite_Number],
	CASE WHEN TRIM([Line_Of_Travel]) IN ('','NULL') THEN NULL ELSE TRIM([Line_Of_Travel]) END AS [Line_Of_Travel],
	CASE WHEN TRIM([GeoCode_Match_Level]) IN ('','NULL') THEN NULL ELSE TRIM([GeoCode_Match_Level]) END AS [GeoCode_Match_Level],
	CASE WHEN TRIM([Latitude]) IN ('','NULL') THEN NULL ELSE TRIM([Latitude]) END AS [Latitude],
	CASE WHEN TRIM([Longitude]) IN ('','NULL') THEN NULL ELSE TRIM([Longitude]) END AS [Longitude],
	CASE WHEN TRIM([Time_Zone_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Time_Zone_Code]) END AS [Time_Zone_Code],
	CASE WHEN TRIM([Time_Zone_Description]) IN ('','NULL') THEN NULL ELSE TRIM([Time_Zone_Description]) END AS [Time_Zone_Description],
	CASE WHEN TRIM([Census_Tract]) IN ('','NULL') THEN NULL ELSE TRIM([Census_Tract]) END AS [Census_Tract],
	CASE WHEN TRIM([Census_Block]) IN ('','NULL') THEN NULL ELSE TRIM([Census_Block]) END AS [Census_Block],
	CASE WHEN TRIM([County_Code]) IN ('','NULL') THEN NULL ELSE TRIM([County_Code]) END AS [County_Code],
	CASE WHEN TRIM([County_Name]) IN ('','NULL') THEN NULL ELSE TRIM([County_Name]) END AS [County_Name],
	CASE WHEN TRIM([FIPS_Code]) IN ('','NULL') THEN NULL ELSE TRIM([FIPS_Code]) END AS [FIPS_Code],
	CASE WHEN TRIM([CBSA_Code]) IN ('','NULL') THEN NULL ELSE TRIM([CBSA_Code]) END AS [CBSA_Code],
	CASE WHEN TRIM([CBSA_Description]) IN ('','NULL') THEN NULL ELSE TRIM([CBSA_Description]) END AS [CBSA_Description],
	CASE WHEN TRIM([Walk_Sequence]) IN ('','NULL') THEN NULL ELSE TRIM([Walk_Sequence]) END AS [Walk_Sequence],
	CASE WHEN TRIM([District_Congressional]) IN ('','NULL') THEN NULL ELSE TRIM([District_Congressional]) END AS [District_Congressional],
	CASE WHEN TRIM([District_State_Senate]) IN ('','NULL') THEN NULL ELSE TRIM([District_State_Senate]) END AS [District_State_Senate],
	CASE WHEN TRIM([District_State_House]) IN ('','NULL') THEN NULL ELSE TRIM([District_State_House]) END AS [District_State_House],
	CASE WHEN TRIM([District_State_Legislative]) IN ('','NULL') THEN NULL ELSE TRIM([District_State_Legislative]) END AS [District_State_Legislative],
	CASE WHEN TRIM([DMA_Code]) IN ('','NULL') THEN NULL ELSE TRIM([DMA_Code]) END AS [DMA_Code],
	CASE WHEN TRIM([DMA_Zone]) IN ('','NULL') THEN NULL ELSE TRIM([DMA_Zone]) END AS [DMA_Zone],
	CASE WHEN TRIM([Email_Present]) IN ('','NULL') THEN NULL ELSE TRIM([Email_Present]) END AS [Email_Present],
	CASE WHEN TRIM([Email]) IN ('','NULL') THEN NULL ELSE TRIM([Email]) END AS [Email],
	CASE WHEN TRIM([Email_02]) IN ('','NULL') THEN NULL ELSE TRIM([Email_02]) END AS [Email_02],
	CASE WHEN TRIM([Email_03]) IN ('','NULL') THEN NULL ELSE TRIM([Email_03]) END AS [Email_03],
	CASE WHEN TRIM([Email_04]) IN ('','NULL') THEN NULL ELSE TRIM([Email_04]) END AS [Email_04],
	CASE WHEN TRIM([Email_05]) IN ('','NULL') THEN NULL ELSE TRIM([Email_05]) END AS [Email_05],
	CASE WHEN TRIM([Area_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Area_Code]) END AS [Area_Code],
	CASE WHEN TRIM([Phone]) IN ('','NULL') THEN NULL ELSE TRIM([Phone]) END AS [Phone],
	CASE WHEN TRIM([DNC]) IN ('','NULL') THEN NULL ELSE TRIM([DNC]) END AS [DNC],
	CASE WHEN TRIM([Scrubbed_Phoneable]) IN ('','NULL') THEN NULL ELSE TRIM([Scrubbed_Phoneable]) END AS [Scrubbed_Phoneable],
	CASE WHEN TRIM([Area_Code_Cell_Phone]) IN ('','NULL') THEN NULL ELSE TRIM([Area_Code_Cell_Phone]) END AS [Area_Code_Cell_Phone],
	CASE WHEN TRIM([Cell_Phone]) IN ('','NULL') THEN NULL ELSE TRIM([Cell_Phone]) END AS [Cell_Phone],
	CASE WHEN TRIM([Dwelling_Type]) IN ('','NULL') THEN NULL ELSE TRIM([Dwelling_Type]) END AS [Dwelling_Type],
	CASE WHEN TRIM([Home_Owner_Renter]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Owner_Renter]) END AS [Home_Owner_Renter],
	CASE WHEN TRIM([Length_Of_Residence]) IN ('','NULL') THEN NULL ELSE TRIM([Length_Of_Residence]) END AS [Length_Of_Residence],
	CASE WHEN TRIM([Length_of_Residence_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Length_of_Residence_Code]) END AS [Length_of_Residence_Code],
	CASE WHEN TRIM([Length_Of_Residence_Description]) IN ('','NULL') THEN NULL ELSE TRIM([Length_Of_Residence_Description]) END AS [Length_Of_Residence_Description],
	CASE WHEN TRIM([Recently_Moved_Flag]) IN ('','NULL') THEN NULL ELSE TRIM([Recently_Moved_Flag]) END AS [Recently_Moved_Flag],
	CASE WHEN TRIM([Recently_Moved_Year]) IN ('','NULL') THEN NULL ELSE TRIM([Recently_Moved_Year]) END AS [Recently_Moved_Year],
	CASE WHEN TRIM([Recently_Moved_Month]) IN ('','NULL') THEN NULL ELSE TRIM([Recently_Moved_Month]) END AS [Recently_Moved_Month],
	CASE WHEN TRIM([Household_Size]) IN ('','NULL') THEN NULL ELSE TRIM([Household_Size]) END AS [Household_Size],
	CASE WHEN TRIM([Household_Rank]) IN ('','NULL') THEN NULL ELSE TRIM([Household_Rank]) END AS [Household_Rank],
	CASE WHEN TRIM([Number_Of_Adults]) IN ('','NULL') THEN NULL ELSE TRIM([Number_Of_Adults]) END AS [Number_Of_Adults],
	CASE WHEN TRIM([Young_Adult_In_Household]) IN ('','NULL') THEN NULL ELSE TRIM([Young_Adult_In_Household]) END AS [Young_Adult_In_Household],
	CASE WHEN TRIM([Senior_Adult_In_Household]) IN ('','NULL') THEN NULL ELSE TRIM([Senior_Adult_In_Household]) END AS [Senior_Adult_In_Household],
	CASE WHEN TRIM([Generations_In_Household]) IN ('','NULL') THEN NULL ELSE TRIM([Generations_In_Household]) END AS [Generations_In_Household],
	CASE WHEN TRIM([Marital_Status]) IN ('','NULL') THEN NULL ELSE TRIM([Marital_Status]) END AS [Marital_Status],
	CASE WHEN TRIM([Recent_Divorce]) IN ('','NULL') THEN NULL ELSE TRIM([Recent_Divorce]) END AS [Recent_Divorce],
	CASE WHEN TRIM([Single_Parent]) IN ('','NULL') THEN NULL ELSE TRIM([Single_Parent]) END AS [Single_Parent],
	CASE WHEN TRIM([Children_Present]) IN ('','NULL') THEN NULL ELSE TRIM([Children_Present]) END AS [Children_Present],
	CASE WHEN TRIM([Number_Children]) IN ('','NULL') THEN NULL ELSE TRIM([Number_Children]) END AS [Number_Children],
	CASE WHEN TRIM([Childrens_Age_00_02]) IN ('','NULL') THEN NULL ELSE TRIM([Childrens_Age_00_02]) END AS [Childrens_Age_00_02],
	CASE WHEN TRIM([Childrens_Age_00_02_Male]) IN ('','NULL') THEN NULL ELSE TRIM([Childrens_Age_00_02_Male]) END AS [Childrens_Age_00_02_Male],
	CASE WHEN TRIM([Childrens_Age_00_02_Female]) IN ('','NULL') THEN NULL ELSE TRIM([Childrens_Age_00_02_Female]) END AS [Childrens_Age_00_02_Female],
	CASE WHEN TRIM([Childrens_Age_00_02_Unknown]) IN ('','NULL') THEN NULL ELSE TRIM([Childrens_Age_00_02_Unknown]) END AS [Childrens_Age_00_02_Unknown],
	CASE WHEN TRIM([Childrens_Age_03_05]) IN ('','NULL') THEN NULL ELSE TRIM([Childrens_Age_03_05]) END AS [Childrens_Age_03_05],
	CASE WHEN TRIM([Childrens_Age_03_05_Male]) IN ('','NULL') THEN NULL ELSE TRIM([Childrens_Age_03_05_Male]) END AS [Childrens_Age_03_05_Male],
	CASE WHEN TRIM([Childrens_Age_03_05_Female]) IN ('','NULL') THEN NULL ELSE TRIM([Childrens_Age_03_05_Female]) END AS [Childrens_Age_03_05_Female],
	CASE WHEN TRIM([Childrens_Age_03_05_Unknown]) IN ('','NULL') THEN NULL ELSE TRIM([Childrens_Age_03_05_Unknown]) END AS [Childrens_Age_03_05_Unknown],
	CASE WHEN TRIM([Childrens_Age_06_10]) IN ('','NULL') THEN NULL ELSE TRIM([Childrens_Age_06_10]) END AS [Childrens_Age_06_10],
	CASE WHEN TRIM([Childrens_Age_06_10_Male]) IN ('','NULL') THEN NULL ELSE TRIM([Childrens_Age_06_10_Male]) END AS [Childrens_Age_06_10_Male],
	CASE WHEN TRIM([Childrens_Age_06_10_Female]) IN ('','NULL') THEN NULL ELSE TRIM([Childrens_Age_06_10_Female]) END AS [Childrens_Age_06_10_Female],
	CASE WHEN TRIM([Childrens_Age_06_10_Unknown]) IN ('','NULL') THEN NULL ELSE TRIM([Childrens_Age_06_10_Unknown]) END AS [Childrens_Age_06_10_Unknown],
	CASE WHEN TRIM([Childrens_Age_11_15]) IN ('','NULL') THEN NULL ELSE TRIM([Childrens_Age_11_15]) END AS [Childrens_Age_11_15],
	CASE WHEN TRIM([Childrens_Age_11_15_Male]) IN ('','NULL') THEN NULL ELSE TRIM([Childrens_Age_11_15_Male]) END AS [Childrens_Age_11_15_Male],
	CASE WHEN TRIM([Childrens_Age_11_15_Female]) IN ('','NULL') THEN NULL ELSE TRIM([Childrens_Age_11_15_Female]) END AS [Childrens_Age_11_15_Female],
	CASE WHEN TRIM([Childrens_Age_11_15_Unknown]) IN ('','NULL') THEN NULL ELSE TRIM([Childrens_Age_11_15_Unknown]) END AS [Childrens_Age_11_15_Unknown],
	CASE WHEN TRIM([Childrens_Age_16_17]) IN ('','NULL') THEN NULL ELSE TRIM([Childrens_Age_16_17]) END AS [Childrens_Age_16_17],
	CASE WHEN TRIM([Childrens_Age_16_17_Male]) IN ('','NULL') THEN NULL ELSE TRIM([Childrens_Age_16_17_Male]) END AS [Childrens_Age_16_17_Male],
	CASE WHEN TRIM([Childrens_Age_16_17_Female]) IN ('','NULL') THEN NULL ELSE TRIM([Childrens_Age_16_17_Female]) END AS [Childrens_Age_16_17_Female],
	CASE WHEN TRIM([Childrens_Age_16_17_Unknown]) IN ('','NULL') THEN NULL ELSE TRIM([Childrens_Age_16_17_Unknown]) END AS [Childrens_Age_16_17_Unknown],
	CASE WHEN TRIM([Child_Near_High_School_Graduation]) IN ('','NULL') THEN NULL ELSE TRIM([Child_Near_High_School_Graduation]) END AS [Child_Near_High_School_Graduation],
	CASE WHEN TRIM([College_Graduate]) IN ('','NULL') THEN NULL ELSE TRIM([College_Graduate]) END AS [College_Graduate],
	CASE WHEN TRIM([Christian_Families]) IN ('','NULL') THEN NULL ELSE TRIM([Christian_Families]) END AS [Christian_Families],
	CASE WHEN TRIM([Business_Owner]) IN ('','NULL') THEN NULL ELSE TRIM([Business_Owner]) END AS [Business_Owner],
	CASE WHEN TRIM([SOHO]) IN ('','NULL') THEN NULL ELSE TRIM([SOHO]) END AS [SOHO],
	CASE WHEN TRIM([Working_Woman]) IN ('','NULL') THEN NULL ELSE TRIM([Working_Woman]) END AS [Working_Woman],
	CASE WHEN TRIM([Veteran_Present_In_Household]) IN ('','NULL') THEN NULL ELSE TRIM([Veteran_Present_In_Household]) END AS [Veteran_Present_In_Household],
	CASE WHEN TRIM([Credit_Card_User]) IN ('','NULL') THEN NULL ELSE TRIM([Credit_Card_User]) END AS [Credit_Card_User],
	CASE WHEN TRIM([Mail_Order_Donor]) IN ('','NULL') THEN NULL ELSE TRIM([Mail_Order_Donor]) END AS [Mail_Order_Donor],
	CASE WHEN TRIM([Mail_Order_Buyer]) IN ('','NULL') THEN NULL ELSE TRIM([Mail_Order_Buyer]) END AS [Mail_Order_Buyer],
	CASE WHEN TRIM([Mail_Order_Responder]) IN ('','NULL') THEN NULL ELSE TRIM([Mail_Order_Responder]) END AS [Mail_Order_Responder],
	CASE WHEN TRIM([TV_Satellite_Dish]) IN ('','NULL') THEN NULL ELSE TRIM([TV_Satellite_Dish]) END AS [TV_Satellite_Dish],
	CASE WHEN TRIM([Pet_Owner]) IN ('','NULL') THEN NULL ELSE TRIM([Pet_Owner]) END AS [Pet_Owner],
	CASE WHEN TRIM([Cat_Owner]) IN ('','NULL') THEN NULL ELSE TRIM([Cat_Owner]) END AS [Cat_Owner],
	CASE WHEN TRIM([Dog_Owner]) IN ('','NULL') THEN NULL ELSE TRIM([Dog_Owner]) END AS [Dog_Owner],
	CASE WHEN TRIM([Other_Pet_Owner]) IN ('','NULL') THEN NULL ELSE TRIM([Other_Pet_Owner]) END AS [Other_Pet_Owner],
	CASE WHEN TRIM([New_Teen_Driver]) IN ('','NULL') THEN NULL ELSE TRIM([New_Teen_Driver]) END AS [New_Teen_Driver],
	CASE WHEN TRIM([New_Teen_Driver_Gender]) IN ('','NULL') THEN NULL ELSE TRIM([New_Teen_Driver_Gender]) END AS [New_Teen_Driver_Gender],
	CASE WHEN TRIM([Boat_Owner]) IN ('','NULL') THEN NULL ELSE TRIM([Boat_Owner]) END AS [Boat_Owner],
	CASE WHEN TRIM([Truck_Owner]) IN ('','NULL') THEN NULL ELSE TRIM([Truck_Owner]) END AS [Truck_Owner],
	CASE WHEN TRIM([Motorcycle_Owner]) IN ('','NULL') THEN NULL ELSE TRIM([Motorcycle_Owner]) END AS [Motorcycle_Owner],
	CASE WHEN TRIM([RV_Owner]) IN ('','NULL') THEN NULL ELSE TRIM([RV_Owner]) END AS [RV_Owner],
	CASE WHEN TRIM([Auto_Buy_New]) IN ('','NULL') THEN NULL ELSE TRIM([Auto_Buy_New]) END AS [Auto_Buy_New],
	CASE WHEN TRIM([Auto_Buy_Used]) IN ('','NULL') THEN NULL ELSE TRIM([Auto_Buy_Used]) END AS [Auto_Buy_Used],
	CASE WHEN TRIM([Auto_Buy_Used_5_Months_Or_Less]) IN ('','NULL') THEN NULL ELSE TRIM([Auto_Buy_Used_5_Months_Or_Less]) END AS [Auto_Buy_Used_5_Months_Or_Less],
	CASE WHEN TRIM([Auto_Buy_Used_6_Months_Or_More]) IN ('','NULL') THEN NULL ELSE TRIM([Auto_Buy_Used_6_Months_Or_More]) END AS [Auto_Buy_Used_6_Months_Or_More],
	CASE WHEN TRIM([Median_HseHld_Income]) IN ('','NULL') THEN NULL ELSE TRIM([Median_HseHld_Income]) END AS [Median_HseHld_Income],
	CASE WHEN TRIM([Median_HseHld_Income_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Median_HseHld_Income_Code]) END AS [Median_HseHld_Income_Code],
	CASE WHEN TRIM([Median_HseHld_Income_Description]) IN ('','NULL') THEN NULL ELSE TRIM([Median_HseHld_Income_Description]) END AS [Median_HseHld_Income_Description],
	CASE WHEN TRIM([Income]) IN ('','NULL') THEN NULL ELSE TRIM([Income]) END AS [Income],
	CASE WHEN TRIM([Income_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Income_Code]) END AS [Income_Code],
	CASE WHEN TRIM([Income_Description]) IN ('','NULL') THEN NULL ELSE TRIM([Income_Description]) END AS [Income_Description],
	CASE WHEN TRIM([NetWorth]) IN ('','NULL') THEN NULL ELSE TRIM([NetWorth]) END AS [NetWorth],
	CASE WHEN TRIM([NetWorth_Code]) IN ('','NULL') THEN NULL ELSE TRIM([NetWorth_Code]) END AS [NetWorth_Code],
	CASE WHEN TRIM([NetWorth_Description]) IN ('','NULL') THEN NULL ELSE TRIM([NetWorth_Description]) END AS [NetWorth_Description],
	CASE WHEN TRIM([Millionaire]) IN ('','NULL') THEN NULL ELSE TRIM([Millionaire]) END AS [Millionaire],
	CASE WHEN TRIM([Unsecured_Credit_Capacity]) IN ('','NULL') THEN NULL ELSE TRIM([Unsecured_Credit_Capacity]) END AS [Unsecured_Credit_Capacity],
	CASE WHEN TRIM([Unsecured_Credit_Capacity_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Unsecured_Credit_Capacity_Code]) END AS [Unsecured_Credit_Capacity_Code],
	CASE WHEN TRIM([Unsecured_Credit_Capacity_Description]) IN ('','NULL') THEN NULL ELSE TRIM([Unsecured_Credit_Capacity_Description]) END AS [Unsecured_Credit_Capacity_Description],
	CASE WHEN TRIM([Discretionary_Income]) IN ('','NULL') THEN NULL ELSE TRIM([Discretionary_Income]) END AS [Discretionary_Income],
	CASE WHEN TRIM([Discretionary_Income_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Discretionary_Income_Code]) END AS [Discretionary_Income_Code],
	CASE WHEN TRIM([Discretionary_Income_Description]) IN ('','NULL') THEN NULL ELSE TRIM([Discretionary_Income_Description]) END AS [Discretionary_Income_Description],
	CASE WHEN TRIM([Donor_Capacity]) IN ('','NULL') THEN NULL ELSE TRIM([Donor_Capacity]) END AS [Donor_Capacity],
	CASE WHEN TRIM([Donor_Capacity_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Donor_Capacity_Code]) END AS [Donor_Capacity_Code],
	CASE WHEN TRIM([Donor_Capacity_Description]) IN ('','NULL') THEN NULL ELSE TRIM([Donor_Capacity_Description]) END AS [Donor_Capacity_Description],
	CASE WHEN TRIM([Investment_Properties_Owned]) IN ('','NULL') THEN NULL ELSE TRIM([Investment_Properties_Owned]) END AS [Investment_Properties_Owned],
	CASE WHEN TRIM([Estimated_Area_Credit_Rating]) IN ('','NULL') THEN NULL ELSE TRIM([Estimated_Area_Credit_Rating]) END AS [Estimated_Area_Credit_Rating],
	CASE WHEN TRIM([CRA_Income_Classification_Code]) IN ('','NULL') THEN NULL ELSE TRIM([CRA_Income_Classification_Code]) END AS [CRA_Income_Classification_Code],
	CASE WHEN TRIM([Credit_Range_New_Credit]) IN ('','NULL') THEN NULL ELSE TRIM([Credit_Range_New_Credit]) END AS [Credit_Range_New_Credit],
	CASE WHEN TRIM([Lines_Of_Credit]) IN ('','NULL') THEN NULL ELSE TRIM([Lines_Of_Credit]) END AS [Lines_Of_Credit],
	CASE WHEN TRIM([Home_Property_Type]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Property_Type]) END AS [Home_Property_Type],
	CASE WHEN TRIM([Home_Property_Type_Detail]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Property_Type_Detail]) END AS [Home_Property_Type_Detail],
	CASE WHEN TRIM([Home_Value]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Value]) END AS [Home_Value],
	CASE WHEN TRIM([Home_Value_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Value_Code]) END AS [Home_Value_Code],
	CASE WHEN TRIM([Home_Value_Description]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Value_Description]) END AS [Home_Value_Description],
	CASE WHEN TRIM([Median_Home_Value]) IN ('','NULL') THEN NULL ELSE TRIM([Median_Home_Value]) END AS [Median_Home_Value],
	CASE WHEN TRIM([Median_Home_Value_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Median_Home_Value_Code]) END AS [Median_Home_Value_Code],
	CASE WHEN TRIM([Median_Home_Value_Description]) IN ('','NULL') THEN NULL ELSE TRIM([Median_Home_Value_Description]) END AS [Median_Home_Value_Description],
	CASE WHEN TRIM([Home_Built_Year]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Built_Year]) END AS [Home_Built_Year],
	CASE WHEN TRIM([Home_Built_Year_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Built_Year_Code]) END AS [Home_Built_Year_Code],
	CASE WHEN TRIM([Home_Built_Year_Description]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Built_Year_Description]) END AS [Home_Built_Year_Description],
	CASE WHEN TRIM([Home_Square_Footage]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Square_Footage]) END AS [Home_Square_Footage],
	CASE WHEN TRIM([Home_Square_Footage_Range]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Square_Footage_Range]) END AS [Home_Square_Footage_Range],
	CASE WHEN TRIM([Land_Square_Footage]) IN ('','NULL') THEN NULL ELSE TRIM([Land_Square_Footage]) END AS [Land_Square_Footage],
	CASE WHEN TRIM([Number_Of_Bedrooms]) IN ('','NULL') THEN NULL ELSE TRIM([Number_Of_Bedrooms]) END AS [Number_Of_Bedrooms],
	CASE WHEN TRIM([Number_Of_Bathrooms]) IN ('','NULL') THEN NULL ELSE TRIM([Number_Of_Bathrooms]) END AS [Number_Of_Bathrooms],
	CASE WHEN TRIM([Home_Air_Conditioning]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Air_Conditioning]) END AS [Home_Air_Conditioning],
	CASE WHEN TRIM([Home_Swimming_Pool]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Swimming_Pool]) END AS [Home_Swimming_Pool],
	CASE WHEN TRIM([Home_Sewer]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Sewer]) END AS [Home_Sewer],
	CASE WHEN TRIM([Home_Water]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Water]) END AS [Home_Water],
	CASE WHEN TRIM([Recent_Home_Buyer]) IN ('','NULL') THEN NULL ELSE TRIM([Recent_Home_Buyer]) END AS [Recent_Home_Buyer],
	CASE WHEN TRIM([Recent_Mortgage_Borrower]) IN ('','NULL') THEN NULL ELSE TRIM([Recent_Mortgage_Borrower]) END AS [Recent_Mortgage_Borrower],
	CASE WHEN TRIM([New_Home_Owner_Flag]) IN ('','NULL') THEN NULL ELSE TRIM([New_Home_Owner_Flag]) END AS [New_Home_Owner_Flag],
	CASE WHEN TRIM([Most_Recent_Home_Purchase_Date_Flag]) IN ('','NULL') THEN NULL ELSE TRIM([Most_Recent_Home_Purchase_Date_Flag]) END AS [Most_Recent_Home_Purchase_Date_Flag],
	CASE WHEN TRIM([Home_Purchase_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Purchase_Date]) END AS [Home_Purchase_Date],
	CASE WHEN TRIM([Home_Purchase_Year]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Purchase_Year]) END AS [Home_Purchase_Year],
	CASE WHEN TRIM([Home_Purchase_Amount]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Purchase_Amount]) END AS [Home_Purchase_Amount],
	CASE WHEN TRIM([Home_Assessed_Value]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Assessed_Value]) END AS [Home_Assessed_Value],
	CASE WHEN TRIM([Home_Total_Loan]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Total_Loan]) END AS [Home_Total_Loan],
	CASE WHEN TRIM([Home_Loan_Date_1_Year]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Date_1_Year]) END AS [Home_Loan_Date_1_Year],
	CASE WHEN TRIM([Home_Loan_Date_1_Month]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Date_1_Month]) END AS [Home_Loan_Date_1_Month],
	CASE WHEN TRIM([Home_Loan_Date_2_Year]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Date_2_Year]) END AS [Home_Loan_Date_2_Year],
	CASE WHEN TRIM([Home_Loan_Date_2_Month]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Date_2_Month]) END AS [Home_Loan_Date_2_Month],
	CASE WHEN TRIM([Home_Loan_Date_3_Year]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Date_3_Year]) END AS [Home_Loan_Date_3_Year],
	CASE WHEN TRIM([Home_Loan_Date_3_Month]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Date_3_Month]) END AS [Home_Loan_Date_3_Month],
	CASE WHEN TRIM([Home_Loan_Amount_1]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Amount_1]) END AS [Home_Loan_Amount_1],
	CASE WHEN TRIM([Home_Loan_Amount_2]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Amount_2]) END AS [Home_Loan_Amount_2],
	CASE WHEN TRIM([Home_Loan_Amount_3]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Amount_3]) END AS [Home_Loan_Amount_3],
	CASE WHEN TRIM([Home_Loan_Type_1]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Type_1]) END AS [Home_Loan_Type_1],
	CASE WHEN TRIM([Home_Loan_Type_2]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Type_2]) END AS [Home_Loan_Type_2],
	CASE WHEN TRIM([Home_Loan_Type_3]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Type_3]) END AS [Home_Loan_Type_3],
	CASE WHEN TRIM([Home_Loan_Interest_Rate_1]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Interest_Rate_1]) END AS [Home_Loan_Interest_Rate_1],
	CASE WHEN TRIM([Home_Loan_Interest_Rate_2]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Interest_Rate_2]) END AS [Home_Loan_Interest_Rate_2],
	CASE WHEN TRIM([Home_Loan_Interest_Rate_3]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Interest_Rate_3]) END AS [Home_Loan_Interest_Rate_3],
	CASE WHEN TRIM([Home_Loan_Interest_Rate_Type_1]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Interest_Rate_Type_1]) END AS [Home_Loan_Interest_Rate_Type_1],
	CASE WHEN TRIM([Home_Loan_Interest_Rate_Type_2]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Interest_Rate_Type_2]) END AS [Home_Loan_Interest_Rate_Type_2],
	CASE WHEN TRIM([Home_Loan_Interest_Rate_Type_3]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Interest_Rate_Type_3]) END AS [Home_Loan_Interest_Rate_Type_3],
	CASE WHEN TRIM([Home_Loan_Transaction_Type_1]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Transaction_Type_1]) END AS [Home_Loan_Transaction_Type_1],
	CASE WHEN TRIM([Home_Loan_Transaction_Type_2]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Transaction_Type_2]) END AS [Home_Loan_Transaction_Type_2],
	CASE WHEN TRIM([Home_Loan_Transaction_Type_3]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Transaction_Type_3]) END AS [Home_Loan_Transaction_Type_3],
	CASE WHEN TRIM([Home_Loan_Lender_Name_1]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Lender_Name_1]) END AS [Home_Loan_Lender_Name_1],
	CASE WHEN TRIM([Home_Loan_Lender_Name_2]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Lender_Name_2]) END AS [Home_Loan_Lender_Name_2],
	CASE WHEN TRIM([Home_Loan_Lender_Name_3]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_Lender_Name_3]) END AS [Home_Loan_Lender_Name_3],
	CASE WHEN TRIM([Home_Loan_To_Value_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Loan_To_Value_Code]) END AS [Home_Loan_To_Value_Code],
	CASE WHEN TRIM([Home_Equity_Available_Code]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Equity_Available_Code]) END AS [Home_Equity_Available_Code],
	CASE WHEN TRIM([Home_Equity_Available_Description]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Equity_Available_Description]) END AS [Home_Equity_Available_Description],
	CASE WHEN TRIM([Donor_Charitable]) IN ('','NULL') THEN NULL ELSE TRIM([Donor_Charitable]) END AS [Donor_Charitable],
	CASE WHEN TRIM([Donor_Animal_Welfare]) IN ('','NULL') THEN NULL ELSE TRIM([Donor_Animal_Welfare]) END AS [Donor_Animal_Welfare],
	CASE WHEN TRIM([Donor_Arts_Cultural]) IN ('','NULL') THEN NULL ELSE TRIM([Donor_Arts_Cultural]) END AS [Donor_Arts_Cultural],
	CASE WHEN TRIM([Donor_Childrens]) IN ('','NULL') THEN NULL ELSE TRIM([Donor_Childrens]) END AS [Donor_Childrens],
	CASE WHEN TRIM([Donor_Environment_Wildlife]) IN ('','NULL') THEN NULL ELSE TRIM([Donor_Environment_Wildlife]) END AS [Donor_Environment_Wildlife],
	CASE WHEN TRIM([Donor_Health]) IN ('','NULL') THEN NULL ELSE TRIM([Donor_Health]) END AS [Donor_Health],
	CASE WHEN TRIM([Donor_International_Aid]) IN ('','NULL') THEN NULL ELSE TRIM([Donor_International_Aid]) END AS [Donor_International_Aid],
	CASE WHEN TRIM([Donor_Political]) IN ('','NULL') THEN NULL ELSE TRIM([Donor_Political]) END AS [Donor_Political],
	CASE WHEN TRIM([Donor_Political_Conservative]) IN ('','NULL') THEN NULL ELSE TRIM([Donor_Political_Conservative]) END AS [Donor_Political_Conservative],
	CASE WHEN TRIM([Donor_Political_Liberal]) IN ('','NULL') THEN NULL ELSE TRIM([Donor_Political_Liberal]) END AS [Donor_Political_Liberal],
	CASE WHEN TRIM([Donor_Religious]) IN ('','NULL') THEN NULL ELSE TRIM([Donor_Religious]) END AS [Donor_Religious],
	CASE WHEN TRIM([Donor_Veterans]) IN ('','NULL') THEN NULL ELSE TRIM([Donor_Veterans]) END AS [Donor_Veterans],
	CASE WHEN TRIM([CC_American_Express]) IN ('','NULL') THEN NULL ELSE TRIM([CC_American_Express]) END AS [CC_American_Express],
	CASE WHEN TRIM([CC_American_Express_Gold_Platinum]) IN ('','NULL') THEN NULL ELSE TRIM([CC_American_Express_Gold_Platinum]) END AS [CC_American_Express_Gold_Platinum],
	CASE WHEN TRIM([CC_Discover]) IN ('','NULL') THEN NULL ELSE TRIM([CC_Discover]) END AS [CC_Discover],
	CASE WHEN TRIM([CC_Visa]) IN ('','NULL') THEN NULL ELSE TRIM([CC_Visa]) END AS [CC_Visa],
	CASE WHEN TRIM([CC_Mastercard]) IN ('','NULL') THEN NULL ELSE TRIM([CC_Mastercard]) END AS [CC_Mastercard],
	CASE WHEN TRIM([CC_Bank]) IN ('','NULL') THEN NULL ELSE TRIM([CC_Bank]) END AS [CC_Bank],
	CASE WHEN TRIM([CC_Gas_Dept_Retail]) IN ('','NULL') THEN NULL ELSE TRIM([CC_Gas_Dept_Retail]) END AS [CC_Gas_Dept_Retail],
	CASE WHEN TRIM([CC_Travel_Entertainment]) IN ('','NULL') THEN NULL ELSE TRIM([CC_Travel_Entertainment]) END AS [CC_Travel_Entertainment],
	CASE WHEN TRIM([CC_Unknown]) IN ('','NULL') THEN NULL ELSE TRIM([CC_Unknown]) END AS [CC_Unknown],
	CASE WHEN TRIM([CC_Gold_Platinum]) IN ('','NULL') THEN NULL ELSE TRIM([CC_Gold_Platinum]) END AS [CC_Gold_Platinum],
	CASE WHEN TRIM([CC_Premium]) IN ('','NULL') THEN NULL ELSE TRIM([CC_Premium]) END AS [CC_Premium],
	CASE WHEN TRIM([CC_Upscale_Dept]) IN ('','NULL') THEN NULL ELSE TRIM([CC_Upscale_Dept]) END AS [CC_Upscale_Dept],
	CASE WHEN TRIM([CC_New_Issue]) IN ('','NULL') THEN NULL ELSE TRIM([CC_New_Issue]) END AS [CC_New_Issue],
	CASE WHEN TRIM([Home_Living]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Living]) END AS [Home_Living],
	CASE WHEN TRIM([DIY_Living]) IN ('','NULL') THEN NULL ELSE TRIM([DIY_Living]) END AS [DIY_Living],
	CASE WHEN TRIM([Sporty_Living]) IN ('','NULL') THEN NULL ELSE TRIM([Sporty_Living]) END AS [Sporty_Living],
	CASE WHEN TRIM([Upscale_Living]) IN ('','NULL') THEN NULL ELSE TRIM([Upscale_Living]) END AS [Upscale_Living],
	CASE WHEN TRIM([Cultural_Artistic_Living]) IN ('','NULL') THEN NULL ELSE TRIM([Cultural_Artistic_Living]) END AS [Cultural_Artistic_Living],
	CASE WHEN TRIM([Highbrow]) IN ('','NULL') THEN NULL ELSE TRIM([Highbrow]) END AS [Highbrow],
	CASE WHEN TRIM([Common_Living]) IN ('','NULL') THEN NULL ELSE TRIM([Common_Living]) END AS [Common_Living],
	CASE WHEN TRIM([Professional_Living]) IN ('','NULL') THEN NULL ELSE TRIM([Professional_Living]) END AS [Professional_Living],
	CASE WHEN TRIM([Broader_Living]) IN ('','NULL') THEN NULL ELSE TRIM([Broader_Living]) END AS [Broader_Living],
	CASE WHEN TRIM([Arts]) IN ('','NULL') THEN NULL ELSE TRIM([Arts]) END AS [Arts],
	CASE WHEN TRIM([Theater_Performing_Arts]) IN ('','NULL') THEN NULL ELSE TRIM([Theater_Performing_Arts]) END AS [Theater_Performing_Arts],
	CASE WHEN TRIM([Food_Wines]) IN ('','NULL') THEN NULL ELSE TRIM([Food_Wines]) END AS [Food_Wines],
	CASE WHEN TRIM([Foods_Natural]) IN ('','NULL') THEN NULL ELSE TRIM([Foods_Natural]) END AS [Foods_Natural],
	CASE WHEN TRIM([Cooking_General]) IN ('','NULL') THEN NULL ELSE TRIM([Cooking_General]) END AS [Cooking_General],
	CASE WHEN TRIM([Cooking_Gourmet]) IN ('','NULL') THEN NULL ELSE TRIM([Cooking_Gourmet]) END AS [Cooking_Gourmet],
	CASE WHEN TRIM([Aviation]) IN ('','NULL') THEN NULL ELSE TRIM([Aviation]) END AS [Aviation],
	CASE WHEN TRIM([Auto_Work]) IN ('','NULL') THEN NULL ELSE TRIM([Auto_Work]) END AS [Auto_Work],
	CASE WHEN TRIM([Automotive_Buff]) IN ('','NULL') THEN NULL ELSE TRIM([Automotive_Buff]) END AS [Automotive_Buff],
	CASE WHEN TRIM([Beauty_Cosmetics]) IN ('','NULL') THEN NULL ELSE TRIM([Beauty_Cosmetics]) END AS [Beauty_Cosmetics],
	CASE WHEN TRIM([Career]) IN ('','NULL') THEN NULL ELSE TRIM([Career]) END AS [Career],
	CASE WHEN TRIM([Career_Improvement]) IN ('','NULL') THEN NULL ELSE TRIM([Career_Improvement]) END AS [Career_Improvement],
	CASE WHEN TRIM([Parenting]) IN ('','NULL') THEN NULL ELSE TRIM([Parenting]) END AS [Parenting],
	CASE WHEN TRIM([Childrens_Interests]) IN ('','NULL') THEN NULL ELSE TRIM([Childrens_Interests]) END AS [Childrens_Interests],
	CASE WHEN TRIM([Grandchildren]) IN ('','NULL') THEN NULL ELSE TRIM([Grandchildren]) END AS [Grandchildren],
	CASE WHEN TRIM([Community_Charities]) IN ('','NULL') THEN NULL ELSE TRIM([Community_Charities]) END AS [Community_Charities],
	CASE WHEN TRIM([Religious_Inspirational]) IN ('','NULL') THEN NULL ELSE TRIM([Religious_Inspirational]) END AS [Religious_Inspirational],
	CASE WHEN TRIM([Crafts]) IN ('','NULL') THEN NULL ELSE TRIM([Crafts]) END AS [Crafts],
	CASE WHEN TRIM([Photography]) IN ('','NULL') THEN NULL ELSE TRIM([Photography]) END AS [Photography],
	CASE WHEN TRIM([Sewing_Knitting_Needlework]) IN ('','NULL') THEN NULL ELSE TRIM([Sewing_Knitting_Needlework]) END AS [Sewing_Knitting_Needlework],
	CASE WHEN TRIM([Collector_Avid]) IN ('','NULL') THEN NULL ELSE TRIM([Collector_Avid]) END AS [Collector_Avid],
	CASE WHEN TRIM([Collectibles_Grouping]) IN ('','NULL') THEN NULL ELSE TRIM([Collectibles_Grouping]) END AS [Collectibles_Grouping],
	CASE WHEN TRIM([Collectibles_General]) IN ('','NULL') THEN NULL ELSE TRIM([Collectibles_General]) END AS [Collectibles_General],
	CASE WHEN TRIM([Collectibles_Stamps]) IN ('','NULL') THEN NULL ELSE TRIM([Collectibles_Stamps]) END AS [Collectibles_Stamps],
	CASE WHEN TRIM([Collectibles_Coins]) IN ('','NULL') THEN NULL ELSE TRIM([Collectibles_Coins]) END AS [Collectibles_Coins],
	CASE WHEN TRIM([Collectibles_Arts]) IN ('','NULL') THEN NULL ELSE TRIM([Collectibles_Arts]) END AS [Collectibles_Arts],
	CASE WHEN TRIM([Collectibles_Antiques]) IN ('','NULL') THEN NULL ELSE TRIM([Collectibles_Antiques]) END AS [Collectibles_Antiques],
	CASE WHEN TRIM([Collectibles_Sports_Memorabilia]) IN ('','NULL') THEN NULL ELSE TRIM([Collectibles_Sports_Memorabilia]) END AS [Collectibles_Sports_Memorabilia],
	CASE WHEN TRIM([Education_Online]) IN ('','NULL') THEN NULL ELSE TRIM([Education_Online]) END AS [Education_Online],
	CASE WHEN TRIM([Exercise_Aerobic]) IN ('','NULL') THEN NULL ELSE TRIM([Exercise_Aerobic]) END AS [Exercise_Aerobic],
	CASE WHEN TRIM([Exercise_Running_Jogging]) IN ('','NULL') THEN NULL ELSE TRIM([Exercise_Running_Jogging]) END AS [Exercise_Running_Jogging],
	CASE WHEN TRIM([Exercise_Walking]) IN ('','NULL') THEN NULL ELSE TRIM([Exercise_Walking]) END AS [Exercise_Walking],
	CASE WHEN TRIM([High_Tech_General]) IN ('','NULL') THEN NULL ELSE TRIM([High_Tech_General]) END AS [High_Tech_General],
	CASE WHEN TRIM([Games_Computer_Games]) IN ('','NULL') THEN NULL ELSE TRIM([Games_Computer_Games]) END AS [Games_Computer_Games],
	CASE WHEN TRIM([Games_Video_Games]) IN ('','NULL') THEN NULL ELSE TRIM([Games_Video_Games]) END AS [Games_Video_Games],
	CASE WHEN TRIM([Games_Board_Puzzles]) IN ('','NULL') THEN NULL ELSE TRIM([Games_Board_Puzzles]) END AS [Games_Board_Puzzles],
	CASE WHEN TRIM([Gaming_Casino]) IN ('','NULL') THEN NULL ELSE TRIM([Gaming_Casino]) END AS [Gaming_Casino],
	CASE WHEN TRIM([Consumer_Electronics]) IN ('','NULL') THEN NULL ELSE TRIM([Consumer_Electronics]) END AS [Consumer_Electronics],
	CASE WHEN TRIM([Environmental_Issues]) IN ('','NULL') THEN NULL ELSE TRIM([Environmental_Issues]) END AS [Environmental_Issues],
	CASE WHEN TRIM([Gardening]) IN ('','NULL') THEN NULL ELSE TRIM([Gardening]) END AS [Gardening],
	CASE WHEN TRIM([Home_Furnishings_Decorating]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Furnishings_Decorating]) END AS [Home_Furnishings_Decorating],
	CASE WHEN TRIM([House_Plant]) IN ('','NULL') THEN NULL ELSE TRIM([House_Plant]) END AS [House_Plant],
	CASE WHEN TRIM([Home_Improvement_Grouping]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Improvement_Grouping]) END AS [Home_Improvement_Grouping],
	CASE WHEN TRIM([Home_Improvement]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Improvement]) END AS [Home_Improvement],
	CASE WHEN TRIM([Home_Improvement_DIY]) IN ('','NULL') THEN NULL ELSE TRIM([Home_Improvement_DIY]) END AS [Home_Improvement_DIY],
	CASE WHEN TRIM([Health_Medical]) IN ('','NULL') THEN NULL ELSE TRIM([Health_Medical]) END AS [Health_Medical],
	CASE WHEN TRIM([Dieting_Weight_Loss]) IN ('','NULL') THEN NULL ELSE TRIM([Dieting_Weight_Loss]) END AS [Dieting_Weight_Loss],
	CASE WHEN TRIM([Self_Improvement]) IN ('','NULL') THEN NULL ELSE TRIM([Self_Improvement]) END AS [Self_Improvement],
	CASE WHEN TRIM([Investments_Grouping]) IN ('','NULL') THEN NULL ELSE TRIM([Investments_Grouping]) END AS [Investments_Grouping],
	CASE WHEN TRIM([Investments_Foreign]) IN ('','NULL') THEN NULL ELSE TRIM([Investments_Foreign]) END AS [Investments_Foreign],
	CASE WHEN TRIM([Investments_Personal]) IN ('','NULL') THEN NULL ELSE TRIM([Investments_Personal]) END AS [Investments_Personal],
	CASE WHEN TRIM([Investments_Real_Estate]) IN ('','NULL') THEN NULL ELSE TRIM([Investments_Real_Estate]) END AS [Investments_Real_Estate],
	CASE WHEN TRIM([Investments_Stocks_Bonds]) IN ('','NULL') THEN NULL ELSE TRIM([Investments_Stocks_Bonds]) END AS [Investments_Stocks_Bonds],
	CASE WHEN TRIM([Money_Seekers]) IN ('','NULL') THEN NULL ELSE TRIM([Money_Seekers]) END AS [Money_Seekers],
	CASE WHEN TRIM([Sweepstakes_Contests]) IN ('','NULL') THEN NULL ELSE TRIM([Sweepstakes_Contests]) END AS [Sweepstakes_Contests],
	CASE WHEN TRIM([Music_Home_Stereo]) IN ('','NULL') THEN NULL ELSE TRIM([Music_Home_Stereo]) END AS [Music_Home_Stereo],
	CASE WHEN TRIM([Music_Player]) IN ('','NULL') THEN NULL ELSE TRIM([Music_Player]) END AS [Music_Player],
	CASE WHEN TRIM([Music_Collector]) IN ('','NULL') THEN NULL ELSE TRIM([Music_Collector]) END AS [Music_Collector],
	CASE WHEN TRIM([Music_Listener]) IN ('','NULL') THEN NULL ELSE TRIM([Music_Listener]) END AS [Music_Listener],
	CASE WHEN TRIM([Movie_Grouping]) IN ('','NULL') THEN NULL ELSE TRIM([Movie_Grouping]) END AS [Movie_Grouping],
	CASE WHEN TRIM([Movie_Music_General]) IN ('','NULL') THEN NULL ELSE TRIM([Movie_Music_General]) END AS [Movie_Music_General],
	CASE WHEN TRIM([Movie_Collector]) IN ('','NULL') THEN NULL ELSE TRIM([Movie_Collector]) END AS [Movie_Collector],
	CASE WHEN TRIM([Reading_General]) IN ('','NULL') THEN NULL ELSE TRIM([Reading_General]) END AS [Reading_General],
	CASE WHEN TRIM([Reading_Audio_Books]) IN ('','NULL') THEN NULL ELSE TRIM([Reading_Audio_Books]) END AS [Reading_Audio_Books],
	CASE WHEN TRIM([Reading_Magazines]) IN ('','NULL') THEN NULL ELSE TRIM([Reading_Magazines]) END AS [Reading_Magazines],
	CASE WHEN TRIM([Reading_Religious_Inspirational]) IN ('','NULL') THEN NULL ELSE TRIM([Reading_Religious_Inspirational]) END AS [Reading_Religious_Inspirational],
	CASE WHEN TRIM([Reading_Science_Fiction]) IN ('','NULL') THEN NULL ELSE TRIM([Reading_Science_Fiction]) END AS [Reading_Science_Fiction],
	CASE WHEN TRIM([Reading_Financial_Newsletter_Subscribers]) IN ('','NULL') THEN NULL ELSE TRIM([Reading_Financial_Newsletter_Subscribers]) END AS [Reading_Financial_Newsletter_Subscribers],
	CASE WHEN TRIM([Current_Affairs_Politics]) IN ('','NULL') THEN NULL ELSE TRIM([Current_Affairs_Politics]) END AS [Current_Affairs_Politics],
	CASE WHEN TRIM([History_Military]) IN ('','NULL') THEN NULL ELSE TRIM([History_Military]) END AS [History_Military],
	CASE WHEN TRIM([Outdoor_Grouping]) IN ('','NULL') THEN NULL ELSE TRIM([Outdoor_Grouping]) END AS [Outdoor_Grouping],
	CASE WHEN TRIM([Outdoor_Enthusiast_General]) IN ('','NULL') THEN NULL ELSE TRIM([Outdoor_Enthusiast_General]) END AS [Outdoor_Enthusiast_General],
	CASE WHEN TRIM([Outdoor_Fishing]) IN ('','NULL') THEN NULL ELSE TRIM([Outdoor_Fishing]) END AS [Outdoor_Fishing],
	CASE WHEN TRIM([Outdoor_Boating_Sailing]) IN ('','NULL') THEN NULL ELSE TRIM([Outdoor_Boating_Sailing]) END AS [Outdoor_Boating_Sailing],
	CASE WHEN TRIM([Outdoor_Camping_Hiking]) IN ('','NULL') THEN NULL ELSE TRIM([Outdoor_Camping_Hiking]) END AS [Outdoor_Camping_Hiking],
	CASE WHEN TRIM([Outdoor_Hunting_Shooting]) IN ('','NULL') THEN NULL ELSE TRIM([Outdoor_Hunting_Shooting]) END AS [Outdoor_Hunting_Shooting],
	CASE WHEN TRIM([Outdoor_Scuba_Diving]) IN ('','NULL') THEN NULL ELSE TRIM([Outdoor_Scuba_Diving]) END AS [Outdoor_Scuba_Diving],
	CASE WHEN TRIM([Spectator_Sports_Grouping]) IN ('','NULL') THEN NULL ELSE TRIM([Spectator_Sports_Grouping]) END AS [Spectator_Sports_Grouping],
	CASE WHEN TRIM([Spectator_Sports_General]) IN ('','NULL') THEN NULL ELSE TRIM([Spectator_Sports_General]) END AS [Spectator_Sports_General],
	CASE WHEN TRIM([Spectator_Sports_Baseball]) IN ('','NULL') THEN NULL ELSE TRIM([Spectator_Sports_Baseball]) END AS [Spectator_Sports_Baseball],
	CASE WHEN TRIM([Spectator_Sports_Basketball]) IN ('','NULL') THEN NULL ELSE TRIM([Spectator_Sports_Basketball]) END AS [Spectator_Sports_Basketball],
	CASE WHEN TRIM([Spectator_Sports_Football]) IN ('','NULL') THEN NULL ELSE TRIM([Spectator_Sports_Football]) END AS [Spectator_Sports_Football],
	CASE WHEN TRIM([Spectator_Sports_Hockey]) IN ('','NULL') THEN NULL ELSE TRIM([Spectator_Sports_Hockey]) END AS [Spectator_Sports_Hockey],
	CASE WHEN TRIM([Spectator_Sports_Racing]) IN ('','NULL') THEN NULL ELSE TRIM([Spectator_Sports_Racing]) END AS [Spectator_Sports_Racing],
	CASE WHEN TRIM([Spectator_Sports_Soccer]) IN ('','NULL') THEN NULL ELSE TRIM([Spectator_Sports_Soccer]) END AS [Spectator_Sports_Soccer],
	CASE WHEN TRIM([Spectator_Sports_TV_Sports]) IN ('','NULL') THEN NULL ELSE TRIM([Spectator_Sports_TV_Sports]) END AS [Spectator_Sports_TV_Sports],
	CASE WHEN TRIM([Spectator_NASCAR]) IN ('','NULL') THEN NULL ELSE TRIM([Spectator_NASCAR]) END AS [Spectator_NASCAR],
	CASE WHEN TRIM([Smoking_Tobacco]) IN ('','NULL') THEN NULL ELSE TRIM([Smoking_Tobacco]) END AS [Smoking_Tobacco],
	CASE WHEN TRIM([Sports_Grouping]) IN ('','NULL') THEN NULL ELSE TRIM([Sports_Grouping]) END AS [Sports_Grouping],
	CASE WHEN TRIM([Sports_Equestrian]) IN ('','NULL') THEN NULL ELSE TRIM([Sports_Equestrian]) END AS [Sports_Equestrian],
	CASE WHEN TRIM([Sports_Golf]) IN ('','NULL') THEN NULL ELSE TRIM([Sports_Golf]) END AS [Sports_Golf],
	CASE WHEN TRIM([Sports_Motorcycling]) IN ('','NULL') THEN NULL ELSE TRIM([Sports_Motorcycling]) END AS [Sports_Motorcycling],
	CASE WHEN TRIM([Sports_Skiing]) IN ('','NULL') THEN NULL ELSE TRIM([Sports_Skiing]) END AS [Sports_Skiing],
	CASE WHEN TRIM([Sports_Tennis]) IN ('','NULL') THEN NULL ELSE TRIM([Sports_Tennis]) END AS [Sports_Tennis],
	CASE WHEN TRIM([Travel_Grouping]) IN ('','NULL') THEN NULL ELSE TRIM([Travel_Grouping]) END AS [Travel_Grouping],
	CASE WHEN TRIM([Travel_Cruises]) IN ('','NULL') THEN NULL ELSE TRIM([Travel_Cruises]) END AS [Travel_Cruises],
	CASE WHEN TRIM([Travel_Domestic]) IN ('','NULL') THEN NULL ELSE TRIM([Travel_Domestic]) END AS [Travel_Domestic],
	CASE WHEN TRIM([Travel_International]) IN ('','NULL') THEN NULL ELSE TRIM([Travel_International]) END AS [Travel_International],
	CASE WHEN TRIM([Travel_RV]) IN ('','NULL') THEN NULL ELSE TRIM([Travel_RV]) END AS [Travel_RV],
	CASE WHEN TRIM([Science_Space]) IN ('','NULL') THEN NULL ELSE TRIM([Science_Space]) END AS [Science_Space],
	CASE WHEN TRIM([Woodworking]) IN ('','NULL') THEN NULL ELSE TRIM([Woodworking]) END AS [Woodworking],
	CASE WHEN TRIM([Buyer_Books]) IN ('','NULL') THEN NULL ELSE TRIM([Buyer_Books]) END AS [Buyer_Books],
	CASE WHEN TRIM([Buyer_Crafts_Hobbies]) IN ('','NULL') THEN NULL ELSE TRIM([Buyer_Crafts_Hobbies]) END AS [Buyer_Crafts_Hobbies],
	CASE WHEN TRIM([Buyer_Gardening_Farming]) IN ('','NULL') THEN NULL ELSE TRIM([Buyer_Gardening_Farming]) END AS [Buyer_Gardening_Farming],
	CASE WHEN TRIM([Buyer_Jewelry]) IN ('','NULL') THEN NULL ELSE TRIM([Buyer_Jewelry]) END AS [Buyer_Jewelry],
	CASE WHEN TRIM([Buyer_Luggage]) IN ('','NULL') THEN NULL ELSE TRIM([Buyer_Luggage]) END AS [Buyer_Luggage],
	CASE WHEN TRIM([Buyer_Online]) IN ('','NULL') THEN NULL ELSE TRIM([Buyer_Online]) END AS [Buyer_Online],
	CASE WHEN TRIM([Buyer_Membership_Club]) IN ('','NULL') THEN NULL ELSE TRIM([Buyer_Membership_Club]) END AS [Buyer_Membership_Club],
	CASE WHEN TRIM([Buyer_Merchandise_Male]) IN ('','NULL') THEN NULL ELSE TRIM([Buyer_Merchandise_Male]) END AS [Buyer_Merchandise_Male],
	CASE WHEN TRIM([Buyer_Merchandise_Female]) IN ('','NULL') THEN NULL ELSE TRIM([Buyer_Merchandise_Female]) END AS [Buyer_Merchandise_Female],
	CASE WHEN TRIM([Buyer_Health_Beauty]) IN ('','NULL') THEN NULL ELSE TRIM([Buyer_Health_Beauty]) END AS [Buyer_Health_Beauty],
	CASE WHEN TRIM([Buyer_Childrens_Babycare]) IN ('','NULL') THEN NULL ELSE TRIM([Buyer_Childrens_Babycare]) END AS [Buyer_Childrens_Babycare],
	CASE WHEN TRIM([Buyer_Childrens_Learning_Toys]) IN ('','NULL') THEN NULL ELSE TRIM([Buyer_Childrens_Learning_Toys]) END AS [Buyer_Childrens_Learning_Toys],
	CASE WHEN TRIM([Buyer_Childrens_Back_To_School]) IN ('','NULL') THEN NULL ELSE TRIM([Buyer_Childrens_Back_To_School]) END AS [Buyer_Childrens_Back_To_School],
	CASE WHEN TRIM([Apparel_Childrens]) IN ('','NULL') THEN NULL ELSE TRIM([Apparel_Childrens]) END AS [Apparel_Childrens],
	CASE WHEN TRIM([Apparel_Infant_Toddlers]) IN ('','NULL') THEN NULL ELSE TRIM([Apparel_Infant_Toddlers]) END AS [Apparel_Infant_Toddlers],
	CASE WHEN TRIM([Apparel_Womens]) IN ('','NULL') THEN NULL ELSE TRIM([Apparel_Womens]) END AS [Apparel_Womens],
	CASE WHEN TRIM([Apparel_Womens_Petite]) IN ('','NULL') THEN NULL ELSE TRIM([Apparel_Womens_Petite]) END AS [Apparel_Womens_Petite],
	CASE WHEN TRIM([Apparel_Womens_Plus_Size]) IN ('','NULL') THEN NULL ELSE TRIM([Apparel_Womens_Plus_Size]) END AS [Apparel_Womens_Plus_Size],
	CASE WHEN TRIM([Apparel_Womens_Young]) IN ('','NULL') THEN NULL ELSE TRIM([Apparel_Womens_Young]) END AS [Apparel_Womens_Young],
	CASE WHEN TRIM([Apparel_Mens]) IN ('','NULL') THEN NULL ELSE TRIM([Apparel_Mens]) END AS [Apparel_Mens],
	CASE WHEN TRIM([Apparel_Mens_Big_Tall]) IN ('','NULL') THEN NULL ELSE TRIM([Apparel_Mens_Big_Tall]) END AS [Apparel_Mens_Big_Tall],
	CASE WHEN TRIM([Apparel_Mens_Young]) IN ('','NULL') THEN NULL ELSE TRIM([Apparel_Mens_Young]) END AS [Apparel_Mens_Young],
	CASE WHEN TRIM([Auto_Parts_Accessories]) IN ('','NULL') THEN NULL ELSE TRIM([Auto_Parts_Accessories]) END AS [Auto_Parts_Accessories],
	CASE WHEN TRIM([Military_Memorabilia_Weapons]) IN ('','NULL') THEN NULL ELSE TRIM([Military_Memorabilia_Weapons]) END AS [Military_Memorabilia_Weapons],
	CASE WHEN TRIM([Musical_Instruments]) IN ('','NULL') THEN NULL ELSE TRIM([Musical_Instruments]) END AS [Musical_Instruments],
	CASE WHEN TRIM([Photography_Video_Equipment]) IN ('','NULL') THEN NULL ELSE TRIM([Photography_Video_Equipment]) END AS [Photography_Video_Equipment],
	CASE WHEN TRIM([Sports_Leisure]) IN ('','NULL') THEN NULL ELSE TRIM([Sports_Leisure]) END AS [Sports_Leisure],
	CASE WHEN TRIM([Value_Hunter]) IN ('','NULL') THEN NULL ELSE TRIM([Value_Hunter]) END AS [Value_Hunter],
	CASE WHEN TRIM([Last_Update_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Last_Update_Date]) END AS [Last_Update_Date],
	CASE WHEN TRIM([Source_Data]) IN ('','NULL') THEN NULL ELSE TRIM([Source_Data]) END AS [Source_Data],
	CASE WHEN TRIM([Production_Date]) IN ('','NULL') THEN NULL ELSE TRIM([Production_Date]) END AS [Production_Date]
INTO [dbo].[Quantarium_Houseamp_WA_Select_DemoInd_20210622_New]
FROM [dbo].[Quantarium_Houseamp_WA_Select_DemoInd_20210622]


GO
RETURN
SET XACT_ABORT ON 
BEGIN transaction
DROP TABLE [dbo].[Quantarium_Houseamp_WA_Select_DemoInd_20210622]
EXEC sp_rename '[dbo].[Quantarium_Houseamp_WA_Select_DemoInd_20210622_New]','Quantarium_Houseamp_WA_Select_DemoInd_20210622','object'
COMMIT

ALTER TABLE [dbo].[Quantarium_Houseamp_WA_Select_DemoInd_20210622] REBUILD WITH (DATA_COMPRESSION = ROW)